import type { Level } from "@/lib/types";

export const LEVELS: Level[] = [
  {
    id: 0,
    slug: "computational-survival",
    title: "Computational Survival",
    codename: "BOOT",
    goal: "Operate a research environment: terminal, git, environments, debugging.",
    exitCriteria: [
      "Clone, install, run, modify, debug, commit and push a small project without help",
      "Read a stack trace and locate the failing line",
      "Comfortable living in a terminal for a full work session",
    ],
    phase: { startDay: 1, endDay: 10 },
    accent: "var(--acc-code)",
  },
  {
    id: 1,
    slug: "programming",
    title: "Programming From Zero",
    codename: "PYTHON",
    goal: "Write non-trivial Python programs independently; NumPy/Matplotlib fluency.",
    exitCriteria: [
      "Write a 150+ line program from a spec without AI writing it for you",
      "Vectorized NumPy replaces loops by reflex",
      "Tests written with pytest as a habit",
    ],
    bossId: "boss-programming",
    phase: { startDay: 1, endDay: 28 },
    accent: "var(--acc-code)",
  },
  {
    id: 2,
    slug: "math-bootloader",
    title: "Mathematical Bootloader",
    codename: "MATH",
    goal: "Grade-10 → working calculus, linear algebra, probability, optimization.",
    exitCriteria: [
      "Derive gradients by hand for small compositions (chain rule automatic)",
      "Implement least squares, eigen/SVD uses, and gradient descent in NumPy",
      "Read P(A|B), 𝔼[X], ∇f, J, Σ notation without friction",
    ],
    bossId: "boss-math",
    phase: { startDay: 1, endDay: 50 },
    accent: "var(--acc-math)",
  },
  {
    id: 3,
    slug: "ml-first-principles",
    title: "ML From First Principles",
    codename: "ML-CORE",
    goal: "Derive and implement learning systems before any framework hides them.",
    exitCriteria: [
      "Linear/logistic regression + MLP with backprop built from raw NumPy",
      "Explain bias/variance, regularization, leakage with concrete examples",
    ],
    phase: { startDay: 24, endDay: 45 },
    accent: "var(--acc-ml)",
  },
  {
    id: 4,
    slug: "deep-learning",
    title: "Deep Learning + PyTorch",
    codename: "DEEP",
    goal: "PyTorch fluency through Transformers, ViTs and multimodal representations.",
    exitCriteria: [
      "Implement multi-head causal attention from a blank file",
      "Trace every tensor shape through a Transformer and a ViT",
      "Train GPT-on-Shakespeare and ViT-on-CIFAR with sane loss curves",
    ],
    bossId: "boss-dl",
    phase: { startDay: 40, endDay: 70 },
    accent: "var(--acc-ml)",
  },
  {
    id: 5,
    slug: "robotics-geometry",
    title: "Robotics Geometry",
    codename: "SE(3)",
    goal: "Rotations, transforms, kinematics, built as your own library, PoE-first.",
    exitCriteria: [
      "Own SO(3)/SE(3) + FK/IK/Jacobian library matching reference oracles to 1e-6",
      "Explain why Euler angles fail and quaternions double-cover",
    ],
    bossId: "boss-robotics",
    phase: { startDay: 55, endDay: 85 },
    accent: "var(--acc-robot)",
  },
  {
    id: 6,
    slug: "control-estimation",
    title: "Control + Estimation",
    codename: "FEEDBACK",
    goal: "PID → LQR → MPC and Bayes → Kalman → particle filters, all implemented.",
    exitCriteria: [
      "Inverted pendulum stabilized by your PID and your LQR, compared quantitatively",
      "EKF tracks a noisy simulated system with consistent NEES/NIS",
    ],
    phase: { startDay: 70, endDay: 95 },
    accent: "var(--acc-robot)",
  },
  {
    id: 7,
    slug: "ros-simulation",
    title: "ROS 2 + Simulation",
    codename: "STACK",
    goal: "ROS 2 Jazzy literacy + MuJoCo depth: infrastructure, not identity.",
    exitCriteria: [
      "Simulated robot with sensors, ros2_control, launch files and bags, built by you",
      "Read C++ robotics code without fear",
    ],
    phase: { startDay: 80, endDay: 105 },
    accent: "var(--acc-robot)",
  },
  {
    id: 8,
    slug: "perception",
    title: "Perception",
    codename: "SEE",
    goal: "Camera geometry deeply; modern segmentation/depth as wired-in tools.",
    exitCriteria: [
      "Calibrate a camera, estimate 6-DoF object pose from RGB-D, localize in 3D",
      "SAM-3-class tools wired into a working pipeline",
    ],
    phase: { startDay: 95, endDay: 115 },
    accent: "var(--acc-robot)",
  },
  {
    id: 9,
    slug: "planning-autonomy",
    title: "Planning + Autonomy",
    codename: "PLAN",
    goal: "Search, sampling planners, grasping and the full perceive→plan→act loop.",
    exitCriteria: [
      "Simulated arm perceives an object, plans collision-free motion, grasps and places it",
    ],
    bossId: "boss-autonomy",
    phase: { startDay: 105, endDay: 125 },
    accent: "var(--acc-robot)",
  },
  {
    id: 10,
    slug: "reinforcement-learning",
    title: "Reinforcement Learning",
    codename: "REWARD",
    goal: "MDPs → PPO/SAC from scratch → GPU-parallel robot RL.",
    exitCriteria: [
      "Your PPO trains Hopper; ported to 2048 parallel envs it solves PushCube in minutes",
      "Explain GAE, clipping, entropy temperature without notes",
    ],
    phase: { startDay: 115, endDay: 140 },
    accent: "var(--acc-learn)",
  },
  {
    id: 11,
    slug: "imitation-learning",
    title: "Imitation Learning",
    codename: "IMITATE",
    goal: "BC → DAgger → ACT → Diffusion Policy (from scratch) → flow matching.",
    exitCriteria: [
      "Controlled BC vs ACT vs Diffusion comparison on PushT with seeds and CIs",
      "Your own diffusion action head converted to flow matching",
    ],
    bossId: "boss-robot-learning",
    phase: { startDay: 130, endDay: 152 },
    accent: "var(--acc-learn)",
  },
  {
    id: 12,
    slug: "vla",
    title: "Embodied Foundation Models / VLA",
    codename: "VLA",
    goal: "The five-paper spine, architecture anatomy, and your own VLA fine-tunes.",
    exitCriteria: [
      "SmolVLA fine-tuned and evaluated on LIBERO with the 400-episode protocol",
      "π0-class architecture reconstructed from memory (blocks, shapes, losses)",
    ],
    bossId: "boss-vla",
    phase: { startDay: 148, endDay: 172 },
    accent: "var(--acc-frontier)",
  },
  {
    id: 13,
    slug: "world-models",
    title: "World Models",
    codename: "DREAM",
    goal: "Latent dynamics, imagination training, video world models, and one trained WM.",
    exitCriteria: [
      "A world model trained by you (TD-MPC2/DINO-WM class) with a planning demo",
      "Argue both sides of the VLA-vs-world-model debate with evidence",
    ],
    phase: { startDay: 165, endDay: 180 },
    accent: "var(--acc-frontier)",
  },
  {
    id: 14,
    slug: "sim-to-real",
    title: "Sim-to-Real",
    codename: "REALITY",
    goal: "Reality gap, domain randomization, sim2sim discipline; hardware optional.",
    exitCriteria: [
      "DR ablation completed: policy robustness measured under perturbed dynamics",
      "Sim2sim transfer executed (train in GPU-parallel sim, validate in vanilla MuJoCo)",
    ],
    phase: { startDay: 172, endDay: 182 },
    accent: "var(--acc-frontier)",
  },
  {
    id: 15,
    slug: "research-apprenticeship",
    title: "Research Apprenticeship",
    codename: "METHOD",
    goal: "Paper reading, reproduction methodology, experiment design, from Month 2.",
    exitCriteria: [
      "One rigorous component-level reproduction with report, deviations and failure analysis",
      "Every claim you make backed by an experiment log entry",
    ],
    phase: { startDay: 35, endDay: 180 },
    accent: "var(--acc-research)",
  },
  {
    id: 16,
    slug: "original-research",
    title: "Original Research",
    codename: "FRONTIER",
    goal: "One narrow question and one falsifiable hypothesis, tested with rigorous evidence.",
    exitCriteria: [
      "Original hypothesis tested with baseline, controls, seeds, ablation",
      "Reproducible repository + technical report + future-work plan",
    ],
    bossId: "boss-final",
    phase: { startDay: 180, endDay: 210 },
    accent: "var(--acc-research)",
  },
];

export const levelById = (id: number) => LEVELS.find((l) => l.id === id)!;
