import type { Project } from "@/lib/types";

// The cumulative project ladder (HANDOVER §12), each reuses earlier work.
export const PROJECTS: Project[] = [
  {
    id: "p1-physics-toy", num: 1, title: "Numerical Physics Toy", levelWindow: [1, 1], hours: 7,
    purpose: "First real program: state, timesteps, integration, visualization, the skeleton of every simulator.",
    prereqNodeIds: ["l1-matplotlib", "l1-testing-modules"],
    minimum: ["Projectile with drag: state vector, Euler step, trajectory plot", "Parameter sweep (angle→range) with figure", "Tests for physics helpers"],
    stretch: ["Semi-implicit Euler + energy-drift comparison", "Bouncing ball or 2-body orbit"],
    metrics: ["Energy drift vs timestep quantified", "Tests green"],
    failureModes: ["Timestep too large → instability mistaken for physics", "Plotting each frame → 100× slowdown"],
    researchConnection: "Integration error here IS the sim2real gap in miniature.",
    artifact: "Repo + README with 3 figures + 10-line findings note.",
  },
  {
    id: "p2-linreg", num: 2, title: "Linear Regression From Scratch", levelWindow: [3, 3], hours: 4,
    purpose: "The E. coli of ML: loss, gradient, fit, generalization in their simplest living form.",
    prereqNodeIds: ["l3-linear-regression"],
    minimum: ["Normal equations + your GD on the same data", "Feature scaling demonstrated", "Train/val split with overfitting curve (poly degrees)"],
    stretch: ["Ridge penalty; MLE writeup (Gaussian noise ⇒ least squares)"],
    metrics: ["GD matches closed form to 1e-6", "Overfitting curve reproduces textbook shape"],
    failureModes: ["Unscaled features → divergence blamed on the algorithm", "Test-set peeking"],
    researchConnection: "Every training curve you'll ever read is this project at scale.",
    artifact: "Notebook + derivation page (∇L from scratch).",
  },
  {
    id: "p3-numpy-net", num: 3, title: "NumPy Neural Network", levelWindow: [3, 3], hours: 8,
    purpose: "The rite of passage: a neural net where you wrote every line, gradient-checked.",
    prereqNodeIds: ["l3-mlp-numpy"],
    minimum: ["2-layer MLP, vectorized forward/backward", "Gradient check every layer <1e-5", "Train to >95% on digits-class data"],
    stretch: ["L2 + early stopping study", "Your Adam from l3 plugged in"],
    metrics: ["Gradient-check tolerance", "Accuracy target", "One-sitting rebuild time"],
    failureModes: ["Transposed weight bug 'fixed' by shapes-until-it-runs", "Softmax overflow without max-subtraction"],
    researchConnection: "Gold-gates PyTorch: autograd never becomes magic.",
    artifact: "Repo with gradcheck suite; the blank-file rebuild is the Boss evidence.",
  },
  {
    id: "p4-classifier", num: 4, title: "CIFAR-10, Run Like a Researcher", levelWindow: [4, 4], hours: 6,
    purpose: "First full DL experiment with baselines, ablation, seeds, tracking; habits over accuracy.",
    prereqNodeIds: ["l4-classifier-project"],
    minimum: ["Linear probe → CNN → +aug → +schedule, each a tracked run", "≥90% test", "3-seed mean±std final table"],
    stretch: ["ResNet-18 from scratch", "One deliberate ablation quantified"],
    metrics: ["Accuracy", "Seed variance reported", "W&B project navigable"],
    failureModes: ["Tuning on test", "Un-seeded 'improvements'"],
    researchConnection: "The experiment-report format you'll reuse through Month 7.",
    artifact: "1-page experiment report + tracked runs.",
  },
  {
    id: "p5-tiny-transformer", num: 5, title: "Tiny Transformer (GPT-on-Shakespeare)", levelWindow: [4, 4], hours: 10,
    purpose: "Assemble attention into the architecture of the era; earn the microgpt cold-read.",
    prereqNodeIds: ["l4-transformer"],
    minimum: ["Decoder-only GPT, pre-LN, trained to coherent samples", "Overfit-1-batch sanity ritual documented", "Hand parameter-count vs numel()"],
    stretch: ["RoPE swap; residual-ablation study"],
    metrics: ["Val loss target", "Rebuild-from-memory in one sitting"],
    failureModes: ["Mask bugs producing 'working' cheating models", "LR too high hiding as architecture bugs"],
    researchConnection: "The exact architecture of every VLA backbone.",
    artifact: "Repo + samples + the microgpt cold-read annotations.",
  },
  {
    id: "p6-kinematics-viz", num: 6, title: "2D Kinematics Visualizer", levelWindow: [2, 5], hours: 3,
    purpose: "Trig meets robots early: a 2-link arm you can drag, months before formal FK.",
    prereqNodeIds: ["l2-trig"],
    minimum: ["Interactive 2-link arm (sliders/animation)", "Fingertip trace over joint sweeps"],
    stretch: ["Reachable-workspace scatter; simple pseudo-IK by gradient descent"],
    metrics: ["Correct geometry vs hand computation"],
    failureModes: ["Degrees/radians mixups (the classic)"],
    researchConnection: "The seed of P7 and everything kinematic.",
    artifact: "Single-file interactive script + GIF.",
  },
  {
    id: "p7-arm-kinematics", num: 7, title: "PandaKin: The Kinematics Library", levelWindow: [5, 5], hours: 12,
    purpose: "The program's robotics backbone: your own SE(3)/FK/IK/Jacobian stack, oracle-verified, reused forever.",
    prereqNodeIds: ["l5-ik", "l5-trajectories"],
    minimum: ["se3.py + kin.py + traj.py with property tests", "FK matches MuJoCo to 1e-6 (500 configs)", "IK ≥95% / <1mm / <0.5° benchmark", "Trajectory execution on UR5e"],
    stretch: ["7-DOF Panda + nullspace demo", "RNEA implementation matched to MR library"],
    metrics: ["Oracle deltas vs modern_robotics + roboticstoolbox", "IK benchmark table"],
    failureModes: ["Frame-convention drift between modules", "Testing only near home configuration"],
    researchConnection: "Screw-theory fluency = reading any manipulation paper's math.",
    artifact: "Installable package + CI tests + demo video (Boss evidence).",
  },
  {
    id: "p8-pid-system", num: 8, title: "PID-Controlled System", levelWindow: [6, 6], hours: 3,
    purpose: "First closed loop: feel P, I, D as behaviors, not letters.",
    prereqNodeIds: ["l6-feedback-pid"],
    minimum: ["PID with anti-windup holding a pendulum setpoint", "Step + sine tracking plots", "Each pathology demonstrated deliberately"],
    stretch: ["Auto-tune sweep heatmap over Kp/Kd"],
    metrics: ["Rise time / overshoot vs spec"],
    failureModes: ["Tuning on one disturbance profile"],
    researchConnection: "The low-level layer under every learned policy.",
    artifact: "Notebook with the pathology gallery.",
  },
  {
    id: "p9-inverted-pendulum", num: 9, title: "Inverted Pendulum, Three Ways", levelWindow: [6, 6], hours: 8,
    purpose: "One system, three controllers (PID/LQR/MPC), estimator in the loop, control engineering in miniature.",
    prereqNodeIds: ["l6-pendulum-project"],
    minimum: ["Swing-up + LQR catch", "PID vs LQR vs MPC comparison table", "KF-estimated state closing the loop"],
    stretch: ["Constraint-active MPC case LQR can't do", "Robustness sweep over mass error"],
    metrics: ["Settling time, effort, disturbance rejection, estimator degradation"],
    failureModes: ["Comparing controllers at different tunings ('strawman baselines')"],
    researchConnection: "Baseline discipline: identical conditions or the comparison is void.",
    artifact: "Video + comparison table + findings page (level gate).",
  },
  {
    id: "p10-kf-localization", num: 10, title: "Kalman Localization", levelWindow: [6, 6], hours: 5,
    purpose: "Estimation as a product: track a moving thing from lying sensors, prove consistency.",
    prereqNodeIds: ["l6-kalman"],
    minimum: ["2D constant-velocity tracker", "NEES/NIS consistency over 100 Monte-Carlo runs", "Mis-tuning study (R ×100 both ways)"],
    stretch: ["EKF unicycle + landmark version; PF comparison with kidnapping"],
    metrics: ["NEES within chi-square bounds", "RMSE vs measurement-only baseline"],
    failureModes: ["A filter that 'looks smooth' but is inconsistent (overconfident)"],
    researchConnection: "Uncertainty honesty: the same discipline as reporting CIs.",
    artifact: "est.py + consistency plots.",
  },
  {
    id: "p11-ros-robot", num: 11, title: "Integrated ROS Robot ('Wanderer')", levelWindow: [7, 7], hours: 6,
    purpose: "A complete sense→compute→act system in the field's middleware.",
    prereqNodeIds: ["l7-ros-robot-project"],
    minimum: ["URDF robot in Gazebo with lidar/camera/IMU", "Reactive obstacle-avoidance node", "One-command launch; bag + trajectory plot"],
    stretch: ["Panic-stop behavior; parameterized speed profiles"],
    metrics: ["Clean-checkout reproducibility", "Collision-free roam duration"],
    failureModes: ["Works-on-my-sourced-shell launch files"],
    researchConnection: "Infrastructure literacy for every lab codebase you'll enter.",
    artifact: "Package + demo video + node-graph README.",
  },
  {
    id: "p12-arm-planning", num: 12, title: "Arm + Planning Integration", levelWindow: [9, 9], hours: 6,
    purpose: "Your RRT meets your arm: collision-aware motion in joint space.",
    prereqNodeIds: ["l9-sampling-planning"],
    minimum: ["Joint-space RRT around a shelf obstacle (MuJoCo collision checks)", "Shortcut + time-parameterize + execute", "50-seed benchmark table"],
    stretch: ["Trajopt smoothing pass; narrow-passage stress test"],
    metrics: ["Success rate, path length pre/post, plan time"],
    failureModes: ["Validating only the end pose, not the swept path"],
    researchConnection: "The classical baseline that learned policies get compared against.",
    artifact: "plan.py + benchmark table.",
  },
  {
    id: "p13-object-localization", num: 13, title: "Language → 3D Object Localization", levelWindow: [8, 8], hours: 4,
    purpose: "Speak a name, get a graspable pose: the perception half of every 'pick up the X'.",
    prereqNodeIds: ["l8-perception-project"],
    minimum: ["SAM3 → depth → cluster → pose pipeline in robot frame", "20-scene eval: success + error stats", "Failure appendix"],
    stretch: ["Duplicate/absent-object handling; monocular (DA3) variant"],
    metrics: ["≥85% localization success; cm/deg errors"],
    failureModes: ["Eval scenes that match the demo scene (self-deception)"],
    researchConnection: "Grounding: where language meets geometry.",
    artifact: "Pipeline repo + eval table.",
  },
  {
    id: "p14-slam-nav", num: 14, title: "Map & Navigate (Nav2)", levelWindow: [9, 9], hours: 4,
    purpose: "The mobile-autonomy loop with production tools, mapped to your from-scratch versions.",
    prereqNodeIds: ["l9-nav-moveit"],
    minimum: ["slam_toolbox map of your Gazebo world", "AMCL + Nav2 to clicked goals", "Goals from a Python node"],
    stretch: ["Costmap parameter study; dynamic-obstacle run"],
    metrics: ["Goal-reach reliability over 20 goals"],
    failureModes: ["Treating Nav2 params as magic (annotate 10 of them instead)"],
    researchConnection: "Your A*/filters ↔ their servers correspondence table.",
    artifact: "Map + launch + correspondence table.",
  },
  {
    id: "p15-mobile-manipulator", num: 15, title: "Tabletop Butler (Autonomy Capstone)", levelWindow: [9, 9], hours: 10,
    purpose: "The classical-stack capstone: perceive → plan → grasp → recover, end to end.",
    prereqNodeIds: ["l9-manipulation-pipeline", "l9-grasping", "l8-perception-project"],
    minimum: ["'Clean up': 3 randomized objects sorted into bins by language prompt", "≥80% completion over 10 episodes", "One induced-failure recovery (re-detect, re-grasp)"],
    stretch: ["Mobile base variant (only if ahead of schedule; pre-agreed de-scope lever)"],
    metrics: ["Completion rate, per-stage failure attribution"],
    failureModes: ["Scripted-pose brittleness hidden by easy randomization ranges"],
    researchConnection: "The baseline system VLAs claim to replace. Know its real ceiling.",
    artifact: "Video + eval table + architecture diagram (Boss evidence).",
  },
  {
    id: "p16-rl-manipulation", num: 16, title: "RL Manipulation (Your PPO at Scale)", levelWindow: [10, 10], hours: 8,
    purpose: "Your from-scratch PPO ported to 2048 parallel envs; a locomotion policy trained in minutes.",
    prereqNodeIds: ["l10-parallel-rl"],
    minimum: ["Your PPO solves ManiSkill3 PushCube-state in parallel", "Playground Go1 walking policy trained + inspected DR/reward configs", "num_envs scaling study"],
    stretch: ["PickCube RGB; reward-shaping ablation"],
    metrics: ["Time-to-solve vs documented references", "Scaling curve"],
    failureModes: ["Auto-reset boundary bugs silently corrupting GAE"],
    researchConnection: "The training-at-scale substrate of modern robot learning.",
    artifact: "Port diff + scaling plots + trained policies.",
  },
  {
    id: "p17-bc-task", num: 17, title: "Behavior Cloning Baseline", levelWindow: [11, 11], hours: 4,
    purpose: "The honest baseline: BC done properly, its failure measured, before fancier policies.",
    prereqNodeIds: ["l11-bc-dagger"],
    minimum: ["CS285 HW1 artifacts: BC gap vs expert + DAgger recovery curve", "Demo-count scaling study"],
    stretch: ["GMM head variant on multimodal data"],
    metrics: ["% of expert performance vs demos; DAgger iterations to close"],
    failureModes: ["Judging BC on in-distribution states only"],
    researchConnection: "Arm 1 of the Boss comparison; the covariate-shift story in data.",
    artifact: "HW1 repo + plots.",
  },
  {
    id: "p18-policy-comparison", num: 18, title: "The PushT Study (ACT vs Diffusion vs BC)", levelWindow: [11, 11], hours: 10,
    purpose: "The Robot Learning Boss: a controlled policy-class comparison with review-grade statistics.",
    prereqNodeIds: ["l11-diffusion-policy", "l11-act", "l11-eval-statistics"],
    minimum: ["3 policy classes, identical data/obs", "3 seeds × 50 episodes, Wilson CIs", "Chunk-size ablation + perturbed-initial-state shift probe"],
    stretch: ["Flow-matching 4th arm; pixel-obs repeat"],
    metrics: ["Success rates with CIs; robustness deltas"],
    failureModes: ["Underpowered comparisons (the CI table forbids them)"],
    researchConnection: "Your first defensible empirical claim: the method IS the result.",
    artifact: "2-page report with money plots (Boss evidence).",
  },
  {
    id: "p19-vla-reproduction", num: 19, title: "VLA Fine-Tune & Evaluation (Capstone)", levelWindow: [12, 12], hours: 12,
    purpose: "The VLA Boss: fine-tune the frontier lineage, evaluate like a 2026 researcher.",
    prereqNodeIds: ["l12-smolvla-finetune", "l12-vla-eval"],
    minimum: ["π0-LoRA (24 GB) or SmolVLA(+cloud π0.5-PEFT) fine-tune", "400-episode LIBERO protocol + your perturbation suite", "One paper-claimed number reproduced within tolerance"],
    stretch: ["Second embodiment/dataset; action-representation swap study"],
    metrics: ["Success + CIs; robustness collapse curve; deviation log completeness"],
    failureModes: ["Eval variance mistaken for improvement; silent config drift"],
    researchConnection: "The reproduction-grade report that anchors your portfolio.",
    artifact: "Report + reusable eval scripts (Boss evidence).",
    computeNote: "Documented: π0-LoRA >22.5 GB; SmolVLA path 16 GB; cloud fallback ≈$10–30.",
  },
  {
    id: "p20-world-model", num: 20, title: "World-Model Experiment (DINO-WM class)", levelWindow: [13, 13], hours: 8,
    purpose: "Train a world model, use it to plan, measure where it hallucinates.",
    prereqNodeIds: ["l13-wm-experiment"],
    minimum: ["DINO-WM planning reproduced; dynamics head retrained on your transitions", "Data-hunger curve (100→10k transitions)", "Hallucination failure gallery"],
    stretch: ["Your own latent-dynamics MLP + CEM planner from scratch"],
    metrics: ["Planning success yours-vs-reference; curve shape"],
    failureModes: ["Evaluating the model (loss) instead of the planner (success)"],
    researchConnection: "First-hand evidence in the latent-vs-generative debate.",
    artifact: "Repo + curve + gallery (level gate).",
  },
  {
    id: "p21-reproduction", num: 21, title: "The Rigorous Reproduction", levelWindow: [15, 15], hours: 10,
    purpose: "Month 6 centerpiece: one claim reproduced with pre-registered tolerance and a public-grade report.",
    prereqNodeIds: ["l15-reproduction-project"],
    minimum: ["One menu item (OFT-head claim at Smol scale / flow-steps tradeoff / DINO-WM / LIBERO-Plus collapse)", "Pre-registered plan; deviation log; CIs", "Plus one eval-level checkpoint check"],
    stretch: ["An author-contactable question list; a second seed-farm pass"],
    metrics: ["Claim vs result table; protocol completeness"],
    failureModes: ["Moving the tolerance after seeing results"],
    researchConnection: "The strongest pre-research portfolio artifact, and the habit RECAP-era labs live by.",
    artifact: "Reproduction report + repo.",
  },
  {
    id: "p22-original-research", num: 22, title: "Original Research Experiment", levelWindow: [16, 16], hours: 100,
    purpose: "The destination: one narrow question, one falsifiable hypothesis, rigorous evidence, shipped.",
    prereqNodeIds: ["l16-proposal"],
    minimum: ["Baseline reproduced; ≥15 logged experiments; one contribution-isolating ablation", "6–8 page report + reproducible repo (clean-machine test)", "Recorded 5-min talk + defense"],
    stretch: ["Workshop submission; public release thread"],
    metrics: ["Evidence table honesty; reproducibility test pass"],
    failureModes: ["Scope creep past Day 190; claims outrunning evidence"],
    researchConnection: "This IS the research.",
    artifact: "Report + repo + talk + next-experiments memo (Final Boss evidence).",
  },
];

export const projectById = (id: string) => PROJECTS.find((p) => p.id === id);
