import type { Resource } from "@/lib/types";

const V = "2026-08-21"; // research-phase verification date

export const RESOURCES: Resource[] = [
  // ── L0 · survival ────────────────────────────────────────────────
  {
    id: "missing-semester",
    title: "The Missing Semester of Your CS Education (2026 edition)",
    authors: "MIT CSAIL PhD students",
    institution: "MIT",
    year: 2026,
    type: "course",
    url: "https://missing.csail.mit.edu/",
    cost: "free",
    difficulty: 1,
    study: "2026: L1 Shell · L2 Command-line Environment (incl. SSH) · L3 Dev Environment & Tools · L5 Version Control & Git · L4 Debugging (first half). From the 2020 edition: L2 Shell Tools & Scripting.",
    skim: "2026 L6 Packaging, L9 Code Quality; 2020 L4 Data Wrangling",
    skipParts: "2026 L7 Agentic Coding, L8; 2020 L8–L10",
    hours: 14,
    role: "primary",
    why: "The only resource covering shell+git+ssh+debugging+editors in one place, written for people who think well; exercises are real tasks.",
    unlocks: "Living in a terminal; clone/commit/branch/push; ssh into a GPU box.",
    lastVerified: V,
  },
  {
    id: "learn-git-branching",
    title: "Learn Git Branching (interactive)",
    authors: "Peter Cottle",
    type: "interactive",
    url: "https://learngitbranching.js.org/",
    cost: "free",
    difficulty: 1,
    study: "Main + Remote intro sequences",
    hours: 3,
    role: "backup",
    why: "Visual mental model of commits/branches/rebase that text can't give.",
    lastVerified: V,
  },
  // ── L1 · python ──────────────────────────────────────────────────
  {
    id: "think-python",
    title: "Think Python, 3rd edition",
    authors: "Allen Downey",
    year: 2024,
    type: "book",
    url: "https://allendowney.github.io/ThinkPython/",
    cost: "free",
    difficulty: 1,
    study: "Ch 1–3 and everything through strings, lists, dictionaries, tuples, files (~ch 1–13)",
    skim: "OOP block near the end (return to it right before PyTorch)",
    skipParts: "Turtle-graphics detours",
    hours: 30,
    role: "primary",
    why: "Runs natively in Jupyter (zero-cost transfer to scientific Python), concise, concept-first, respects an intelligent adult.",
    unlocks: "Writing/debugging 100-line programs, ready for NumPy.",
    lastVerified: V,
  },
  {
    id: "cs50p",
    title: "CS50's Introduction to Programming with Python",
    authors: "David Malan",
    institution: "Harvard",
    type: "course",
    url: "https://cs50.harvard.edu/python/",
    cost: "free",
    difficulty: 1,
    study: "Week 5 (Unit Tests / pytest); do this week regardless of main track",
    skim: "Weeks 0–7 if you want graded structure instead of Think Python",
    hours: 6,
    role: "backup",
    why: "Its testing week is the best beginner pytest intro anywhere; the rest is a solid but slower alternative path.",
    lastVerified: V,
  },
  {
    id: "exercism",
    title: "Exercism: Python track",
    authors: "Exercism community",
    type: "interactive",
    url: "https://exercism.org/tracks/python",
    cost: "free",
    difficulty: 2,
    study: "~25–35 exercises interleaved with reading (concept exercises + easy practice)",
    hours: 12,
    role: "primary",
    why: "Test-driven from the first exercise, which habituates the pytest workflow; beats interview-skewed alternatives.",
    lastVerified: V,
  },
  {
    id: "atbs",
    title: "Automate the Boring Stuff with Python, 3rd ed.",
    authors: "Al Sweigart",
    year: 2025,
    type: "book",
    url: "https://automatetheboringstuff.com/",
    cost: "free",
    difficulty: 1,
    skim: "Part I ch 1–8 as an alternate drill track",
    skipParts: "Never read Part II linearly; it is a lookup shelf (regex, files, CSV/JSON)",
    role: "reference",
    lastVerified: V,
  },
  {
    id: "numpy-docs",
    title: "NumPy official guides (absolute basics + quickstart + user guide)",
    authors: "NumPy developers",
    type: "docs",
    url: "https://numpy.org/doc/stable/user/absolute_beginners.html",
    cost: "free",
    difficulty: 2,
    study: "Absolute basics; quickstart; then Broadcasting, Indexing on ndarrays, Copies & views (the three that prevent 90% of bugs)",
    skipParts: "Structured arrays, ufunc internals, C-API",
    hours: 6,
    role: "primary",
    why: "First-party and current; everything else paraphrases these.",
    unlocks: "Array thinking, the literal mental model of PyTorch tensors.",
    lastVerified: V,
  },
  {
    id: "matplotlib-docs",
    title: "Matplotlib quick start + pyplot tutorial",
    authors: "Matplotlib developers",
    type: "docs",
    url: "https://matplotlib.org/stable/users/explain/quick_start.html",
    cost: "free",
    difficulty: 1,
    study: "Quick start + pyplot tutorial, using the object-oriented (fig, ax) style",
    skipParts: "Animations, artists, backends",
    hours: 3,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "scipy-lectures",
    title: "Scientific Python Lectures",
    authors: "community (Varoquaux et al.)",
    type: "course",
    url: "https://lectures.scientific-python.org/",
    cost: "free",
    difficulty: 2,
    skim: "NumPy and Matplotlib chapters as an alternative track",
    hours: 7,
    role: "backup",
    lastVerified: V,
  },
  {
    id: "py2numpy",
    title: "From Python to NumPy",
    authors: "Nicolas P. Rougier",
    year: 2017,
    type: "book",
    url: "https://www.labri.fr/perso/nrougier/from-python-to-numpy/",
    cost: "free",
    difficulty: 3,
    skim: "Worked case studies after ~2 weeks of NumPy use",
    hours: 6,
    role: "reference",
    why: "Vectorization craft: direct training for tensorized PyTorch code.",
    lastVerified: V,
  },
  // ── L2 · math ────────────────────────────────────────────────────
  {
    id: "khan-math",
    title: "Khan Academy (Algebra 1 → Algebra 2 → Precalculus): test-out loop",
    authors: "Khan Academy",
    type: "course",
    url: "https://www.khanacademy.org/math/algebra2",
    cost: "free",
    difficulty: 1,
    study: "Lead with Course Challenges; patch only weak units. Alg 2 core: rational exponents/radicals, logarithms, transformations of functions, equations, trigonometry. Precalc: composite functions + trig functions.",
    skim: "Polynomial units (unit tests only), exponential models",
    skipParts: "Complex numbers, conic sections, sequences/statistics units, modeling",
    hours: 50,
    role: "primary",
    why: "The only free resource with adaptive diagnostics + infinite generated practice, exactly what repair (vs first learning) needs. Exercises-first; videos only on failure.",
    lastVerified: V,
  },
  {
    id: "pauls-notes",
    title: "Paul's Online Math Notes (Algebra · Calc I · Calc III)",
    authors: "Paul Dawkins",
    institution: "Lamar University",
    type: "notes",
    url: "https://tutorial.math.lamar.edu/",
    cost: "free",
    difficulty: 2,
    study: "Calc I: limits (intuitive), all derivative rules (chain rule until automatic), min/max, antiderivatives, u-substitution, FTC. Calc III: partials, multivariable chain rule, directional derivatives, gradient, Lagrange multipliers.",
    skim: "Related rates, L'Hôpital",
    skipParts: "Trig-substitution/partial-fraction integration, volumes, series machinery, multiple/line/surface integrals",
    hours: 27,
    role: "primary",
    why: "Terse adult-toned prose with fully-solved practice problems, the fastest working-skill track.",
    lastVerified: V,
  },
  {
    id: "3b1b-calculus",
    title: "3Blue1Brown: Essence of Calculus",
    authors: "Grant Sanderson",
    type: "video",
    url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr",
    cost: "free",
    difficulty: 1,
    study: "All 12 chapters, especially ch 2–4 (the visual chain rule = the backprop primitive), 7–9, 11",
    hours: 5,
    role: "primary",
    why: "Fastest possible construction of correct geometric intuition; makes every later mechanical resource 2× faster.",
    lastVerified: V,
  },
  {
    id: "3b1b-linalg",
    title: "3Blue1Brown: Essence of Linear Algebra",
    authors: "Grant Sanderson",
    type: "video",
    url: "https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab",
    cost: "free",
    difficulty: 1,
    study: "All 16 chapters BEFORE any computational resource",
    skim: "Ch 10–12 (cross products, Cramer)",
    hours: 4,
    role: "primary",
    why: "Highest ROI-per-minute video series in mathematics.",
    lastVerified: V,
  },
  {
    id: "vmls",
    title: "Introduction to Applied Linear Algebra (VMLS) + Python companion",
    authors: "Stephen Boyd, Lieven Vandenberghe",
    institution: "Stanford/UCLA",
    year: 2018,
    type: "book",
    url: "https://vmls-book.stanford.edu/",
    cost: "free",
    difficulty: 2,
    study: "Ch 1–3, 5 (vectors, norms, independence/basis/Gram–Schmidt); 6–8, 10–11 (matrices, systems, matmul, inverses/QR); 12–13 (least squares + data fitting, your first real ML model). Implement every concept in NumPy via the Python companion.",
    skim: "Ch 4 (k-means), 14",
    skipParts: "Ch 9, 15–19",
    hours: 24,
    role: "primary",
    why: "Gentle-rigorous, proof-light, built for compute-first learners; the exact vocabulary applied ML uses. (Deliberate gap: no eigen/SVD, closed by MML ch 4.)",
    lastVerified: V,
  },
  {
    id: "mml-book",
    title: "Mathematics for Machine Learning",
    authors: "Deisenroth, Faisal, Ong",
    year: 2020,
    type: "book",
    url: "https://mml-book.github.io/",
    cost: "free",
    difficulty: 3,
    study: "Ch 4 (eigen/SVD) · §5.1–5.7 (vector calculus: the best compact treatment of exactly the multivariable calc ML uses) · §7.1–7.2 (GD, constrained/Lagrange) · §6.5–6.6 (Gaussians)",
    skim: "Ch 2–3 after VMLS; Part II as preview",
    hours: 18,
    role: "primary",
    why: "Consolidation + notation-standardizing pass, not a first-exposure spine.",
    lastVerified: V,
  },
  {
    id: "mit-1806",
    title: "MIT 18.06 Linear Algebra (Strang): eigen/SVD lectures + RES.18-010",
    authors: "Gilbert Strang",
    institution: "MIT OCW",
    type: "course",
    url: "https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/",
    cost: "free",
    difficulty: 3,
    study: "Eigen lectures (L21–22, L25, L29) only; or the 6-video 'A 2020 Vision of Linear Algebra' as a 2 h capstone",
    skipParts: "Do NOT run all 35 lectures on this timeline",
    hours: 4,
    role: "backup",
    lastVerified: V,
  },
  {
    id: "mit-1805",
    title: "MIT 18.05 Introduction to Probability and Statistics (S22)",
    authors: "Jeremy Orloff, Jennifer French Kamrin",
    institution: "MIT OCW",
    year: 2022,
    type: "course",
    url: "https://ocw.mit.edu/courses/18-05-introduction-to-probability-and-statistics-spring-2022/",
    cost: "free",
    difficulty: 2,
    study: "Probability reading: counting; conditional probability & Bayes; discrete/continuous RVs; expectation/variance; common distributions; joints & covariance; LLN + CLT. Statistics reading: MLE; Bayesian updating. Do psets in NumPy.",
    skim: "NHST, confidence intervals",
    skipParts: "R-specific work, regression classes, bootstrap",
    hours: 30,
    role: "primary",
    why: "The only free resource at exactly working-engineer depth with self-contained notes AND solved psets; simulation-friendly.",
    lastVerified: V,
  },
  {
    id: "stat110",
    title: "Harvard Stat 110 + Introduction to Probability 2e",
    authors: "Joe Blitzstein, Jessica Hwang",
    institution: "Harvard",
    type: "course",
    url: "https://stat110.hsites.harvard.edu/",
    cost: "free",
    difficulty: 3,
    study: "Book ch 1–5, 7, 10 if 18.05 feels thin",
    skipParts: "Ch 8, 11–13 (Markov chains/MCMC: later)",
    hours: 12,
    role: "backup",
    why: "The best problems in any probability book; deeper but slower.",
    lastVerified: V,
  },
  {
    id: "seeing-theory",
    title: "Seeing Theory",
    authors: "Daniel Kunin et al.",
    institution: "Brown",
    type: "interactive",
    url: "https://seeing-theory.brown.edu/",
    cost: "free",
    difficulty: 1,
    study: "2–3 h of play alongside week 1 of probability",
    hours: 2,
    role: "reference",
    lastVerified: V,
  },
  {
    id: "khan-multivariable",
    title: "Khan Academy: Multivariable Calculus (Jacobian + Lagrange units)",
    authors: "Grant Sanderson (author), Khan Academy",
    type: "course",
    url: "https://www.khanacademy.org/math/multivariable-calculus",
    cost: "free",
    difficulty: 2,
    study: "'Derivatives of multivariable functions' (gradient + Jacobian) and 'Applications of multivariable derivatives' (Lagrange multipliers articles)",
    hours: 8,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "d2l",
    title: "Dive into Deep Learning (d2l.ai): optimization chapter + reference",
    authors: "Zhang, Lipton, Li, Smola",
    type: "book",
    url: "https://www.d2l.ai/chapter_optimization/",
    cost: "free",
    difficulty: 2,
    study: "Ch 12.1–12.6: optimization & DL, convexity, GD, SGD, minibatch, momentum",
    skim: "Adam section now; attention chapters 9–11 as backup explanations later",
    hours: 8,
    role: "primary",
    why: "Implementation-first: you plot loss landscapes and code GD yourself.",
    lastVerified: V,
  },
  // ── L3/L4 · ML/DL ────────────────────────────────────────────────
  {
    id: "cs229-notes",
    title: "CS229 Machine Learning: official lecture notes (Aug 2026 revision)",
    authors: "Andrew Ng, Tengyu Ma",
    institution: "Stanford",
    year: 2026,
    type: "notes",
    url: "https://cs229.stanford.edu/main_notes.pdf",
    cost: "free",
    difficulty: 3,
    study: "Part I (linear regression/LMS), Part II (classification, logistic regression, GLM/MLE), bias–variance + regularization chapters",
    skipParts: "SVM/kernels, GDA depth, learning-theory proofs, EM",
    hours: 9,
    role: "primary",
    why: "Same author as the famous course, 5× faster for someone who reads math.",
    lastVerified: V,
  },
  {
    id: "statquest",
    title: "StatQuest: core ML playlist",
    authors: "Josh Starmer",
    type: "video",
    url: "https://statquest.org/",
    cost: "free",
    difficulty: 1,
    study: "~15 videos at 1.5×: linear/logistic regression, MLE, gradient descent, bias–variance, ridge/lasso, cross-validation, ROC/AUC",
    skipParts: "Trees/boosting/SVM series",
    hours: 4,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "islp",
    title: "An Introduction to Statistical Learning (Python edition)",
    authors: "James, Witten, Hastie, Tibshirani, Taylor",
    type: "book",
    url: "https://www.statlearning.com/",
    cost: "free",
    difficulty: 2,
    role: "reference",
    why: "Reading reference for classic ML; too slow to work through on this timeline.",
    lastVerified: V,
  },
  {
    id: "pytorch-tutorials",
    title: "PyTorch: Learn the Basics (official, PyTorch 2.13)",
    authors: "PyTorch team",
    type: "docs",
    url: "https://docs.pytorch.org/tutorials/beginner/basics/intro.html",
    cost: "free",
    difficulty: 2,
    study: "All 8 in order (Quickstart → Tensors → Data → Transforms → Build NN → Autograd → Optimization → Save/Load), typing everything",
    hours: 6,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "karpathy-z2h",
    title: "Neural Networks: Zero to Hero",
    authors: "Andrej Karpathy",
    type: "video",
    url: "https://karpathy.ai/zero-to-hero.html",
    cost: "free",
    difficulty: 3,
    study: "v1 micrograd · v2–5 makemore (v4 activations/BatchNorm and v5 backprop-ninja with exercises) · v7 GPT from scratch (twice)",
    skim: "v6 WaveNet; v8 tokenizer once; v9 GPT-2 reproduction (recommended stretch)",
    hours: 32,
    role: "primary",
    why: "Nothing else makes you hand-compute gradients through a real architecture and then scale the same code to a real GPT-2 run.",
    unlocks: "Everything downstream: backprop is never magic again.",
    lastVerified: V,
  },
  {
    id: "microgpt",
    title: "microgpt: GPT in ~200 dependency-free lines",
    authors: "Andrej Karpathy",
    year: 2026,
    type: "notes",
    url: "https://karpathy.github.io/2026/02/12/microgpt/",
    cost: "free",
    difficulty: 4,
    study: "The DL-stage exit exam: read it cold and re-derive every line (tokenizer, autograd, attention, Adam)",
    hours: 5,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "3b1b-nn",
    title: "3Blue1Brown: Neural networks series (ch 5–7: GPT/attention/MLPs)",
    authors: "Grant Sanderson",
    type: "video",
    url: "https://www.3blue1brown.com/lessons/attention",
    cost: "free",
    difficulty: 2,
    study: "Ch 5 Transformers/GPT · ch 6 Attention · ch 7 How LLMs store facts. Watch ch 6 before Karpathy v7, rewatch after.",
    hours: 2,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "cs231n",
    title: "CS231n: Deep Learning for Computer Vision (Spring 2025 videos)",
    authors: "Fei-Fei Li et al.",
    institution: "Stanford",
    year: 2025,
    type: "course",
    url: "https://cs231n.stanford.edu/",
    cost: "free",
    difficulty: 3,
    study: "Selected lectures incl. L6 CNN architectures, L8 Attention & Transformers, L16 Vision & Language, L17 Robot Learning · Assignment A1 fast + CNN/Transformer parts of A2/A3 (the best shape-tracing forcing function in existence)",
    skim: "L13–15 (generative, 3D)",
    hours: 22,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "uva-notebooks",
    title: "UvA Deep Learning notebooks (T6 Transformers · T15 ViT)",
    authors: "Phillip Lippe",
    institution: "University of Amsterdam",
    type: "docs",
    url: "https://uvadlc-notebooks.readthedocs.io/en/latest/",
    cost: "free",
    difficulty: 3,
    study: "Tutorial 6 (Transformers & Multi-Head Attention) after Karpathy v7; Tutorial 15 (Vision Transformers)",
    hours: 6,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "annotated-transformer",
    title: "The Annotated Transformer (2022 rewrite)",
    authors: "Harvard NLP (Rush et al.)",
    type: "docs",
    url: "http://nlp.seas.harvard.edu/annotated-transformer/",
    cost: "free",
    difficulty: 3,
    skim: "Once, for the encoder-decoder completion of the decoder-only picture",
    hours: 3,
    role: "backup",
    lastVerified: V,
  },
  {
    id: "labml",
    title: "labml.ai annotated paper implementations (RoPE, ViT, DDPM, LoRA…)",
    authors: "labml.ai",
    type: "repo",
    url: "https://nn.labml.ai/",
    cost: "free",
    difficulty: 3,
    role: "reference",
    why: "The 'how do I write X cleanly' side-by-side paper/code lookup.",
    lastVerified: V,
  },
  {
    id: "vit-pytorch",
    title: "lucidrains/vit-pytorch",
    authors: "Phil Wang",
    type: "repo",
    url: "https://github.com/lucidrains/vit-pytorch",
    cost: "free",
    difficulty: 3,
    study: "Read vit.py (~150 lines) line-by-line, then train it on CIFAR-10",
    hours: 4,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "open-clip",
    title: "OpenCLIP (mlfoundations)",
    authors: "ML Foundations community",
    type: "repo",
    url: "https://github.com/mlfoundations/open_clip",
    cost: "free",
    difficulty: 3,
    study: "Zero-shot inference + a linear probe on frozen features",
    hours: 3,
    role: "primary",
    why: "The standard open CLIP/SigLIP stack; frozen-feature workflow is exactly what VLA backbones do.",
    lastVerified: V,
  },
  {
    id: "wandb",
    title: "Weights & Biases (free tier)",
    authors: "W&B (CoreWeave)",
    type: "tool",
    url: "https://wandb.ai/",
    cost: "freemium",
    difficulty: 1,
    study: "watch/sweeps/histograms on your training loops (+ log to local CSV as hedge)",
    hours: 1,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "udl-book",
    title: "Understanding Deep Learning",
    authors: "Simon J.D. Prince",
    year: 2023,
    type: "book",
    url: "https://udlbook.github.io/udlbook/",
    cost: "free",
    difficulty: 3,
    role: "reference",
    why: "Best figures in the field; transformers ch 12; dip in when a concept resists.",
    lastVerified: V,
  },
  // ── L5–L9 · robotics ─────────────────────────────────────────────
  {
    id: "eater-quaternions",
    title: "Visualizing Quaternions (interactive video series)",
    authors: "Grant Sanderson, Ben Eater",
    type: "interactive",
    url: "https://eater.net/quaternions",
    cost: "free",
    difficulty: 2,
    study: "All parts + the interactive drills; you drag the rotations yourself",
    hours: 3,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "sola-lie",
    title: "A micro Lie theory for state estimation in robotics",
    authors: "Joan Solà, Jérémie Deray, Dinesh Atchuthan",
    year: 2021,
    type: "paper",
    url: "https://arxiv.org/abs/1812.01537",
    cost: "free",
    difficulty: 4,
    study: "§I–IV + SO(3)/SE(3) example boxes + Jacobian appendix tables; watch the author's ~1 h lecture BEFORE reading (youtube.com/watch?v=QR1p0Rabuww); implement exp/log/⊞/⊟ in NumPy",
    skim: "§V derivative zoo; proofs",
    hours: 7,
    role: "primary",
    why: "Replaces a semester of abstract Lie theory; the exact formalism of modern estimation/learning papers; its tables are a permanent reference.",
    lastVerified: V,
  },
  {
    id: "modern-robotics",
    title: "Modern Robotics: Mechanics, Planning, and Control",
    authors: "Kevin Lynch, Frank Park",
    institution: "Northwestern/SNU",
    year: 2019,
    type: "book",
    url: "https://hades.mech.northwestern.edu/index.php/Modern_Robotics",
    cost: "free",
    difficulty: 4,
    study: "Ch 3 Rigid-Body Motions (the heart) · Ch 4 FK (PoE) · Ch 5 Velocity Kinematics & Jacobians · Ch 6 IK (numerical) · Ch 8.1–8.3, 8.5 dynamics-lite · Ch 9.1–9.4 trajectories · Ch 11.1–11.4 control, while building your own library alongside, checked against the MR pip package",
    skim: "Ch 2 (C-space vocabulary, ~2 h); Ch 12 §12.1 grasping vocabulary",
    skipParts: "Ch 7 closed chains, Ch 10 planning (superseded), Ch 13 wheeled robots, Appendix C DH (read a table once)",
    hours: 55,
    role: "primary",
    why: "The only top-tier text that is free (PDF+videos+MOOC+reference code) AND screw-theory/PoE-first, the convention of Drake, Pinocchio and modern learning-robotics code.",
    lastVerified: V,
  },
  {
    id: "rtb-python",
    title: "Robotics Toolbox for Python (+ spatialmath)",
    authors: "Peter Corke et al.",
    type: "repo",
    url: "https://github.com/petercorke/robotics-toolbox-python",
    cost: "free",
    difficulty: 3,
    role: "reference",
    why: "Independent oracle for unit-testing your own FK/IK/Jacobian code.",
    lastVerified: V,
  },
  {
    id: "mujoco",
    title: "MuJoCo 3.12 + Python bindings + viewer",
    authors: "Google DeepMind",
    type: "docs",
    url: "https://mujoco.readthedocs.io/",
    cost: "free",
    difficulty: 3,
    study: "Overview, XML/MJCF reference (as needed), 'Computation' chapter (how contacts/constraints actually work)",
    hours: 8,
    role: "primary",
    why: "The curriculum's primary simulator; MJCF semantics now run GPU-batched inside both Google (Warp/MJX) and NVIDIA (Newton/Isaac Lab 3) stacks.",
    lastVerified: V,
  },
  {
    id: "menagerie",
    title: "MuJoCo Menagerie (curated robot models)",
    authors: "Google DeepMind",
    type: "repo",
    url: "https://github.com/google-deepmind/mujoco_menagerie",
    cost: "free",
    difficulty: 2,
    study: "UR5e (clean 6-DOF) then Franka Panda (7-DOF nullspace); trs_so_arm100 for the SO-101 twin",
    role: "primary",
    lastVerified: V,
  },
  {
    id: "mjctrl",
    title: "kevinzakka/mjctrl: minimal control examples",
    authors: "Kevin Zakka",
    type: "repo",
    url: "https://github.com/kevinzakka/mjctrl",
    cost: "free",
    difficulty: 3,
    role: "reference",
    why: "Single-file differential IK with nullspace + operational-space control, the oracle for your controller implementations.",
    lastVerified: V,
  },
  {
    id: "brian-douglas",
    title: "Brian Douglas: Control System Lectures",
    authors: "Brian Douglas",
    type: "video",
    url: "https://engineeringmedia.com/videos",
    cost: "free",
    difficulty: 2,
    study: "Intro/PID/state-space videos (~5 h at 1.25×)",
    skipParts: "Frequency-domain series (one Bode video for vocabulary, nothing more)",
    hours: 5,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "brunton-bootcamp",
    title: "Steve Brunton: Control Bootcamp",
    authors: "Steve Brunton",
    institution: "University of Washington",
    type: "video",
    url: "https://www.youtube.com/playlist?list=PLMrJAkhIeNNR20Mz-VpzgfQs5zrYi085m",
    cost: "free",
    difficulty: 3,
    study: "State-space, stability, controllability, pole placement, LQR, Kalman/LQG segment, pausing to implement cart-pole LQR in Python/MuJoCo",
    skipParts: "Robust-control (H∞) tail",
    hours: 10,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "underactuated",
    title: "Underactuated Robotics (Tedrake)",
    authors: "Russ Tedrake",
    institution: "MIT",
    year: 2026,
    type: "course",
    url: "https://underactuated.csail.mit.edu/",
    cost: "free",
    difficulty: 4,
    study: "Ch 8 LQR · Ch 10 Trajectory Optimization (+ Ch 7 DP intro for value-function intuition)",
    skim: "Ch 3 canonical test rigs; Ch 17 planning-through-contact intuition",
    skipParts: "Walking, Lyapunov, robust/adaptive chapters",
    hours: 12,
    role: "backup",
    lastVerified: V,
  },
  {
    id: "labbe-kalman",
    title: "Kalman and Bayesian Filters in Python",
    authors: "Roger Labbe",
    type: "book",
    url: "https://github.com/rlabbe/Kalman-and-Bayesian-Filters-in-Python",
    cost: "free",
    difficulty: 3,
    study: "Ch 1–2 (g-h, discrete Bayes), 4–8 (KF design), 11 EKF, 12 particle filters, writing every filter from scratch, FilterPy only as test oracle",
    skim: "Ch 10 UKF (recipe-level)",
    skipParts: "Ch 13–14 smoothing/adaptive",
    hours: 27,
    role: "primary",
    why: "THE implementation-first Bayes-filter text; executable Jupyter book.",
    lastVerified: V,
  },
  {
    id: "tedrake-manipulation",
    title: "Robotic Manipulation: Perception, Planning, and Control (Fall 2025)",
    authors: "Russ Tedrake",
    institution: "MIT",
    year: 2025,
    type: "course",
    url: "https://manipulation.csail.mit.edu/",
    cost: "free",
    difficulty: 4,
    study: "Ch 3 Basic Pick and Place (the single best implementation chapter in robotics education) · Ch 4 Geometric Pose Estimation · Ch 5 Bin Picking · Ch 6 Motion Planning · notebooks/Deepnote exercises",
    skim: "Ch 8 control, Ch 9–10 deep perception",
    skipParts: "Ch 7 mobile manipulation, Ch 11 RL (comes later), Ch 12 tactile",
    hours: 30,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "fpcv",
    title: "First Principles of Computer Vision",
    authors: "Shree Nayar",
    institution: "Columbia",
    type: "video",
    url: "https://fpcv.cs.columbia.edu/",
    cost: "free",
    difficulty: 2,
    study: "Image formation/lenses · camera calibration (intrinsics/extrinsics) · stereo + SfM overview modules only",
    hours: 6,
    role: "primary",
    why: "Clearest short treatment of camera geometry in existence.",
    lastVerified: V,
  },
  {
    id: "opencv",
    title: "OpenCV 5: Python tutorials (calibration + pose)",
    authors: "OpenCV team",
    type: "docs",
    url: "https://docs.opencv.org/",
    cost: "free",
    difficulty: 2,
    study: "Calibration + solvePnP/ArUco labs: calibrate a simulated camera, reproject, estimate a fiducial pose",
    hours: 4,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "open3d",
    title: "Open3D (point clouds, ICP)",
    authors: "Intel ISL",
    type: "docs",
    url: "https://www.open3d.org/",
    cost: "free",
    difficulty: 2,
    study: "RGB-D→cloud, downsample/normals, ICP registration (pairs with Tedrake ch 4)",
    hours: 4,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "sam3",
    title: "SAM 3 / 3.1 (Segment Anything, concept prompts)",
    authors: "Meta AI",
    year: 2025,
    type: "repo",
    url: "https://github.com/facebookresearch/sam3",
    cost: "free",
    difficulty: 2,
    study: "As a TOOL: text/exemplar-prompted segmentation wired into your perception pipeline",
    hours: 3,
    role: "primary",
    why: "The 2026 default. It subsumes most Grounding-DINO + SAM-2 pipelines.",
    lastVerified: V,
  },
  {
    id: "depth-anything3",
    title: "Depth Anything 3",
    authors: "ByteDance Seed",
    year: 2025,
    type: "repo",
    url: "https://github.com/ByteDance-Seed/Depth-Anything-3",
    cost: "free",
    difficulty: 2,
    study: "As a TOOL: monocular depth/geometry in your pipeline",
    hours: 2,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "pythonrobotics",
    title: "PythonRobotics (planning + SLAM reference implementations)",
    authors: "Atsushi Sakai et al.",
    type: "repo",
    url: "https://github.com/AtsushiSakai/PythonRobotics",
    cost: "free",
    difficulty: 3,
    study: "Cross-check your own A*/RRT/RRT* against its implementations; run/read EKF-SLAM + FastSLAM demos",
    hours: 6,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "lavalle",
    title: "Planning Algorithms (LaValle)",
    authors: "Steven LaValle",
    year: 2006,
    type: "book",
    url: "http://lavalle.pl/planning/",
    cost: "free",
    difficulty: 4,
    skim: "Ch 5 (sampling-based) + Ch 6 intro only; never linearly",
    role: "reference",
    lastVerified: V,
  },
  {
    id: "ompl",
    title: "OMPL: Open Motion Planning Library",
    authors: "Kavraki Lab",
    institution: "Rice University",
    type: "docs",
    url: "https://ompl.kavrakilab.org/",
    cost: "free",
    difficulty: 3,
    role: "reference",
    why: "The production planning library (40+ planners). Know it exists; don't study it.",
    lastVerified: V,
  },
  {
    id: "slam-handbook",
    title: "The SLAM Handbook (free draft, Cambridge UP 2026)",
    authors: "Carlone, Kim, Barfoot, Cremers, Dellaert + 60 authors",
    year: 2026,
    type: "book",
    url: "https://github.com/SLAM-Handbook-contributors/slam-handbook-public-release",
    cost: "free",
    difficulty: 4,
    role: "reference",
    why: "The new canonical estimation/SLAM reference. Consult on demand.",
    lastVerified: V,
  },
  {
    id: "stachniss",
    title: "Cyrill Stachniss: SLAM/estimation lectures",
    authors: "Cyrill Stachniss",
    institution: "University of Bonn",
    type: "video",
    url: "https://www.ipb.uni-bonn.de/teaching/",
    cost: "free",
    difficulty: 3,
    study: "'Introduction to SLAM' + graph-SLAM overview only (the 4–6 h bridge)",
    hours: 5,
    role: "backup",
    lastVerified: V,
  },
  {
    id: "ros2-docs",
    title: "ROS 2 Jazzy: official tutorials",
    authors: "Open Robotics / OSRA",
    type: "docs",
    url: "https://docs.ros.org/en/jazzy/Tutorials.html",
    cost: "free",
    difficulty: 3,
    study: "Beginner CLI (9 lessons) · Beginner client libraries (rclpy) · Intermediate: Launch, TF2, URDF, RViz, per the 55 h syllabus",
    skipParts: "DDS/RMW tuning, QoS deep-dives, executors, lifecycle, real-time, security",
    hours: 25,
    role: "primary",
    why: "Canonical and current. Install Jazzy on Ubuntu 24.04 (NOT Lyrical; the CUDA/Isaac ecosystem doesn't support 26.04 yet).",
    lastVerified: V,
  },
  {
    id: "articulated-robotics",
    title: "Articulated Robotics: 'Building a mobile robot' series",
    authors: "Josh Newans",
    type: "video",
    url: "https://articulatedrobotics.xyz/",
    cost: "free",
    difficulty: 2,
    study: "The build-along thread: URDF/Xacro → Gazebo → ros2_control → sensors → Nav2",
    hours: 15,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "moveit2",
    title: "MoveIt 2 tutorials",
    authors: "PickNik / MoveIt community",
    type: "docs",
    url: "https://moveit.picknik.ai/",
    cost: "free",
    difficulty: 3,
    study: "One Panda/UR pick-place tutorial pass + moveit_py motion request",
    hours: 5,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "nav2",
    title: "Nav2 documentation",
    authors: "Open Navigation / ROS community",
    type: "docs",
    url: "https://docs.nav2.org/",
    cost: "free",
    difficulty: 3,
    study: "Bringup + behavior-tree concepts on a sim robot; slam_toolbox → map → AMCL → goals from rclpy",
    hours: 6,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "learncpp",
    title: "learncpp.com (reading-literacy subset)",
    authors: "Alex (learncpp)",
    type: "notes",
    url: "https://www.learncpp.com/",
    cost: "free",
    difficulty: 3,
    study: "Ch ~1–11 + skim classes/templates; then port two official ROS 2 C++ tutorials (pub/sub + service)",
    hours: 20,
    role: "primary",
    why: "A robot-learning researcher needs C++ READING fluency (~20–25 h), not a semester.",
    lastVerified: V,
  },
  // ── L10 · RL ─────────────────────────────────────────────────────
  {
    id: "cs285",
    title: "Berkeley CS 185/285 Deep RL (Spring 2026)",
    authors: "Sergey Levine",
    institution: "UC Berkeley",
    year: 2026,
    type: "course",
    url: "https://rail.eecs.berkeley.edu/deeprlcourse/",
    cost: "free",
    difficulty: 4,
    study: "Lec 2 (imitation), 4–6 (policy gradients/actor-critic), 7–8 (Q-learning), 15–16 (offline RL) + HW1 (BC+DAgger)",
    skipParts: "Everything else on first pass",
    hours: 18,
    role: "primary",
    why: "The only course that treats RL as robot learning, by the field's central figure.",
    lastVerified: V,
  },
  {
    id: "sutton-barto",
    title: "Reinforcement Learning: An Introduction (2nd ed.)",
    authors: "Richard Sutton, Andrew Barto",
    year: 2018,
    type: "book",
    url: "http://incompleteideas.net/book/the-book-2nd.html",
    cost: "free",
    difficulty: 3,
    study: "Ch 1, 3–6 (MDPs, DP, MC, TD)",
    skim: "Ch 9–10, 13",
    skipParts: "Bandits depth, eligibility-trace machinery, Dyna variants, average-reward",
    hours: 12,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "spinningup-essays",
    title: "Spinning Up: essays only",
    authors: "OpenAI (Josh Achiam)",
    type: "docs",
    url: "https://spinningup.openai.com/en/latest/",
    cost: "free",
    difficulty: 2,
    study: "'Key Papers in Deep RL', 'Intro to Policy Optimization', 'Spinning Up as a Deep RL Researcher'",
    skipParts: "THE CODE (TF1-era, pre-Gymnasium); implement from CleanRL instead",
    hours: 4,
    role: "backup",
    lastVerified: V,
  },
  {
    id: "cleanrl",
    title: "CleanRL (single-file benchmarked implementations)",
    authors: "Costa Huang et al.",
    type: "repo",
    url: "https://github.com/vwxyzjn/cleanrl",
    cost: "free",
    difficulty: 3,
    study: "Read ppo.py + sac_continuous_action.py as the implementation textbook; validate your from-scratch versions against its curves",
    hours: 6,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "ppo-37-details",
    title: "The 37 Implementation Details of PPO",
    authors: "Huang et al. (ICLR Blog Track 2022)",
    type: "notes",
    url: "https://iclr-blog-track.github.io/2022/03/25/ppo-implementation-details/",
    cost: "free",
    difficulty: 3,
    study: "Alongside your from-scratch PPO, the document that makes a PPO actually train",
    hours: 3,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "gymnasium",
    title: "Gymnasium 1.3 + MuJoCo envs",
    authors: "Farama Foundation",
    type: "docs",
    url: "https://gymnasium.farama.org/",
    cost: "free",
    difficulty: 2,
    study: "Env API + Hopper/HalfCheetah for your from-scratch PPO/SAC",
    hours: 2,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "mujoco-playground",
    title: "MuJoCo Playground (GPU-parallel RL, Warp backend)",
    authors: "Google DeepMind + Zakka et al.",
    year: 2026,
    type: "repo",
    url: "https://github.com/google-deepmind/mujoco_playground",
    cost: "free",
    difficulty: 3,
    study: "Locomotion Colab (Go1 joystick trains in ~7 min on an RTX 4090) then G1 humanoid; inspect reward + domain-randomization configs",
    hours: 8,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "maniskill",
    title: "ManiSkill3 (GPU-parallel manipulation + vision RL)",
    authors: "UCSD Hao Su Lab",
    year: 2025,
    type: "repo",
    url: "https://github.com/haosulab/ManiSkill",
    cost: "free",
    difficulty: 3,
    study: "PPO baselines: PushCube state (<1 min) → PickCube state (2–5 min) → PickCube RGB (15–45 min); port YOUR PPO to its vectorized API",
    hours: 8,
    role: "primary",
    why: "Fastest GPU-parallel sim+rendering; single-file CleanRL-style baselines, the smoothest bridge from your own PPO to parallel training.",
    lastVerified: V,
  },
  {
    id: "sb3",
    title: "Stable-Baselines3 2.9",
    authors: "DLR-RM (Raffin et al.)",
    type: "repo",
    url: "https://github.com/DLR-RM/stable-baselines3",
    cost: "free",
    difficulty: 2,
    role: "reference",
    why: "Baseline oracle, never the learning vehicle.",
    lastVerified: V,
  },
  {
    id: "corl-iql",
    title: "CORL: single-file offline RL (iql.py)",
    authors: "CORL team (community fork)",
    type: "repo",
    url: "https://github.com/corl-team/CORL",
    cost: "free",
    difficulty: 4,
    study: "Exactly one file: iql.py, expectile value learning + advantage-weighted extraction (the offline-RL algorithm that survived into VLA-land)",
    hours: 5,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "unitree-rl-gym",
    title: "unitree_rl_gym (Train → Play → Sim2Sim → Sim2Real)",
    authors: "Unitree Robotics",
    type: "repo",
    url: "https://github.com/unitreerobotics/unitree_rl_gym",
    cost: "free",
    difficulty: 3,
    study: "The sim2sim step as the no-hardware sim-to-real lab (or replicate the loop with Playground/mjlab policies replayed in vanilla MuJoCo)",
    hours: 5,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "reality-gap-survey",
    title: "The Reality Gap in Robotics (Annual Reviews 2026)",
    authors: "Annual Review of Control, Robotics, and Autonomous Systems",
    year: 2026,
    type: "paper",
    url: "https://www.annualreviews.org/content/journals/10.1146/annurev-control-031924-100130",
    cost: "free",
    difficulty: 3,
    study: "The modern sim-to-real best-practices survey",
    hours: 4,
    role: "primary",
    lastVerified: V,
  },
  // ── L11+ · robot learning / frontier ─────────────────────────────
  {
    id: "lerobot",
    title: "LeRobot v0.6 (the field's workbench)",
    authors: "Hugging Face (Cadene et al.)",
    year: 2026,
    type: "repo",
    url: "https://github.com/huggingface/lerobot",
    cost: "free",
    difficulty: 3,
    study: "Docs: getting started, LeRobotDataset v3, policies (act/diffusion/smolvla/pi05), lerobot-eval + lerobot-rollout (incl. dagger correction mode); official Colabs (training-act, training-smolvla)",
    hours: 10,
    role: "primary",
    why: "26.8k★, ICLR 2026 paper; every major policy family, six benchmark suites, dataset streaming, all in one API.",
    lastVerified: V,
  },
  {
    id: "robot-learning-tutorial",
    title: "Robot Learning: A Tutorial (LeRobot team)",
    authors: "Hugging Face LeRobot team",
    year: 2025,
    type: "notes",
    url: "https://huggingface.co/spaces/lerobot/robot-learning-tutorial",
    cost: "free",
    difficulty: 3,
    study: "The best single modern survey-with-code of the robot-learning stack",
    hours: 6,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "diffusion-policy-repo",
    title: "Diffusion Policy (official repo + Colabs)",
    authors: "Cheng Chi et al. (Columbia/TRI/MIT)",
    year: 2023,
    type: "repo",
    url: "https://github.com/real-stanford/diffusion_policy",
    cost: "free",
    difficulty: 4,
    study: "Official state-based Colab; then implement the DDPM action head from scratch on PushT and check against LeRobot's diffusion policy",
    hours: 8,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "act-repo",
    title: "ACT (original) + gym-aloha sim tasks",
    authors: "Tony Zhao et al. (Stanford)",
    year: 2023,
    type: "repo",
    url: "https://github.com/tonyzhaozh/act",
    cost: "free",
    difficulty: 3,
    study: "Sim TransferCube with scripted demos; the 'ACT tuning tips' doc; then train via LeRobot --policy.type=act",
    hours: 5,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "openpi",
    title: "openpi (π0 / π0-FAST / π0.5 open weights)",
    authors: "Physical Intelligence",
    year: 2026,
    type: "repo",
    url: "https://github.com/Physical-Intelligence/openpi",
    cost: "free",
    difficulty: 5,
    study: "Fine-tune with LoRA on a LeRobot dataset (documented: inference >8 GB; LoRA >22.5 GB, one RTX 4090; full FT >70 GB = cloud)",
    hours: 12,
    role: "primary",
    why: "The frontier lineage you can actually run, the capstone fine-tune path.",
    lastVerified: V,
  },
  {
    id: "openvla-repo",
    title: "OpenVLA (repo as the readable reference implementation)",
    authors: "Kim, Pertsch, Karamcheti et al. (Stanford/Berkeley/TRI)",
    year: 2024,
    type: "repo",
    url: "https://github.com/openvla/openvla",
    cost: "free",
    difficulty: 4,
    study: "Read the codebase end-to-end (tokenization → backbone → action head → training loop). Do NOT fine-tune it (LoRA floor ~27 GB; frozen since Mar 2025); study it.",
    hours: 6,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "isaac-groot",
    title: "NVIDIA Isaac GR00T N1.7",
    authors: "NVIDIA GEAR",
    year: 2026,
    type: "repo",
    url: "https://github.com/NVIDIA/Isaac-GR00T",
    cost: "free",
    difficulty: 4,
    study: "Inference on 16 GB+; architecture read (Cosmos-Reason2 backbone + flow DiT head); fine-tune only via cloud (40 GB+) or LeRobot BS1–2 on 24 GB",
    hours: 5,
    role: "backup",
    lastVerified: V,
  },
  {
    id: "libero",
    title: "LIBERO (via LeRobot env) + LIBERO-Plus robustness suite",
    authors: "Liu et al. (UT Austin) / Fei et al.",
    type: "repo",
    url: "https://github.com/Lifelong-Robot-Learning/LIBERO",
    cost: "free",
    difficulty: 3,
    study: "Use through LeRobot (--env.type=libero; 1.9 GB dataset; 400-episode protocol). Always read scores alongside LIBERO-Plus robustness results; the benchmark is saturated.",
    hours: 4,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "vla-eval-harness",
    title: "Ai2 vla-evaluation-harness",
    authors: "Allen Institute for AI",
    year: 2026,
    type: "repo",
    url: "https://github.com/allenai/vla-evaluation-harness",
    cost: "free",
    difficulty: 3,
    study: "'Any VLA on any sim benchmark': the capstone's evaluation backbone",
    hours: 3,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "awesome-vla-2026",
    title: "awesome-vla-2026 (living index, 250+ papers)",
    authors: "community",
    year: 2026,
    type: "repo",
    url: "https://github.com/miracle-techlink/awesome-vla-2026",
    cost: "free",
    difficulty: 2,
    role: "reference",
    why: "A map for anything beyond the ladder, not a syllabus.",
    lastVerified: V,
  },
  {
    id: "dreamerv3-repo",
    title: "DreamerV3 (official JAX)",
    authors: "Danijar Hafner",
    type: "repo",
    url: "https://github.com/danijar/dreamerv3",
    cost: "free",
    difficulty: 4,
    study: "Run on one control task (single-GPU documented); read the RSSM + imagination training code",
    hours: 6,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "tdmpc2-repo",
    title: "TD-MPC2 (official)",
    authors: "Nicklas Hansen et al.",
    type: "repo",
    url: "https://github.com/nicklashansen/tdmpc2",
    cost: "free",
    difficulty: 4,
    study: "Single-task online RL on walker-walk from pixels (12 GB GPU documented); compare against released reference checkpoints; ablate horizon/CEM samples",
    hours: 8,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "dino-wm",
    title: "DINO-WM (frozen DINOv2 features + latent dynamics + MPC)",
    authors: "Zhou et al. (NYU)",
    year: 2025,
    type: "repo",
    url: "https://github.com/gaoyuezhou/dino_wm",
    cost: "free",
    difficulty: 4,
    study: "Download push-T dataset + checkpoint, run zero-shot MPC planning, then retrain the dynamics head on one GPU",
    hours: 8,
    role: "primary",
    why: "The most reproducible manipulation-planning world model for a solo learner.",
    lastVerified: V,
  },
  {
    id: "vjepa2",
    title: "V-JEPA 2 / 2-AC (+ 2.1)",
    authors: "Meta FAIR",
    year: 2026,
    type: "repo",
    url: "https://github.com/facebookresearch/vjepa2",
    cost: "free",
    difficulty: 4,
    study: "Open checkpoints incl. the action-conditioned robot model; probe frozen features; read the CEM planning loop",
    hours: 4,
    role: "backup",
    lastVerified: V,
  },
  {
    id: "keshav-reading",
    title: "How to Read a Paper (three-pass method)",
    authors: "S. Keshav",
    institution: "University of Waterloo",
    type: "paper",
    url: "https://web.stanford.edu/class/ee384m/Handouts/HowtoReadPaper.pdf",
    cost: "free",
    difficulty: 1,
    study: "The three-pass method; apply it to every ladder paper",
    hours: 1,
    role: "primary",
    lastVerified: V,
  },
  {
    id: "make-it-stick",
    title: "Make It Stick: The Science of Successful Learning",
    authors: "Brown, Roediger, McDaniel",
    year: 2014,
    type: "book",
    url: "https://www.hup.harvard.edu/books/9780674729018",
    cost: "paid",
    difficulty: 1,
    role: "reference",
    why: "Retrieval practice + spacing + interleaving, by the researchers themselves: why this app quizzes you instead of re-showing you (with Dunlosky et al. 2013, PSPI, as the scholarly citation).",
    lastVerified: V,
  },
];

export const resourceById = (id: string) => RESOURCES.find((r) => r.id === id);
