import type { SkillNode } from "@/lib/types";

export const L0_NODES: SkillNode[] = [
  {
    id: "l0-terminal",
    level: 0,
    title: "Terminal & Shell",
    track: "code",
    labs: ["code"],
    why: "Every tool in this program (Python, git, simulators, GPU training) is driven from a shell. This is the substrate for everything else.",
    objectives: [
      "Navigate and manipulate the filesystem (cd, ls, mv, cp, rm, find, grep)",
      "Compose commands with pipes and redirection",
      "Understand PATH, environment variables, exit codes",
      "Read a man page / --help without panic",
    ],
    prereqs: [],
    hours: 5,
    primary: { resourceId: "missing-semester", sections: "2026 L1 (Shell) + 2020 L2 (Shell Tools & Scripting) + exercises" },
    exercises: [
      "Find every .py file under a directory tree containing the word 'import numpy' using find+grep",
      "Write a one-liner that counts lines of code in a project excluding blank lines",
      "Break your PATH on purpose, observe the failure, fix it",
    ],
    masteryGate: "silver",
    masteryTest: "Given a messy directory of 100 mixed files, organize, search, batch-rename and archive them using only the shell, no file manager, no AI.",
    diagnostic: "Explain what `cat data.txt | grep error | wc -l` does and predict its output for a given file; write the find command for '*.log modified in the last day'.",
    misconceptions: ["The terminal is 'the hard way'. It is the fast way once commands become reflexes; GUIs are the detour here."],
  },
  {
    id: "l0-editor",
    level: 0,
    title: "Editor & IDE Basics",
    track: "code",
    labs: ["code"],
    why: "You will spend thousands of hours in an editor; ten setup decisions now repay themselves daily.",
    objectives: [
      "VS Code with Python + Jupyter extensions configured",
      "Keyboard-first editing: multi-cursor, go-to-definition, find-in-project",
      "Integrated terminal + debugger panel familiarity",
    ],
    prereqs: [{ id: "l0-terminal" }],
    hours: 2,
    primary: { resourceId: "missing-semester", sections: "Official VS Code 'Getting Started with Python' tutorial (code.visualstudio.com/docs/python) as the do-along; 2026 L3 only for LSP concepts (curation 2026-08-21: L3 is vim/LSP-focused, no VS Code walkthrough)" },
    exercises: ["Set up format-on-save; step through a 20-line script in the VS Code debugger with a breakpoint and a watch expression"],
    masteryGate: "bronze",
    masteryTest: "Live-edit a multi-file project: rename a symbol across files, jump between definition/usages, run and debug, all without touching the mouse more than twice.",
    diagnostic: "Demonstrate go-to-definition, project-wide search, and setting a breakpoint in under 60 seconds.",
  },
  {
    id: "l0-python-setup",
    level: 0,
    title: "Python Environments & Packaging",
    track: "code",
    labs: ["code"],
    why: "Half of all beginner robotics/ML failures are environment failures. Owning venvs/uv and pip now prevents weeks of pain later (LeRobot, MuJoCo, PyTorch all install this way).",
    objectives: [
      "Create/activate virtual environments; install/uninstall/pin packages",
      "Understand site-packages, interpreter selection, requirements.txt / pyproject basics",
      "Diagnose 'ModuleNotFoundError' and version-conflict errors systematically",
    ],
    prereqs: [{ id: "l0-terminal" }],
    hours: 3,
    primary: { resourceId: "missing-semester", sections: "2026 L6 \u00a71 Dependencies & Environments (venv/pip/uv) + PyPA pip+venv guide do-along; hands-on: create 3 separate envs (curation 2026-08-21: env content moved from L3 to L6 in the 2026 edition)" },
    exercises: [
      "Create two environments with different NumPy versions; prove which one a script uses and why",
      "Intentionally create a broken install, read the error, repair it",
    ],
    masteryGate: "silver",
    masteryTest: "From a fresh shell: create an env, install a pinned dependency set from requirements.txt, run its test suite, and explain where every package lives on disk.",
    diagnostic: "Explain the difference between `python`, `python3`, and the venv's python; show how to verify which interpreter is running.",
  },
  {
    id: "l0-git",
    level: 0,
    title: "Git Fundamentals",
    track: "code",
    labs: ["code"],
    why: "Research is iteration; git is how iteration becomes reversible. Every experiment in this program is a commit.",
    objectives: [
      "The commit graph mental model: working tree → index → commits → branches",
      "add/commit/status/log/diff/branch/checkout/merge fluency",
      "Undo safely: restore, revert, reset (and when each is right)",
    ],
    prereqs: [{ id: "l0-terminal" }],
    hours: 5,
    primary: { resourceId: "missing-semester", sections: "2026 L5 Version Control & Git (the data-model-first notes)" },
    backup: { resourceId: "learn-git-branching", sections: "Main + Remote intro sequences" },
    exercises: [
      "Create a repo, make 5 commits, branch, create a merge conflict on purpose, resolve it",
      "Recover a 'lost' commit using reflog",
    ],
    masteryGate: "gold",
    masteryTest: "Given a repo with a broken merge and an accidentally-deleted branch, restore both to a working state and explain each command's effect on the commit graph, no AI, no cheat sheet.",
    diagnostic: "Draw the commit graph after: commit ×2, branch f, commit on f, checkout main, commit, merge f. Explain what HEAD is at each step.",
    misconceptions: ["Git is not a save button. It is a graph of snapshots; nothing committed is ever lost until garbage-collected."],
  },
  {
    id: "l0-github",
    level: 0,
    title: "GitHub, Remotes & SSH",
    track: "code",
    labs: ["code"],
    why: "Your portfolio, backups, and every open-source robotics repo you'll clone live here. SSH keys unlock remote GPU boxes too.",
    objectives: [
      "clone/push/pull/fetch; origin vs local branches",
      "SSH keypair generation and agent use",
      "Fork → branch → pull-request flow; reading others' repos (README, issues, structure)",
    ],
    prereqs: [{ id: "l0-git" }],
    hours: 3,
    primary: { resourceId: "missing-semester", sections: "2026 L2 SSH segment + L5 remotes; hands-on GitHub flow" },
    exercises: ["Set up SSH auth; publish a repo; open a PR against your own repo from a branch and merge it"],
    masteryGate: "silver",
    masteryTest: "Clone an unfamiliar medium-sized repo, orient yourself (entry points, structure, how to run it) in 20 minutes, and push a small documented change to your fork.",
    diagnostic: "Explain what `git pull` actually does (fetch + merge) and when push is rejected; demonstrate ssh -T authentication.",
  },
  {
    id: "l0-debug-mindset",
    level: 0,
    title: "Debugging Mentality & Stack Traces",
    track: "code",
    labs: ["code"],
    why: "The single highest-leverage research skill: converting 'it broke' into a located, minimal, explained failure. Every level above this one depends on it.",
    objectives: [
      "Read a Python traceback bottom-up; identify the failing frame and the true cause vs symptom",
      "Binary-search a failure (bisect the code, the data, the config)",
      "Form debugging hypotheses and test them one at a time",
      "print/logging/debugger: choose the right probe",
    ],
    prereqs: [{ id: "l0-terminal" }],
    hours: 3,
    primary: { resourceId: "missing-semester", sections: "2020 edition Debugging lecture, first half (print/logging/pdb, Python-first) + deliberate-practice reps below; 2026 L4 only for its AI-for-debugging section (curation 2026-08-21: 2026 L4 is C/systems-heavy)" },
    exercises: [
      "Take 5 pre-broken scripts (typo, wrong type, off-by-one, bad path, silent logic bug) and fix each while narrating hypothesis → test → conclusion",
      "Introduce a bug into working code, hand it to tomorrow-you, fix it cold",
    ],
    masteryGate: "gold",
    masteryTest: "Fix an unseen 100-line broken script in under 30 minutes, keeping a written hypothesis log. The log is graded, not just the fix.",
    diagnostic: "Given a 15-line traceback through 3 library layers, point at the line to read first and say why.",
    misconceptions: ["'The error message is the enemy.' It is the single most informative artifact you have; read all of it, especially the last line."],
  },
  {
    id: "l0-os-mental-model",
    level: 0,
    title: "How the Machine Runs Your Code",
    track: "code",
    labs: ["code"],
    why: "A working model of processes, memory, files and the GPU prevents cargo-cult fixes and explains why environments, paths and CUDA versions behave as they do.",
    objectives: [
      "Processes, PIDs, kill; foreground/background jobs",
      "Memory vs disk; what 'out of memory' actually means (RAM vs VRAM)",
      "What the GPU is: massively parallel arithmetic + its own memory; why ML uses it",
      "Files/permissions; where software lives on Linux",
    ],
    prereqs: [{ id: "l0-terminal" }],
    hours: 3,
    primary: { resourceId: "missing-semester", sections: "scattered across L1/L2 + notes; supplement: htop/nvidia-smi exploration" },
    exercises: ["Run a runaway Python loop, find it with htop, kill it; watch nvidia-smi while a tensor allocation grows"],
    masteryGate: "bronze",
    masteryTest: "Explain to a rubber duck: what happens end-to-end when you type `python train.py` (shell, interpreter, process, memory, GPU handoff).",
    diagnostic: "What is the difference between RAM and VRAM, and which error message tells you each is exhausted?",
  },
  {
    id: "l0-workflow-capstone",
    level: 0,
    title: "Survival Capstone: Clone → Modify → Ship",
    track: "project",
    labs: ["code"],
    why: "Proves the whole survival toolchain works together, the L0 exit condition from the handover.",
    objectives: ["Complete the full loop on a real small project without assistance"],
    prereqs: [{ id: "l0-git" }, { id: "l0-python-setup" }, { id: "l0-editor" }, { id: "l0-debug-mindset" }],
    hours: 2,
    exercises: [
      "Clone a small Python CLI project, create an env, install, run its tests, fix one intentionally-planted bug, add one tiny feature, commit with a clear message, push to your fork",
    ],
    masteryGate: "gold",
    masteryTest: "The loop above, timed under 45 minutes, narrated in a short written log. This unlocks Level 1 project work.",
    diagnostic: "Already done this loop on your own projects? Show the repo and walk through its history.",
  },
];
