import type { SkillNode } from "@/lib/types";

export const L1_NODES: SkillNode[] = [
  {
    id: "l1-python-basics",
    level: 1,
    title: "Python: Values, Types & Expressions",
    track: "code",
    labs: ["code"],
    why: "The first bricks: everything you will ever build, from linear regression to a VLA fine-tune script, is made of these.",
    objectives: [
      "Variables, int/float/str/bool, f-strings, operators, precedence",
      "Type errors read and understood, not feared",
      "REPL + notebook + script workflows",
    ],
    prereqs: [{ id: "l0-python-setup" }],
    hours: 6,
    primary: { resourceId: "think-python", sections: "Ch 1–3 (+ notebook exercises)" },
    backup: { resourceId: "exercism", sections: "First ~8 concept exercises" },
    exercises: [
      "Unit-conversion calculator (degrees↔radians, m/s↔km/h) with formatted output",
      "Predict-then-run: 20 expressions involving int/float division, precedence, string ops",
    ],
    masteryGate: "silver",
    masteryTest: "Write a compound-interest table printer from a verbal spec, first try, no reference.",
    diagnostic: "Predict outputs: `7//2`, `7%2`, `2**3**2`, `'ab'*3`, `int('3.0')` (trap). Explain each.",
  },
  {
    id: "l1-control-flow",
    level: 1,
    title: "Control Flow: Conditionals & Loops",
    track: "code",
    labs: ["code"],
    why: "Computation is repetition with decisions. Loops are also your first taste of algorithmic thinking, and of off-by-one bugs.",
    objectives: [
      "if/elif/else, boolean logic, truthiness",
      "for/while, range, break/continue, nested loops",
      "Loop-accumulator and loop-search patterns",
    ],
    prereqs: [{ id: "l1-python-basics" }],
    hours: 5,
    primary: { resourceId: "think-python", sections: "Conditionals + iteration chapters" },
    backup: { resourceId: "exercism", sections: "Control-flow exercises" },
    exercises: [
      "FizzBuzz variants without looking anything up",
      "Collatz sequence length; prime tester; number-guessing game",
      "Deliberately write three off-by-one bugs, predict each, verify",
    ],
    masteryGate: "gold",
    masteryTest: "Implement 'print a text histogram of dice-roll sums over 10,000 simulated rolls', loops only, no libraries, working first or second run.",
    diagnostic: "Trace by hand what `for i in range(3): for j in range(i): print(i, j)` prints.",
  },
  {
    id: "l1-functions",
    level: 1,
    title: "Functions, Scope & Composition",
    track: "code",
    labs: ["code"],
    why: "Functions are the unit of thought. Decomposing problems into named, testable pieces is the difference between scripts and software, and mirrors how math composes.",
    objectives: [
      "def/return, parameters, defaults, keyword args, *args/**kwargs basics",
      "Local vs global scope; why mutation of arguments surprises people",
      "Pure functions vs side effects; docstrings",
    ],
    prereqs: [{ id: "l1-control-flow" }],
    hours: 5,
    primary: { resourceId: "think-python", sections: "Function chapters (both fruitful + void)" },
    exercises: [
      "Refactor a 60-line script into 6 functions with one clear job each",
      "Write compose(f, g) returning a new function; use it on numeric transforms",
    ],
    masteryGate: "gold",
    masteryTest: "Given a messy 80-line procedural script, produce a clean decomposition with docstrings and no globals, and explain each boundary choice.",
    diagnostic: "What does a function without `return` return? What prints: default arg `def f(x, xs=[])` called twice (the classic trap)?",
    misconceptions: ["Default mutable arguments are evaluated once. The [] trap will bite you in real ML configs."],
  },
  {
    id: "l1-data-structures",
    level: 1,
    title: "Lists, Dicts, Sets, Tuples & Comprehensions",
    track: "code",
    labs: ["code"],
    why: "Datasets are lists of dicts; configs are dicts; trajectories are lists of tuples. Choosing the right structure IS half of programming.",
    objectives: [
      "Indexing/slicing; mutation vs copy; aliasing",
      "dict/set operations and when each wins",
      "List/dict comprehensions as the default idiom",
      "Nested structures (list of dicts of lists) navigated confidently",
    ],
    prereqs: [{ id: "l1-functions" }],
    hours: 6,
    primary: { resourceId: "think-python", sections: "Lists, dictionaries, tuples chapters" },
    backup: { resourceId: "exercism", sections: "Collections exercises (~8)" },
    exercises: [
      "Word-frequency counter → top-10, with and without Counter",
      "Invert a dict; group a list of records by field; flatten nested lists",
      "Demonstrate the aliasing bug: two names, one list. Then fix with copy",
    ],
    masteryGate: "gold",
    masteryTest: "Parse a small CSV-like text into records, filter/aggregate/sort by multiple criteria, comprehensions throughout, clean first-pass code.",
    diagnostic: "Predict: `a=[1,2]; b=a; b.append(3); print(a)`. Then `a[:]` version. Explain the memory model.",
  },
  {
    id: "l1-files-errors",
    level: 1,
    title: "Files, Paths & Exceptions",
    track: "code",
    labs: ["code"],
    why: "Every experiment reads configs and writes results. Exceptions are how robust research code fails loudly instead of lying silently.",
    objectives: [
      "open/with, text vs binary, encodings (enough), pathlib",
      "JSON and CSV read/write",
      "try/except/finally, raising, custom messages; EAFP style",
    ],
    prereqs: [{ id: "l1-data-structures" }],
    hours: 4,
    primary: { resourceId: "think-python", sections: "Files chapter + JSON exercises" },
    references: [{ resourceId: "atbs", sections: "Files/JSON chapters as lookup" }],
    exercises: [
      "Experiment logger: append JSON-lines results, then a loader that summarizes them",
      "Robust file reader: handles missing file, bad encoding, malformed line, each with a distinct, informative error path",
    ],
    masteryGate: "silver",
    masteryTest: "Build a config-driven script: reads params.json, validates fields with clear errors, writes results.csv, and survives five adversarial inputs I throw at it.",
    diagnostic: "When would you catch an exception vs let it crash? Show the with-statement equivalent of try/finally close.",
  },
  {
    id: "l1-classes",
    level: 1,
    title: "Classes: Exactly Enough OOP",
    track: "code",
    labs: ["code"],
    why: "PyTorch modules, gym environments, and every robotics framework are classes. You need to read and write them, not to worship inheritance hierarchies.",
    objectives: [
      "class/__init__/self/methods/attributes; dataclasses",
      "__repr__, __eq__, __len__ dunders (reading fluency)",
      "Single inheritance + super() as used by nn.Module, and why deep hierarchies are avoided",
    ],
    prereqs: [{ id: "l1-functions" }],
    hours: 4,
    primary: { resourceId: "think-python", sections: "The OOP block (returned to, as scheduled)" },
    skip: ["Multiple inheritance, metaclasses, descriptors: read about them the day a library forces you"],
    exercises: [
      "Vector2D class with +, *, norm, __repr__, then rewrite as @dataclass",
      "Read a small gym-style Env class and diagram its lifecycle (reset/step)",
    ],
    masteryGate: "silver",
    masteryTest: "Design a Particle class hierarchy for a toy simulator (state, step(dt), energy) and justify every method's placement.",
    diagnostic: "What is `self`? What does `super().__init__()` do in a subclass of nn.Module-style base?",
  },
  {
    id: "l1-testing-modules",
    level: 1,
    title: "Modules, pytest & Typing Basics",
    track: "code",
    labs: ["code"],
    why: "Tests are how you'll verify your kinematics library against oracles and your PPO against reference curves, the research habit that separates evidence from vibes.",
    objectives: [
      "Modules/imports/__main__; project layout; making a small installable package",
      "pytest: test functions, asserts, parametrize, running subsets",
      "Type hints as documentation; mypy-lite discipline",
    ],
    prereqs: [{ id: "l1-functions" }],
    hours: 5,
    primary: { resourceId: "cs50p", sections: "Week 5 (Unit Tests), the best beginner pytest intro anywhere" },
    backup: { resourceId: "exercism", sections: "Continue track; every exercise is test-driven" },
    exercises: [
      "Write tests FIRST for a stats module (mean/median/variance), then implement to green",
      "Add type hints to three earlier exercises; find one real bug via hints",
    ],
    masteryGate: "gold",
    masteryTest: "Package your stats module (pyproject, src layout), 10+ tests incl. edge cases and a parametrized suite, installable with pip -e, reviewed for test quality.",
    diagnostic: "Why does `python file.py` vs `import file` behave differently (__name__)? Write a parametrized pytest for abs().",
  },
  {
    id: "l1-numpy",
    level: 1,
    title: "NumPy: Arrays, Broadcasting, Vectorization",
    track: "code",
    labs: ["code", "ml"],
    why: "NumPy's array model IS PyTorch's tensor model. Shapes, broadcasting, and views learned here transfer one-to-one to every network you'll ever build.",
    objectives: [
      "ndarray creation, dtype, shape, reshape; axis semantics of reductions",
      "Broadcasting rules applied confidently (and predicted before running)",
      "Fancy vs boolean indexing; views vs copies",
      "Replace loops with vectorized ops by reflex",
    ],
    prereqs: [{ id: "l1-data-structures" }],
    hours: 8,
    primary: { resourceId: "numpy-docs", sections: "Absolute basics → quickstart → Broadcasting, Indexing, Copies & views" },
    backup: { resourceId: "scipy-lectures", sections: "NumPy chapter" },
    references: [{ resourceId: "py2numpy", sections: "Case studies (after 2 weeks of use)" }],
    equations: ["\\text{broadcast: } (m,1)\\odot(1,n)\\to(m,n)"],
    exercises: [
      "Predict result shapes for 15 broadcasting expressions before running",
      "Pairwise distance matrix of N points: loop version, then fully vectorized; time both",
      "Image-as-array: load, crop, flip, channel-swap a picture with pure indexing",
    ],
    masteryGate: "gold",
    masteryTest: "Vectorize three loop-based numerical routines (moving average, standardize-by-column, k-nearest by distance matrix) with zero Python loops and matching outputs.",
    diagnostic: "Shape of (3,1)+(1,4)? Of A[Boolean mask]? Does `a[2:5]` copy? Prove each in the REPL.",
    misconceptions: ["`axis=0` means 'collapse rows' (operate DOWN columns). Draw it once, never confuse it again."],
  },
  {
    id: "l1-matplotlib",
    level: 1,
    title: "Matplotlib & the Jupyter Workflow",
    track: "code",
    labs: ["code"],
    why: "You cannot debug what you cannot see. Loss curves, trajectories, filters, attention maps: plotting is your instrument panel for the next 200 days.",
    objectives: [
      "fig/ax object API (not pyplot state soup): line, scatter, hist, imshow, subplots",
      "Labels/legends/log-scales; save publication-quality figures",
      "Notebook discipline: restart-and-run-all as the truth test",
    ],
    prereqs: [{ id: "l1-numpy" }],
    hours: 4,
    primary: { resourceId: "matplotlib-docs", sections: "Quick start + pyplot tutorial (OO style)" },
    exercises: [
      "One figure, 4 subplots: function family, histogram, scatter with colormap, image",
      "Recreate a published loss-curve figure (axes, legend, styling) from its picture",
    ],
    masteryGate: "silver",
    masteryTest: "Given a CSV of noisy experiment runs, produce a mean±std band plot across seeds with proper labels, the exact figure you'll make 50 times this year.",
    diagnostic: "Why prefer `fig, ax = plt.subplots()` over `plt.plot` globals? Show log-scale on y.",
  },
  {
    id: "l1-vectorization-craft",
    level: 1,
    title: "Vectorization Craft (Thinking in Arrays)",
    track: "code",
    labs: ["code", "ml"],
    why: "The gap between 'knows NumPy functions' and 'thinks in arrays' is the gap between copying ML code and writing it. This node closes it.",
    objectives: [
      "Translate problem statements into array formulations",
      "einsum/tensordot reading fluency",
      "Profile first, optimize second (timeit)",
    ],
    prereqs: [{ id: "l1-numpy" }],
    hours: 4,
    primary: { resourceId: "py2numpy", sections: "Worked case studies: ch. 4 Game of Life (work through), Mandelbrot (read), boids (skim) (curation 2026-08-21: the book has no gradient-descent case)" },
    exercises: [
      "Conway's Game of Life step with zero loops",
      "Batch polynomial evaluation via Vandermonde matrix",
      "Write matmul three ways: loops, broadcasting+sum, einsum. Verify equal, time them",
    ],
    masteryGate: "silver",
    masteryTest: "Vectorize an unseen simulation kernel (I provide the loop version) achieving ≥50× speedup with identical output.",
    diagnostic: "Read `np.einsum('ij,jk->ik', A, B)` aloud; what is `np.einsum('bij,bjk->bik', A, B)`?",
  },
  {
    id: "l1-project-simulation",
    level: 1,
    title: "Project P1: Numerical Physics Toy",
    track: "project",
    labs: ["code", "robotics"],
    why: "Your first real program: simulate, integrate, visualize. Introduces timesteps and state, the exact skeleton of every robot simulator you'll ever touch.",
    objectives: [
      "State + Euler integration loop; timestep effects observed",
      "Projectile with drag; energy tracking; parameter sweeps",
    ],
    prereqs: [{ id: "l1-matplotlib" }, { id: "l1-testing-modules" }, { id: "l2-functions-graphs" }],
    hours: 7,
    implementation: "Projectile (then bouncing-ball or orbit) simulator: state vector, step function, integrator, trajectory plots, parameter sweep grid; tests for the physics helpers.",
    exercises: [
      "Show energy drift vs timestep for Euler; then implement semi-implicit Euler and compare",
      "Sweep launch angle → range curve; find the optimum numerically",
    ],
    masteryGate: "gold",
    masteryTest: "P1 accepted: clean repo, tests green, README with three figures, and a 10-line writeup of what the timestep experiment showed.",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    projectIds: ["p1-physics-toy"],
  },
  {
    id: "boss-programming",
    level: 1,
    title: "BOSS: Programming",
    track: "project",
    labs: ["code"],
    why: "Gate out of Level 1: build a numerical simulation from a written spec, alone, from a blank file.",
    objectives: ["Prove independent construction, the anti-tutorial-hell certificate"],
    prereqs: [
      { id: "l1-project-simulation", tier: "gold" },
      { id: "l1-files-errors" },
      { id: "l1-classes" },
      { id: "l1-vectorization-craft" },
    ],
    hours: 6,
    masteryGate: "gold",
    masteryTest: "Timed (one sitting): from a two-page spec (predator–prey grid world with config file, CLI, plots, and 3 required tests), produce a working, tested, committed repo. No AI code generation; docs allowed.",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    exercises: [],
  },
];
