import type { SkillNode } from "@/lib/types";

export const L10_NODES: SkillNode[] = [
  {
    id: "l10-mdp",
    level: 10,
    title: "MDPs, Returns & Value Functions",
    track: "core",
    labs: ["ml", "embodied"],
    why: "The formal language of sequential decision-making. Every policy, reward, and value you'll meet, including RECAP's advantage conditioning, is defined in this vocabulary. Get it exact.",
    objectives: [
      "States/actions/transitions/rewards/discount; episodic vs continuing",
      "Policies; returns; V and Q defined precisely; Bellman expectation + optimality equations",
      "Reward design as problem specification (and its hazards)",
    ],
    prereqs: [{ id: "l2-random-variables", tier: "gold" }, { id: "l3-ml-framing" }],
    hours: 6,
    primary: { resourceId: "sutton-barto", sections: "Ch 3 (MDPs), slow, exact reading" },
    backup: { resourceId: "spinningup-essays", sections: "Intro to RL parts 1–2" },
    equations: [
      "G_t = \\sum_{k=0}^{\\infty} \\gamma^k r_{t+k+1}",
      "V^{\\pi}(s) = \\mathbb{E}_{\\pi}[G_t \\mid s_t = s]",
      "Q^{*}(s,a) = \\mathbb{E}[r + \\gamma \\max_{a'} Q^{*}(s',a')]",
    ],
    exercises: [
      "Formalize three tasks as MDPs (gridworld, cart-pole, pick-and-place): explicitly write S, A, r, γ, the modeling drill",
      "Hand-compute V for a 4-state chain under two policies; verify by simulation",
    ],
    masteryGate: "gold",
    masteryTest: "Derive the Bellman expectation equation from the return definition on paper, and design a reward for 'stack two blocks' that you then critique for hackability.",
    diagnostic: "What does γ trade? Why is Q more directly useful than V for control? Write V in terms of Q.",
  },
  {
    id: "l10-tabular",
    level: 10,
    title: "Dynamic Programming, TD & Tabular Q-Learning",
    track: "core",
    labs: ["ml"],
    why: "Where the ideas are visible: value iteration you can watch converge, TD errors you can print, Q-tables you can read. The Gold gate before ANY deep-RL library is allowed (the L3 rule, RL edition).",
    objectives: [
      "Value iteration / policy iteration on a known MDP",
      "TD(0) vs Monte-Carlo targets; bootstrapping",
      "ε-greedy exploration; Q-learning (off-policy) implemented and understood",
    ],
    prereqs: [{ id: "l10-mdp" }],
    hours: 6,
    primary: { resourceId: "sutton-barto", sections: "Ch 4–6 (DP, MC, TD); implement as you read" },
    equations: ["Q(s,a) \\mathrel{+}= \\alpha\\,[r + \\gamma \\max_{a'}Q(s',a') - Q(s,a)]"],
    implementation: "Gridworld value iteration (heatmap animation of V converging) + tabular Q-learning on FrozenLake/cliff-walk with an exploration study.",
    exercises: ["Cliff-walking: show Q-learning vs SARSA taking different paths; explain on/off-policy from YOUR plot"],
    masteryGate: "gold",
    masteryTest: "Blank file: value iteration + Q-learning both solving a gridworld, with the TD-error plot and a paragraph deriving why Q-learning converges off-policy (intuition level).",
    diagnostic: "What is bootstrapping? Why does Q-learning learn the greedy policy while behaving ε-greedy?",
  },
  {
    id: "l10-dqn",
    level: 10,
    title: "Function Approximation & DQN (One Day)",
    track: "core",
    labs: ["ml"],
    why: "The deadly triad (bootstrapping + off-policy + function approximation) and the two fixes that launched deep RL: replay buffers and target networks. Budget one day: the field moved to PPO/SAC, and so will you.",
    objectives: [
      "Why naive neural TD diverges; replay + target networks as stabilizers",
      "DQN on CartPole, working",
    ],
    prereqs: [{ id: "l10-tabular", tier: "gold" }, { id: "l4-training-loop", tier: "gold" }],
    hours: 4,
    primary: { resourceId: "cleanrl", sections: "dqn.py read + your own minimal reimplementation" },
    skip: ["Atari, Rainbow, distributional RL: archaeology for this target (audited cut)"],
    exercises: ["Ablate the target network: watch training destabilize; bring it back"],
    masteryGate: "silver",
    masteryTest: "Your DQN solves CartPole with the target-network ablation plot and a correct explanation of what each stabilizer fixes.",
    diagnostic: "Name the deadly triad. What exactly does the target network hold still?",
  },
  {
    id: "l10-policy-gradient",
    level: 10,
    title: "Policy Gradients & GAE, Derived",
    track: "core",
    labs: ["ml", "math"],
    why: "Optimize the policy directly, the idea behind PPO, and (via advantage estimation) behind how VLAs are RL-fine-tuned in 2026. The log-derivative trick is one of the great moves in ML; you derive it.",
    objectives: [
      "REINFORCE derived via the log-derivative trick; why high variance",
      "Baselines don't bias (proved); advantage A = Q - V",
      "GAE: the λ dial between bias and variance",
    ],
    prereqs: [{ id: "l10-mdp", tier: "gold" }, { id: "l3-backprop-theory", tier: "gold" }],
    hours: 7,
    primary: { resourceId: "spinningup-essays", sections: "Part 3: Intro to Policy Optimization (log-derivative trick, EGLP, reward-to-go, baselines) + S&B §13.1–13.4, then implement REINFORCE from scratch (curation 2026-08-21, HANDOVERFINAL §15: CS285-first is wrong for first exposure)" },
    backup: { resourceId: "cs285", sections: "Lectures 5–6 as DEEPEN after your REINFORCE works; first legitimate CS285 contact is l10-ppo" },
    equations: [
      "\\nabla_\\theta J = \\mathbb{E}\\big[\\textstyle\\sum_t \\nabla_\\theta \\log \\pi_\\theta(a_t\\mid s_t)\\, A_t\\big]",
      "A^{GAE(\\lambda)}_t = \\sum_{l} (\\gamma\\lambda)^l \\delta_{t+l},\\;\\; \\delta_t = r_t + \\gamma V(s_{t+1}) - V(s_t)",
    ],
    implementation: "REINFORCE from scratch on CartPole; add a learned value baseline; plot variance of gradient estimates with/without baseline (measure it, don't assert it).",
    exercises: ["Derive ∇J on paper start-to-finish including the baseline-unbiasedness step; then implement GAE and sweep λ ∈ {0, 0.9, 0.95, 1}"],
    masteryGate: "gold",
    masteryTest: "The full derivation reproduced closed-book + REINFORCE-with-baseline working, with your measured variance-reduction plot.",
    diagnostic: "Why does the log-derivative trick work (one line)? What does λ=0 vs λ=1 give you?",
  },
  {
    id: "l10-ppo",
    level: 10,
    title: "PPO From Scratch (The 37 Details)",
    track: "core",
    labs: ["ml"],
    why: "The workhorse of robot RL and VLA fine-tuning alike. A paper-correct PPO that doesn't train is normal. The craft is the 37 implementation details, and you learn them by needing them.",
    objectives: [
      "Clipped surrogate objective; why trust regions matter",
      "Vectorized rollout buffers; minibatch epochs; advantage normalization",
      "Entropy bonus; value clipping; the debugging metrics (KL, clip fraction, explained variance)",
    ],
    prereqs: [{ id: "l10-policy-gradient", tier: "gold" }],
    hours: 9,
    primary: { resourceId: "ppo-37-details", sections: "Alongside your build: every detail as you hit its absence" },
    backup: { resourceId: "cleanrl", sections: "ppo.py + ppo_continuous_action.py as reference curves" },
    equations: ["L^{CLIP} = \\mathbb{E}\\big[\\min(r_t A_t,\\; \\operatorname{clip}(r_t, 1\\pm\\epsilon) A_t)\\big],\\;\\; r_t = \\tfrac{\\pi_\\theta(a|s)}{\\pi_{old}(a|s)}"],
    implementation: "PPO from a blank file: CartPole first, then continuous-action Hopper/HalfCheetah (Gymnasium-MuJoCo); validate against CleanRL reference curves on matched seeds.",
    exercises: [
      "Ablate 3 details (advantage norm, orthogonal init, LR anneal): quantify each on Hopper",
      "Log KL + clip fraction; identify a 'silent failure' run from metrics alone",
    ],
    masteryGate: "gold",
    masteryTest: "Your PPO reaches CleanRL-comparable returns on Hopper within 2× wall-clock, ablation table included. This Gold-gates all RL libraries.",
    diagnostic: "What does the clip do when A>0 vs A<0? Which metric tells you the policy is changing too fast?",
    projectIds: ["p16-rl-manipulation"],
    computeNote: "CPU-fine for CartPole; Hopper minutes-to-an-hour on any GPU or decent CPU.",
  },
  {
    id: "l10-sac",
    level: 10,
    title: "SAC & Continuous Control",
    track: "core",
    labs: ["ml"],
    why: "The off-policy counterpart: replay-efficient, entropy-regularized, the algorithm inside HIL-SERL and most real-robot RL. Implementing both PPO and SAC gives you the two poles of model-free RL.",
    objectives: [
      "Max-entropy RL: why 'be good AND stay random'",
      "Twin critics; target networks; automatic temperature tuning",
      "Squashed Gaussian policies; reparameterization (vs log-derivative; connect to PG)",
    ],
    prereqs: [{ id: "l10-ppo", tier: "gold" }],
    hours: 6,
    primary: { resourceId: "cleanrl", sections: "sac_continuous_action.py; read, then reimplement core" },
    equations: ["J(\\pi) = \\mathbb{E}\\big[\\textstyle\\sum_t r_t + \\alpha \\mathcal{H}(\\pi(\\cdot\\mid s_t))\\big]"],
    implementation: "SAC from scratch on HalfCheetah; sample-efficiency comparison vs your PPO (env steps to threshold return, 3 seeds each).",
    exercises: ["Freeze α at 3 values vs auto-tune: show the exploration collapse/chaos regimes"],
    masteryGate: "gold",
    masteryTest: "Working SAC + the PPO-vs-SAC study (sample efficiency, wall-clock, stability across seeds) written up as a mini-report.",
    diagnostic: "Why twin critics? Why does off-policy make SAC sample-efficient but touchier?",
  },
  {
    id: "l10-parallel-rl",
    level: 10,
    title: "GPU-Parallel Robot RL (Playground + ManiSkill3)",
    track: "core",
    labs: ["ml", "robotics", "embodied"],
    why: "The 2026 phase change: thousands of MuJoCo-Warp environments on one consumer GPU. A Go1 walks in 7 documented minutes on a 4090. You port YOUR PPO to the vectorized world and feel why the field moved.",
    objectives: [
      "Vectorized-env semantics: batched obs/actions, auto-resets, GAE over partial rollouts",
      "MuJoCo Playground locomotion (Go1) + inspection of its reward/DR configs",
      "ManiSkill3 PushCube/PickCube with the CleanRL-style baseline, then with your PPO",
    ],
    prereqs: [{ id: "l10-ppo", tier: "gold" }, { id: "l5-mujoco-basics" }],
    hours: 6,
    primary: { resourceId: "mujoco-playground", sections: "Locomotion notebook (Go1) end-to-end + config reading" },
    backup: { resourceId: "maniskill", sections: "PPO baseline: PushCube state → PickCube RGB" },
    implementation: "Port your PPO to ManiSkill3's vectorized API; solve PushCube-state with 2048 envs (<1 min when correct, the brutal correctness oracle); then Playground Go1 with the provided trainer.",
    exercises: ["Sweep num_envs ∈ {16, 256, 2048}: plot wall-clock and sample efficiency; explain the tradeoff"],
    masteryGate: "gold",
    masteryTest: "Your PPO solves PushCube in parallel + a trained Go1 walking policy, with a half-page on what vectorization changed in your implementation (resets, advantage bookkeeping).",
    diagnostic: "Why do parallel envs shift the PPO bottleneck to the GPU? What breaks if you mishandle auto-reset boundaries in GAE?",
    computeNote: "Documented: Go1 ≈7 min, PickCube 2–5 min on RTX 4090; 12 GB workable for state-based tasks.",
  },
  {
    id: "l10-offline-iql",
    level: 10,
    title: "Offline RL Essentials: IQL",
    track: "core",
    labs: ["ml", "embodied"],
    why: "Demoted-but-load-bearing (audited): offline RL is the value-learning half of modern VLA post-training. RECAP is advantage-conditioned offline-style RL. You study the one algorithm that survived: IQL.",
    objectives: [
      "The offline problem: distribution shift, overestimation of unseen actions",
      "IQL: expectile value regression + advantage-weighted extraction, with no OOD queries",
      "The through-line to 2026: advantage conditioning in π*0.6",
    ],
    prereqs: [{ id: "l10-sac", tier: "gold" }],
    hours: 4,
    primary: { resourceId: "corl-iql", sections: "iql.py: a guided line-by-line study, then implement the two losses yourself on a small dataset" },
    equations: [
      "L_V = \\mathbb{E}\\,[\\,|\\tau - \\mathbb{1}(u<0)|\\,u^2\\,],\\; u = Q(s,a)-V(s)",
      "\\pi: \\max \\mathbb{E}\\,[\\exp(\\beta A(s,a))\\log\\pi(a\\mid s)]",
    ],
    exercises: ["On a gridworld dataset YOU generate (mixed-quality policies): show naive Q-learning overestimating, IQL not"],
    masteryGate: "silver",
    masteryTest: "The two IQL losses implemented and working on your toy dataset + one paragraph tracing expectile-value → advantage-conditioning → RECAP.",
    diagnostic: "Why can't you just run Q-learning on a fixed dataset? What does the expectile τ→1 approximate?",
  },
  {
    id: "l10-eval-pitfalls",
    level: 10,
    title: "RL Evaluation Pitfalls",
    track: "research",
    labs: ["ml"],
    why: "RL results are the least reproducible in ML: seed lotteries, eval-vs-train confusion, reward hacking. Installing the skepticism now makes your robot-learning comparisons (next level) credible.",
    objectives: [
      "Seed variance quantified; why 3–5 seeds minimum; overlapping error bands",
      "Deterministic-eval vs stochastic-train policies; eval episode counts",
      "Reward hacking: the failure mode where the metric wins and the task loses",
    ],
    prereqs: [{ id: "l10-ppo", tier: "gold" }],
    hours: 2,
    primary: { resourceId: "cs285", sections: "Evaluation discussions + your own seed study" },
    exercises: ["Run your Hopper PPO on 8 seeds: plot the full distribution; find the pair of seeds that would 'prove' a fake improvement"],
    masteryGate: "silver",
    masteryTest: "A one-page 'how I will report RL results' protocol (seeds, eval counts, CIs, what curves shown) that you then follow for the rest of the program.",
    diagnostic: "Why is a 2-seed comparison worthless? Give one concrete reward-hack you could imagine in a manipulation task.",
  },
];
