import type { SkillNode } from "@/lib/types";

export const L11_NODES: SkillNode[] = [
  {
    id: "l11-bc-dagger",
    level: 11,
    title: "Behavior Cloning & DAgger",
    track: "core",
    labs: ["ml", "embodied"],
    why: "Imitation is how most robot skills are trained in 2026, and covariate shift is its original sin. BC + DAgger (CS285 HW1) is the canonical entry, and LeRobot's rollout 'dagger' mode makes the fix tangible.",
    objectives: [
      "BC as supervised learning on demonstrations; why it's not 'just' supervised (compounding errors)",
      "Covariate shift: the drift-off-distribution death spiral, produced and measured",
      "DAgger: querying the expert on YOUR states; the labeling-cost tradeoff",
    ],
    prereqs: [{ id: "l4-training-loop", tier: "gold" }, { id: "l10-mdp", tier: "gold" }],
    hours: 6,
    primary: { resourceId: "cs285", sections: "Lecture 2 (Supervised Learning of Behaviors) + Spring-2026 HW1 (BC + DAgger in MuJoCo)" },
    equations: ["\\mathbb{E}_{p_{\\pi}(s)}[\\ell] \\ne \\mathbb{E}_{p_{\\text{data}}(s)}[\\ell]", "\\text{BC error compounds: } O(\\epsilon T^2)\\;\\text{vs DAgger } O(\\epsilon T)"],
    implementation: "CS285 HW1: BC on expert MuJoCo demos, measure the performance gap vs expert; implement DAgger and plot its recovery across iterations.",
    exercises: ["Vary demo count 5→500: plot the BC scaling curve; find where more data stops helping (and reason why)"],
    masteryGate: "gold",
    masteryTest: "HW1-grade artifact: BC + DAgger implemented, the compounding-error story told with YOUR plots, and the T vs T² argument reproduced on paper.",
    diagnostic: "Why does a 1% per-step error rate destroy a 200-step episode? What exactly does DAgger change about the data distribution?",
    paperIds: ["paper-dagger"],
  },
  {
    id: "l11-lerobot",
    level: 11,
    title: "LeRobot: The Workbench",
    track: "code",
    labs: ["embodied", "code"],
    why: "The field's shared workbench (26.8k★, ICLR 2026): datasets, policies, evaluation, teleop in one API. Every hands-on exercise from here to the capstone runs through it. Learn it as infrastructure.",
    objectives: [
      "LeRobotDataset v3: episodes/frames/streaming; loading pusht and inspecting tensors",
      "lerobot-train / lerobot-eval CLIs; policy configs; the env registry (pusht, aloha, libero)",
      "First end-to-end: train Diffusion Policy on PushT (official minimal example), evaluate 50 episodes",
    ],
    prereqs: [{ id: "l11-bc-dagger" }],
    hours: 5,
    primary: { resourceId: "lerobot", sections: "Getting started + dataset v3 docs + examples/training/train_policy.py (DP on PushT)" },
    backup: { resourceId: "robot-learning-tutorial", sections: "The tutorial's IL chapters" },
    implementation: "Run the official minimal training example end-to-end on PushT; then write your own dataset-inspection notebook (episode lengths, action distributions, camera frames).",
    exercises: ["Stream one DROID slice from the Hub; compare its structure to pusht, your first look at real-robot-scale data"],
    masteryGate: "gold",
    masteryTest: "From clean env: install, train DP-on-PushT (short run), evaluate with lerobot-eval, and explain every field of the dataset schema from your inspection notebook.",
    diagnostic: "What does delta_timestamps do? Where do normalization stats live and why do they matter at eval?",
  },
  {
    id: "l11-act",
    level: 11,
    title: "ACT: Action Chunking with Transformers",
    track: "core",
    labs: ["embodied", "ml"],
    why: "The standard first real IL policy: a CVAE-transformer predicting CHUNKS of actions, the idea (predict sequences, not steps) that every VLA inherited. Your transformer skills meet robots here.",
    objectives: [
      "Action chunking: why predicting k=100 steps fights compounding error and multimodality",
      "The CVAE structure: latent z for demonstration style; temporal ensembling at inference",
      "ACT's architecture read completely (encoder/decoder, camera tokens, proprio)",
    ],
    prereqs: [{ id: "l11-lerobot" }, { id: "l4-transformer", tier: "gold" }],
    hours: 6,
    primary: { resourceId: "act-repo", sections: "Paper (2304.13705) + LeRobot ACT implementation read side-by-side; 'tuning tips' doc" },
    equations: ["\\pi(a_{t:t+k}\\mid o_t);\\;\\; L = \\|a - \\hat a\\|_1 + \\beta\\, D_{KL}(q(z\\mid a, o)\\,\\|\\,\\mathcal{N}(0,I))"],
    implementation: "Train ACT on gym-aloha TransferCube (scripted demos): LeRobot config, W&B-tracked, evaluated ≥50 episodes; ablate chunk size k ∈ {1, 10, 100}.",
    exercises: ["The k=1 ablation IS behavior cloning. Connect its failure back to l11-bc-dagger quantitatively"],
    masteryGate: "gold",
    masteryTest: "Trained ACT with the chunk-size ablation table + a from-memory architecture diagram (every tensor labeled) + one paragraph: what the CVAE latent buys.",
    diagnostic: "Why chunk? What does temporal ensembling smooth over? What role does z play at train vs test time?",
    paperIds: ["paper-act"],
  },
  {
    id: "l11-diffusion",
    level: 11,
    title: "Diffusion Models (DDPM Core)",
    track: "core",
    labs: ["ml"],
    why: "Deferred from L4 on purpose. You learn diffusion exactly when robotics needs it. Noise-in, structure-out: the generative engine of Diffusion Policy and (via flow matching) of π0's action expert.",
    objectives: [
      "Forward noising process; the denoising objective (predict ε)",
      "Training/sampling loops; noise schedules; classifier-free guidance (concept)",
      "2D toy diffusion built from scratch, the full pipeline in miniature",
    ],
    prereqs: [{ id: "l4-transformer", tier: "gold" }],
    hours: 6,
    primary: { resourceId: "labml", sections: "Annotated DDPM implementation as reference for your own build" },
    equations: [
      "x_t = \\sqrt{\\bar\\alpha_t}\\,x_0 + \\sqrt{1-\\bar\\alpha_t}\\,\\epsilon",
      "L = \\mathbb{E}_{t,x_0,\\epsilon}\\,\\|\\epsilon - \\epsilon_\\theta(x_t, t)\\|^2",
    ],
    implementation: "DDPM from scratch on 2D point distributions (spiral, two-moons): train the denoiser MLP, animate samples flowing from noise to structure.",
    exercises: ["Sweep sampling steps 5→1000: quality-vs-speed plot, the latency problem flow matching will solve"],
    masteryGate: "gold",
    masteryTest: "Blank-file 2D DDPM producing clean spirals + the objective derivation sketch (why predicting ε works) on paper.",
    diagnostic: "What does the model actually predict and why is that easier than predicting x₀ directly? Why is sampling slow?",
    paperIds: ["paper-ddpm"],
  },
  {
    id: "l11-diffusion-policy",
    level: 11,
    title: "Diffusion Policy, From Scratch",
    track: "core",
    labs: ["embodied", "ml"],
    why: "The 2026-verified 'first policy class to implement from scratch': diffusion over ACTION chunks conditioned on observations. Multimodal demonstrations (go left OR right) stop being a problem. You see why, in your own code.",
    objectives: [
      "Action-sequence diffusion conditioned on observation features",
      "Receding-horizon execution (predict 16, execute 8)",
      "Why mean-regression BC fails on multimodal data and diffusion doesn't",
    ],
    prereqs: [{ id: "l11-diffusion", tier: "gold" }, { id: "l11-lerobot", tier: "gold" }],
    hours: 8,
    primary: { resourceId: "diffusion-policy-repo", sections: "Paper + official state-based Colab; then YOUR from-scratch build on PushT state-obs" },
    equations: ["a^0 \\sim \\text{denoise}(a^T\\!\\sim\\!\\mathcal{N}, \\; o)\\;\\text{over chunk } a_{t:t+H}"],
    implementation: "Your own diffusion action head (MLP/U-Net denoiser) trained on lerobot/pusht state observations; evaluated in gym-pusht ≥50 episodes; cross-checked against LeRobot's diffusion policy on the same data.",
    exercises: ["Construct a synthetic fork dataset (two valid paths): show BC averaging into the wall, diffusion committing to a mode, the level's money plot"],
    masteryGate: "gold",
    masteryTest: "From-scratch DP within 10 success-points of LeRobot's reference on PushT (state), plus the multimodality money plot and a written explanation.",
    diagnostic: "Why does the denoiser condition on observations but not the noise schedule? What does receding-horizon re-planning forgive?",
    paperIds: ["paper-diffusion-policy"],
    projectIds: ["p18-policy-comparison"],
    computeNote: "8 GB GPU: ~1–4 h per training run (documented).",
  },
  {
    id: "l11-flow-matching",
    level: 11,
    title: "Flow Matching: The ~50-Line Delta",
    track: "core",
    labs: ["embodied", "ml"],
    why: "The 2025–26 shift: π0, GR00T, X-VLA all generate actions by flow matching (straight-line probability paths, few-step inference). From your DDPM it is a ~50-line change, and making that change is the fastest way to own it.",
    objectives: [
      "Rectified-flow objective: regress the velocity field along linear interpolants",
      "ODE-integration sampling in 1–10 steps vs DDPM's many",
      "Why VLAs chose flow (latency at control rates, simplicity)",
    ],
    prereqs: [{ id: "l11-diffusion-policy", tier: "gold" }],
    hours: 4,
    primary: { resourceId: "labml", sections: "Flow-matching reference + Lipman paper §core; port YOUR DP to rectified flow" },
    equations: [
      "x_t = (1-t)x_0 + t\\,x_1;\\;\\; L = \\mathbb{E}\\,\\|v_\\theta(x_t, t) - (x_1 - x_0)\\|^2",
    ],
    implementation: "Convert your from-scratch PushT diffusion head to rectified flow; match success at 10 inference steps; plot success-vs-steps for both models on one figure.",
    exercises: ["Time policy inference DDPM-50-step vs flow-5-step at batch 1, the number that explains a 50 Hz control loop"],
    masteryGate: "gold",
    masteryTest: "The conversion done and benchmarked (the success-vs-steps figure), plus a paragraph: exactly which lines changed and why the objective still produces the data distribution.",
    diagnostic: "What does the network regress in flow matching vs DDPM? Why can flow sample in so few steps?",
    paperIds: ["paper-flow-matching"],
  },
  {
    id: "l11-eval-statistics",
    level: 11,
    title: "Policy Evaluation Statistics",
    track: "research",
    labs: ["embodied", "ml"],
    why: "The field's 2026 wake-up: at 90% observed success, 70 rollouts give a ±8pp confidence interval; benchmark saturation hides real differences. This node makes your comparisons mean something, and it is the cheapest research edge you own.",
    objectives: [
      "Binomial CIs on success rates; the rollout-count math internalized",
      "Seeds × episodes design; when a difference is real (and the sequential-testing idea)",
      "Benchmark skepticism: LIBERO saturation, LIBERO-Plus perturbation collapses, and what scores do and don't mean",
    ],
    prereqs: [{ id: "l10-eval-pitfalls" }, { id: "l2-stats-mle", tier: "gold" }],
    hours: 4,
    primary: { resourceId: "libero", sections: "LIBERO protocol + LIBERO-Plus robustness results read critically" },
    equations: ["\\text{Wilson CI on } \\hat p = k/n;\\;\\; n{=}50 \\Rightarrow \\pm\\sim{9}\\text{pp at } p{=}0.8"],
    exercises: [
      "Write ci(k, n) and TABLE the interval widths for n ∈ {10, 20, 50, 100, 400}. Pin it above your desk",
      "Simulate two policies with true 70% vs 75%: how many episodes until the difference is detectable at 95%?",
    ],
    masteryGate: "gold",
    masteryTest: "Your written evaluation protocol (episodes, seeds, CIs, robustness variants) applied retroactively to one earlier experiment, including the honest admission of what it invalidates.",
    diagnostic: "20 episodes, 16 successes: give the CI. Why must the Robot Learning Boss use ≥50 episodes × 3 seeds?",
    paperIds: ["paper-libero", "paper-roboarena"],
  },
  {
    id: "l11-data-quality",
    level: 11,
    title: "Demonstrations, Teleop & Dataset Quality",
    track: "core",
    labs: ["embodied"],
    why: "Policies are functions of their data. Collection method (leader-arm, GELLO, UMI, phone), demo consistency, and coverage decide success before any architecture does. The 2026 ecosystem made this tooling-real (LeRobot record/correct/rollout).",
    objectives: [
      "Teleop options: leader-follower, GELLO, UMI handheld, phone, with a tradeoffs table",
      "Dataset audits: action distributions, demo length variance, idle-frame pollution, coverage",
      "Correction workflows: LeRobot rollout modes (base/sentry/dagger) as interactive imitation",
    ],
    prereqs: [{ id: "l11-lerobot", tier: "gold" }],
    hours: 3,
    primary: { resourceId: "lerobot", sections: "il_robots tutorial (record→visualize→train loop, correction rollouts); sim path via LeIsaac/keyboard teleop" },
    exercises: [
      "Audit lerobot/pusht like a reviewer: plot action/state coverage, find its quirks",
      "Deliberately pollute a training set (10% idle frames): measure the policy damage, then filter and recover",
    ],
    masteryGate: "silver",
    masteryTest: "A one-page 'dataset datasheet' for a dataset you assembled or audited: collection method, coverage plots, known biases, expected failure modes, the habit real labs enforce.",
    diagnostic: "Why do idle frames poison BC? What does UMI trade against leader-arm teleop?",
  },
  {
    id: "boss-robot-learning",
    level: 11,
    title: "BOSS: Robot Learning",
    track: "project",
    labs: ["embodied"],
    why: "The handover's Robot Learning Boss, upgraded with 2026 eval rigor: a controlled comparison of policy classes on one task, with statistics that would survive review.",
    objectives: ["Train/evaluate multiple policies and diagnose distribution shift like a researcher"],
    prereqs: [
      { id: "l11-diffusion-policy", tier: "gold" },
      { id: "l11-act", tier: "gold" },
      { id: "l11-flow-matching" },
      { id: "l11-eval-statistics", tier: "gold" },
    ],
    hours: 10,
    masteryGate: "gold",
    masteryTest: "The PushT Study: BC-MLP (yours) vs ACT vs Diffusion Policy (yours), with identical data/obs, 3 seeds × 50 episodes each, Wilson CIs, chunk-size ablation, a distribution-shift probe (perturbed initial states), and a 2-page report with the money plots. Pass = defensible conclusions, not a winner.",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    exercises: [],
    projectIds: ["p18-policy-comparison"],
    computeNote: "Full grid ≈ a weekend on one 8–16 GB GPU (documented per-run numbers).",
  },
];
