import type { SkillNode } from "@/lib/types";

export const L12_NODES: SkillNode[] = [
  {
    id: "l12-vla-anatomy",
    level: 12,
    title: "VLA Anatomy: The Convergent Recipe",
    track: "core",
    labs: ["embodied"],
    why: "The 2026 field converged: VLM backbone (kept close to language pretraining) + chunked flow/diffusion action expert + discrete tokens where unification is needed. Learn the shared anatomy once and every VLA paper becomes a diff against it.",
    objectives: [
      "The observation path: images→ViT patches, language→tokens, proprio→embeddings",
      "Action heads taxonomy: discrete tokens vs continuous regression vs diffusion/flow experts",
      "Knowledge insulation, dual-system designs, latency/control-rate constraints (RTC)",
      "The survey map: action-tokenization perspective as your organizing frame",
    ],
    prereqs: [{ id: "l11-act", tier: "gold" }, { id: "l4-clip-contrastive", tier: "gold" }],
    hours: 6,
    primary: { resourceId: "awesome-vla-2026", sections: "Survey 2507.01925 (action-tokenization perspective); STUDY as the map; the index for everything else" },
    equations: ["\\pi_\\theta(a_{t:t+H} \\mid I_{1..k}, \\ell, q_t)"],
    exercises: [
      "Draw the generic-VLA block diagram from memory; then annotate where π0, OpenVLA, GR00T each deviate",
      "Latency budget exercise: 3-camera 224² inputs at 50 Hz control. Where does the time go? (why chunking + async inference exist)",
    ],
    masteryGate: "gold",
    masteryTest: "Whiteboard reconstruction: the full VLA anatomy with tensor shapes at every arrow for a π0-class model, plus a filled 'design axes' table (tokenization × head × co-training) for 5 named systems.",
    diagnostic: "Why keep the VLM close to its language pretraining? Name the three action-representation families and one system using each.",
    paperIds: ["paper-vla-survey"],
  },
  {
    id: "l12-rt-lineage",
    level: 12,
    title: "RT-1 → RT-2 → OXE: The Founding Line",
    track: "core",
    labs: ["embodied"],
    why: "RT-2's move, a VLM whose output tokens ARE motor commands, is the founding idea of the field you're entering. OXE made scale collaborative. Read the history that everything since is answering.",
    objectives: [
      "RT-1: the first robot transformer at fleet scale (skim-level)",
      "RT-2: co-fine-tuning a VLM on web + robot data; action-as-token; emergent transfer",
      "Open X-Embodiment: 22 embodiments, the cross-embodiment bet, what RT-X showed",
    ],
    prereqs: [{ id: "l12-vla-anatomy" }],
    hours: 3,
    primary: { resourceId: "awesome-vla-2026", sections: "RT-2 (2307.15818) READ; RT-1 + OXE (2310.08864) SKIM" },
    exercises: ["Write the one-page 'RT-2 in my own words' memo: what transferred from the web, what couldn't, and why discretized actions were both the enabler and the bottleneck"],
    masteryGate: "silver",
    masteryTest: "Defend RT-2 to a skeptic: three concrete evidences of web-knowledge transfer, and the two costs (action fidelity, inference rate) that later systems paid down.",
    diagnostic: "What does 'de-tokenize to actions' mean mechanically? What did OXE show about cross-robot data?",
    paperIds: ["paper-rt2", "paper-oxe"],
  },
  {
    id: "l12-openvla-code",
    level: 12,
    title: "OpenVLA: Reading a Whole VLA Codebase",
    track: "code",
    labs: ["embodied", "code"],
    why: "The best READABLE open VLA implementation (7B, DINOv2+SigLIP→Llama-2). You don't fine-tune it (superseded; 27 GB LoRA floor); you read it end-to-end, which is how repository-literacy for the research phase gets built.",
    objectives: [
      "Trace input→output through the actual code: image processing, prompt template, action tokenizer, decoding",
      "Training loop anatomy: data mixing, loss masking, checkpointing at scale",
      "OFT's lesson (skim): why continuous heads + chunking beat token-by-token decoding",
    ],
    prereqs: [{ id: "l12-vla-anatomy", tier: "gold" }],
    hours: 6,
    primary: { resourceId: "openvla-repo", sections: "Full-repo guided read: prismatic backbone → action tokenizer → train.py; OFT README for the delta" },
    exercises: [
      "Produce the repo map: every directory's job in one line each; the 10 most load-bearing files ranked",
      "Find where the 256-bin action discretization lives; compute what resolution 256 bins gives a normalized gripper DOF",
    ],
    masteryGate: "gold",
    masteryTest: "The whiteboard walkthrough: from a camera image to a 7-DOF action, file-by-file, function-by-function, from your notes, the repository-reading skill certified.",
    diagnostic: "Where do vision features enter the LLM? Why did OFT's L1-regression head beat autoregressive tokens on LIBERO?",
    paperIds: ["paper-openvla", "paper-openvla-oft"],
  },
  {
    id: "l12-pi0-flow",
    level: 12,
    title: "π0 & π0.5: Flow-Matching VLAs",
    track: "core",
    labs: ["embodied"],
    why: "The center-of-gravity lineage: π0's flow action expert (your l11-flow-matching, industrialized) and π0.5's co-training recipe for open-world generalization. These two papers + FAST are the spine's core.",
    objectives: [
      "π0 architecture: PaliGemma VLM + action expert; the flow head over 50-step chunks",
      "FAST: DCT+BPE action tokenization, and when discrete wins (autoregressive pretraining, 5× cheaper)",
      "π0.5: heterogeneous co-training (web + cross-embodiment + verbal instructions), hierarchical inference, knowledge insulation",
    ],
    prereqs: [{ id: "l11-flow-matching", tier: "gold" }, { id: "l12-vla-anatomy", tier: "gold" }],
    hours: 6,
    primary: { resourceId: "openpi", sections: "π0 (2410.24164) + FAST (2501.09747) + π0.5 (2504.16054) READ deep, with the openpi source open beside the papers" },
    equations: ["a \\sim \\text{flow}(a^{\\tau}, o, \\ell)\\;\\text{over } a_{t:t+50}"],
    exercises: [
      "Diff π0 vs your PushT flow policy: list every scale-up decision (backbone, conditioning, chunk length, data) in a table",
      "Explain FAST's DCT step to a rubber duck: why cosine-transform actions before BPE?",
    ],
    masteryGate: "gold",
    masteryTest: "Reconstruct π0.5's training-data mixture diagram and inference hierarchy from memory, and defend (with paper evidence) the claim 'co-training breadth, not robot-data volume, drove open-world generalization'.",
    diagnostic: "Why a separate action expert instead of action tokens in the VLM? What does knowledge insulation protect, concretely?",
    paperIds: ["paper-pi0", "paper-fast", "paper-pi05"],
  },
  {
    id: "l12-action-tokenization",
    level: 12,
    title: "Action Representation Deep-Dive",
    track: "core",
    labs: ["embodied", "ml"],
    why: "The design axis that most differentiates 2026 systems: FAST tokens vs flow experts vs L1 regression vs RVQ vs (rising) discrete diffusion. You implement a mini-FAST to make the tradeoffs concrete.",
    objectives: [
      "The full menu with costs: fidelity, inference rate, pretraining compatibility, cross-embodiment",
      "FAST mechanics: normalize → DCT → quantize → BPE; compression ratios measured",
      "Where the field is probing next: discrete-diffusion heads, latent actions (UniVLA/ViLLA)",
    ],
    prereqs: [{ id: "l12-pi0-flow", tier: "gold" }, { id: "l4-rope-tokenization" }],
    hours: 4,
    primary: { resourceId: "openpi", sections: "FAST paper §method + tokenizer code; survey 2507.01925 as the taxonomy" },
    implementation: "Mini-FAST on your PushT action chunks: DCT → quantize → BPE; report tokens-per-chunk vs naive binning; round-trip reconstruction error plot.",
    exercises: ["Reconstruct actions from truncated token sequences: quantify the graceful (or not) degradation"],
    masteryGate: "gold",
    masteryTest: "Your mini-FAST achieving >3× compression over per-dim binning at acceptable reconstruction error, plus the one-page 'which action representation for which regime' decision memo.",
    diagnostic: "Why does DCT help before BPE (what structure does it expose)? When do discrete tokens beat flow, despite the fidelity cost?",
  },
  {
    id: "l12-smolvla-finetune",
    level: 12,
    title: "SmolVLA: Your First VLA Fine-Tune",
    track: "core",
    labs: ["embodied"],
    why: "The consumer-GPU VLA (450M, trains on one modest card): the first foundation-model fine-tune where YOU run the whole loop (data, training, evaluation). The warm-up for the openpi capstone.",
    objectives: [
      "SmolVLA architecture (compact VLM + flow expert + async inference) read from its readable source",
      "Fine-tune on a LeRobot dataset; monitor with your W&B discipline",
      "Evaluate properly: LIBERO or sim task with your l11 statistics protocol",
    ],
    prereqs: [{ id: "l12-vla-anatomy", tier: "gold" }, { id: "l11-lerobot", tier: "gold" }],
    hours: 8,
    primary: { resourceId: "lerobot", sections: "SmolVLA docs + official training-smolvla notebook (documented: ~20k steps ≈ 4 h on A100; fits 16 GB at BS≤8, 12 GB at BS≤4/frozen vision)" },
    implementation: "Fine-tune smolvla_base on a chosen sim dataset; evaluate ≥50 episodes with CIs; compare against your from-scratch DP on the same task, the 'does pretraining help at my scale' experiment.",
    exercises: ["Ablate: fine-tune with vision encoder frozen vs unfrozen at fixed compute and report the tradeoff"],
    masteryGate: "gold",
    masteryTest: "A complete fine-tune report: config, curves, ≥50-episode CI'd evaluation, the DP comparison, and one architecture observation from reading its source.",
    diagnostic: "What did VLM pretraining buy at 450M scale on YOUR task, and what didn't it buy? (Answer from your own numbers.)",
    paperIds: ["paper-smolvla"],
    computeNote: "16 GB local comfortable; 12 GB at reduced batch; cloud A100 ≈ $5–15 if needed.",
  },
  {
    id: "l12-cross-embodiment",
    level: 12,
    title: "Cross-Embodiment & Generalist Systems",
    track: "core",
    labs: ["embodied"],
    why: "The open mechanism question of 2026: motion transfer (Gemini) vs soft prompts (X-VLA) vs latent actions (UniVLA) vs RVQ spaces (RDT2), with no agreed winner. Plus the GR00T dual-system + data-pyramid design, and the GEN-0 scaling claims to read critically.",
    objectives: [
      "The transfer-mechanism taxonomy with one named system per cell",
      "GR00T N1.x: dual-system, synthetic-data flywheel (DreamGen), humanoid framing",
      "Scaling-law claims (GEN-0's ~7B threshold): what would make them credible; what's unaudited",
    ],
    prereqs: [{ id: "l12-pi0-flow" }],
    hours: 3,
    primary: { resourceId: "isaac-groot", sections: "GR00T N1 paper (2503.14734) SKIM+; Gemini Robotics 1.5 report (2510.03342) SKIM; GEN-0 blog read critically" },
    exercises: ["Write the skeptic's memo on GEN-0's scaling claims: what's shown, what's inferred, what experiment would falsify the 7B threshold"],
    masteryGate: "silver",
    masteryTest: "The taxonomy table from memory + a defensible 5-minute answer to 'does robot data transfer across bodies, and via what mechanism?'",
    diagnostic: "What is motion transfer (mechanically)? Why might latent actions transfer where raw actions can't?",
    paperIds: ["paper-groot", "paper-gemini-robotics"],
  },
  {
    id: "l12-vla-eval",
    level: 12,
    title: "VLA Evaluation & The Saturation Crisis",
    track: "research",
    labs: ["embodied"],
    why: "LIBERO ≥97% while LIBERO-Plus perturbations collapse the same models below 30%. The eval crisis is the field's soft underbelly and your cheapest research doorway. You run the evaluations yourself.",
    objectives: [
      "The LIBERO protocol run hands-on (400 episodes via lerobot-eval); its saturation understood",
      "Robustness deltas: what perturbation studies reveal about memorization vs understanding",
      "The 2026 eval stack: SimplerEnv (frozen), RoboArena (real, distributed), Ai2 harness, neural-sim eval (RoboWorld ρ=0.97)",
    ],
    prereqs: [{ id: "l11-eval-statistics", tier: "gold" }, { id: "l12-smolvla-finetune", tier: "gold" }],
    hours: 4,
    primary: { resourceId: "vla-eval-harness", sections: "Run one released checkpoint through a benchmark; LIBERO + LIBERO-Plus results read side-by-side" },
    exercises: ["Perturb your own SmolVLA eval (camera jitter, initial-state shift): produce your own miniature LIBERO-Plus and its collapse curve"],
    masteryGate: "gold",
    masteryTest: "Your perturbation study: baseline vs 3 perturbation types, CIs, and the one-page 'what my policy actually learned' analysis, a genuine (small) research artifact.",
    diagnostic: "Why can a 97% LIBERO score coexist with brittleness? What makes real-world eval so expensive that RoboArena had to be invented?",
    paperIds: ["paper-libero", "paper-roboarena"],
  },
  {
    id: "l12-rl-vla",
    level: 12,
    title: "RL × VLA: Learning From Experience",
    track: "core",
    labs: ["embodied"],
    why: "The defining 2025–26 development: policies that improve from their own rollouts. RECAP (advantage conditioning), SimpleVLA-RL (GRPO on VLAs), πRL (RL through flow heads). Your PPO/IQL spine is exactly what makes these papers readable.",
    objectives: [
      "RECAP: value function from mixed experience → advantage-conditioned policy (the IQL through-line)",
      "SimpleVLA-RL: sparse success rewards + GRPO-style updates at scale; the 1-demo cold-start result",
      "πRL's two-layer MDP: how RL gradients pass through a flow action expert",
      "What's runnable at your scale (checkpoint evals; QueST-scale RIPT) vs cluster-only",
    ],
    prereqs: [{ id: "l10-ppo", tier: "gold" }, { id: "l10-offline-iql" }, { id: "l12-pi0-flow", tier: "gold" }],
    hours: 4,
    primary: { resourceId: "openpi", sections: "RECAP (2511.14759) READ; SimpleVLA-RL (2509.09674) READ + code-walk; πRL (2510.25889) formulation study; RL4VLA (2505.19789) as the controlled experiment" },
    exercises: ["Map each paper onto your spine: which l10 concept does each reuse? Produce the 2-column table (their trick ↔ your implementation)"],
    masteryGate: "gold",
    masteryTest: "The seminar test: present the RL-from-experience work in 15 minutes to a camera, covering methods, evidence, compute realities, and the two open problems you'd attack with one GPU.",
    diagnostic: "Why sparse binary rewards for VLA-RL? What does advantage conditioning avoid vs full policy-gradient fine-tuning?",
    paperIds: ["paper-recap", "paper-simplevla-rl", "paper-rl4vla"],
  },
  {
    id: "boss-vla",
    level: 12,
    title: "BOSS: VLA",
    track: "project",
    labs: ["embodied"],
    why: "The handover's VLA Boss: reproduce a meaningful component/result of a modern VLA system, the capstone fine-tune on the frontier lineage, evaluated like a researcher.",
    objectives: ["The program's flagship technical artifact before the research month"],
    prereqs: [
      { id: "l12-smolvla-finetune", tier: "gold" },
      { id: "l12-pi0-flow", tier: "gold" },
      { id: "l12-vla-eval", tier: "gold" },
      { id: "l12-openvla-code" },
    ],
    hours: 12,
    masteryGate: "gold",
    masteryTest: "24 GB path: LoRA-fine-tune π0 (openpi, documented >22.5 GB) on LIBERO or a chosen LeRobot dataset; evaluate with the 400-episode protocol + your perturbation suite; reproduce one paper-claimed number within tolerance; report deviations honestly. 16/12 GB path: the same study on SmolVLA + one cloud A100 π0.5-PEFT run (≈$10–30). Deliverable: reproduction-grade report (setup, config, results table with CIs, deviations, failure gallery) + reusable eval scripts. Passing = the report would survive a lab-meeting grilling.",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    exercises: [],
    projectIds: ["p19-vla-reproduction"],
    computeNote: "Documented floors: π0-LoRA >22.5 GB (RTX 4090-class); inference >8 GB; cloud fallback ≈$10–30.",
  },
];
