import type { SkillNode } from "@/lib/types";

export const L13_NODES: SkillNode[] = [
  {
    id: "l13-wm-concepts",
    level: 13,
    title: "World Models: The Idea & The Split",
    track: "core",
    labs: ["embodied", "ml"],
    why: "Can an agent predict consequences before acting? The 2026 field splits into two live bets: latent/JEPA (LeCun/AMI, V-JEPA) vs generative-video (Dreamer 4, Genie 3, Cosmos), and you must be able to argue both.",
    objectives: [
      "The V-M-C decomposition (Ha & Schmidhuber): vision, memory/dynamics, controller",
      "Latent vs generative prediction: what each buys and costs",
      "The four world-action-model paradigms (2026 tutorial framing)",
      "The taxonomy: WMs as policies, planners, evaluators, data factories",
    ],
    prereqs: [{ id: "l10-mdp", tier: "gold" }, { id: "l4-transformer", tier: "gold" }],
    hours: 4,
    primary: { resourceId: "dreamerv3-repo", sections: "Ha & Schmidhuber 'World Models' (1803.10122) READ + WAM tutorial (2607.00836) READ first; WM survey (2605.00080) as the map" },
    exercises: ["Write the two-column brief: 'latent bet vs generative bet', covering champions, evidence, failure modes, and what result would settle it"],
    masteryGate: "gold",
    masteryTest: "Argue each side of the VLA-vs-world-model debate for 5 minutes to a camera, citing specific 2025–26 systems as evidence, then state your own position and its falsifier.",
    diagnostic: "What does 'training inside the dream' mean? Why might predicting pixels be wasteful, and when is it exactly right?",
    paperIds: ["paper-worldmodels", "paper-wam-tutorial", "paper-wm-survey"],
  },
  {
    id: "l13-dreamer",
    level: 13,
    title: "Dreamer: RSSM & Imagination Training",
    track: "core",
    labs: ["embodied", "ml"],
    why: "The reproducible core of model-based RL: learn latent dynamics (RSSM), then train the actor-critic purely in imagination. Nature-published, single-GPU runnable, and the recipe Dreamer 4 scaled to Minecraft-diamonds-from-offline-data.",
    objectives: [
      "RSSM: deterministic + stochastic latent state; reconstruction/reward/continue heads",
      "Imagination rollouts: why gradients through the model help; λ-returns in latent space",
      "DreamerV3's robustness tricks (symlog, two-hot) at recognition level; Dreamer 4's delta (tokenizer + shortcut-forced diffusion dynamics, offline)",
    ],
    prereqs: [{ id: "l13-wm-concepts" }, { id: "l10-sac", tier: "gold" }],
    hours: 6,
    primary: { resourceId: "dreamerv3-repo", sections: "DreamerV3 paper (2301.04104) READ + run the official repo on one control task; Dreamer 4 (2509.24527) READ (no official code, itself a teachable fact)" },
    equations: ["h_t = f(h_{t-1}, z_{t-1}, a_{t-1});\\;\\; z_t \\sim q(z_t \\mid h_t, x_t)", "\\max_\\pi \\mathbb{E}_{\\text{imag}}\\big[\\textstyle\\sum \\gamma^t r_t\\big]"],
    implementation: "Run DreamerV3 on a DMC task (single GPU, documented); log imagined vs real trajectories; inspect reconstruction quality over training.",
    exercises: ["Corrupt the reward head's capacity: watch imagination-trained behavior degrade. Model error becomes policy error, visibly"],
    masteryGate: "gold",
    masteryTest: "The RSSM diagram + training loop reconstructed from memory, the repo run producing a learning curve, and a paragraph on what Dreamer 4 changed and why offline mattered.",
    diagnostic: "Why a stochastic AND deterministic latent path? Where can imagination training go wrong (compounding model error)?",
    paperIds: ["paper-dreamerv3", "paper-dreamer4"],
    computeNote: "DreamerV3 small configs: 12 GB state-based / 24 GB vision; hours-scale runs.",
  },
  {
    id: "l13-tdmpc",
    level: 13,
    title: "TD-MPC2: Planning in Latent Space",
    track: "core",
    labs: ["embodied", "ml"],
    why: "The decoder-free counterpoint: no reconstruction, just a latent model good enough to PLAN through (MPC with learned dynamics, your l6-mpc completing its arc). One config across 104 tasks; runs on 12 GB.",
    objectives: [
      "Implicit world models: why skipping reconstruction can win",
      "CEM/MPPI planning through learned latent dynamics + value terminal",
      "The Dreamer-vs-TD-MPC2 design contrast internalized",
    ],
    prereqs: [{ id: "l13-wm-concepts" }, { id: "l6-mpc" }],
    hours: 5,
    primary: { resourceId: "tdmpc2-repo", sections: "Paper (2310.16828) READ + single-task run on walker-walk (12 GB documented); compare against released reference curves" },
    equations: ["a^{*} = \\arg\\max_{a_{0:H}} \\textstyle\\sum_h \\gamma^h \\hat r(z_h, a_h) + \\gamma^{H+1} \\hat V(z_{H+1})"],
    implementation: "TD-MPC2 on walker-walk from pixels; ablate planning horizon and CEM samples; reproduce the reference curve within tolerance.",
    exercises: ["Set horizon=1: TD-MPC2 collapses toward model-free. Measure it; connect to your MPC horizon study from L6"],
    masteryGate: "gold",
    masteryTest: "Reproduced reference performance + the horizon/samples ablation table + the one-page Dreamer-vs-TD-MPC2 comparison memo (when to prefer which).",
    diagnostic: "What does TD-MPC2 never predict that Dreamer does? Why does a value terminal make short horizons work?",
    paperIds: ["paper-tdmpc2"],
    computeNote: "12 GB documented minimum; budget a weekend on a 3090/4090.",
  },
  {
    id: "l13-video-wm",
    level: 13,
    title: "Video World Models & JEPA (The 2026 Wave)",
    track: "core",
    labs: ["embodied"],
    why: "The frontier layer: V-JEPA 2-AC controls real arms zero-shot from latent prediction; Cosmos/DreamDojo generate robot futures as data factories; Ctrl-World evaluates VLAs in imagination; Genie 3 makes playable worlds. Literacy here defines 'current' in 2026.",
    objectives: [
      "JEPA line: predict in representation space (I-JEPA→V-JEPA 2/2.1); the AC head + CEM control result",
      "Generative line: Cosmos 3 platform, DreamGen/DreamDojo data factories, Genie's latent actions",
      "WM-as-evaluator: Ctrl-World / RoboWorld (ρ=0.97 vs RoboArena), and when neural sims can rank policies",
      "Hallucination/coverage: the failure mode that gates all of it",
    ],
    prereqs: [{ id: "l13-wm-concepts" }, { id: "l12-vla-anatomy", tier: "gold" }],
    hours: 5,
    primary: { resourceId: "vjepa2", sections: "V-JEPA 2 (2506.09985) READ incl. the AC planning loop; Genie (2402.15391) READ for latent actions; Cosmos-Policy + DreamDojo + Ctrl-World SKIM with repos open" },
    exercises: ["Run V-JEPA 2 frozen-feature probing on your tabletop frames; read the AC planning code path end-to-end (no arm needed)"],
    masteryGate: "silver",
    masteryTest: "The landscape brief: a one-page map of 2026 video-WM systems (axis: latent↔generative × policy/planner/evaluator/data-factory) with one evidence-backed claim per quadrant.",
    diagnostic: "How does V-JEPA 2-AC act without ever generating pixels? Why are generative WMs currently better evaluators than planners?",
    paperIds: ["paper-vjepa2", "paper-genie", "paper-ctrl-world"],
  },
  {
    id: "l13-latent-actions",
    level: 13,
    title: "Latent Actions: Learning From Human Video",
    track: "core",
    labs: ["embodied"],
    why: "The route around the robot-data bottleneck: infer ACTIONS from action-free video (Genie's LAM → LAPA → UniVLA), then pretrain policies on humanity's videos. Egocentric mega-datasets (EgoDex, EgoVerse) made this the fastest-moving subfield.",
    objectives: [
      "The latent-action mechanism: VQ codebooks over frame transitions; IDM extraction",
      "LAPA/UniVLA results: what 30×-cheaper pretraining showed; task-centric latents",
      "DreamGen's pipeline: WM-generated video + IDM actions = synthetic trajectories",
    ],
    prereqs: [{ id: "l13-video-wm" }],
    hours: 4,
    primary: { resourceId: "awesome-vla-2026", sections: "Genie §LAM (re-read) + LAPA + UniVLA papers; DreamGen (2505.12705) pipeline SKIM" },
    exercises: ["Design (on paper, precisely) a latent-action learner for PushT from state-pairs only: losses, codebook, how you'd validate the latents mean something"],
    masteryGate: "silver",
    masteryTest: "The design doc above, reviewed against UniVLA's actual choices: where you converged, where you diverged, and what their ablations say about your divergences.",
    diagnostic: "Why can actions be inferred from video at all? What breaks if the latent-action codebook collapses?",
  },
  {
    id: "l13-wm-experiment",
    level: 13,
    title: "Project P20: Train Your Own World Model",
    track: "project",
    labs: ["embodied", "ml"],
    why: "The level's gate: a world model trained by you, used for something (planning or evaluation). DINO-WM (frozen features + latent dynamics + MPC) is the audited most-reproducible path on one GPU.",
    objectives: ["Full loop: dynamics model trained on offline data → MPC planning to goals → honest evaluation"],
    prereqs: [{ id: "l13-tdmpc", tier: "gold" }, { id: "l13-dreamer" }],
    hours: 8,
    primary: { resourceId: "dino-wm", sections: "Reproduce: PushT dataset + checkpoint → zero-shot MPC planning → retrain the dynamics head yourself" },
    implementation: "Primary: DINO-WM on PushT. Run their planning, then retrain dynamics on your own collected transitions; compare planning success yours-vs-theirs. Alternative: your own latent dynamics MLP over DINOv3 features + CEM planner, from scratch, same eval.",
    exercises: ["The money experiment: planning success vs dynamics-model training-set size (100→10k transitions), the data-hunger curve of model-based control"],
    masteryGate: "gold",
    masteryTest: "P20 accepted: working WM-planner with the data-hunger curve, a failure gallery (where the model hallucinates), and a half-page connecting your observations to the field's hallucination/coverage problem.",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    projectIds: ["p20-world-model"],
    computeNote: "Single-GPU end-to-end (documented); hours-scale training.",
  },
];
