import type { SkillNode } from "@/lib/types";

export const L14_NODES: SkillNode[] = [
  {
    id: "l14-reality-gap",
    level: 14,
    title: "The Reality Gap & Domain Randomization",
    track: "core",
    labs: ["embodied", "robotics"],
    why: "Sim-trained policies meet a world with different friction, latency, and lighting. Domain randomization (train across randomized physics so reality looks like one more sample) is the recipe that took policies from sim to real hands and legs.",
    objectives: [
      "Gap taxonomy: dynamics (mass/friction/latency/actuators) vs perception (lighting/texture) vs systematic modeling error",
      "DR done right: which parameters, what ranges, the robustness-vs-performance tradeoff",
      "The canon absorbed: Tobin DR, OpenAI ADR (curriculum over ranges), Rudin's massively-parallel recipe",
    ],
    prereqs: [{ id: "l10-parallel-rl", tier: "gold" }],
    hours: 5,
    primary: { resourceId: "reality-gap-survey", sections: "The 2026 Annual Reviews survey READ + Rudin (2109.11978) + ADR (1910.07113) papers" },
    implementation: "The DR ablation (the level's core experiment): train Go1/PushCube policies with and without friction+mass+latency randomization; evaluate BOTH under 10 perturbed-physics test conditions; the robustness gap quantified.",
    exercises: ["Push DR ranges to absurd width: watch task performance collapse. Find the sweet spot empirically and connect to ADR's automated answer"],
    masteryGate: "gold",
    masteryTest: "Your DR ablation table + the one-page 'DR design memo' for a new task (parameters, ranges, evidence-based reasoning).",
    diagnostic: "Why does DR work (the distribution argument)? Which gap does DR NOT fix (systematic modeling error)?",
    paperIds: ["paper-rudin", "paper-dr-tobin"],
  },
  {
    id: "l14-sim2sim",
    level: 14,
    title: "Sim2Sim: Transfer Discipline Without Hardware",
    track: "core",
    labs: ["embodied", "robotics"],
    why: "The audited no-hardware proxy for sim-to-real: train in GPU-parallel sim (Warp/MJX), deploy in vanilla CPU MuJoCo with different solver/timestep, the same transfer discipline (export, interface, validate) real labs run before touching a robot.",
    objectives: [
      "The Train → Play → Sim2Sim → (Sim2Real) pipeline as practiced (unitree_rl_gym pattern)",
      "Policy export (ONNX/TorchScript); observation/action interface contracts",
      "Teacher–student distillation: privileged teacher → deployable student (the rsl_rl pattern)",
    ],
    prereqs: [{ id: "l14-reality-gap" }],
    hours: 5,
    primary: { resourceId: "unitree-rl-gym", sections: "The sim2sim step studied; replicate the loop with YOUR Playground/ManiSkill policies replayed in vanilla MuJoCo" },
    implementation: "Export your trained Go1/PushCube policy; run it in plain MuJoCo at a different timestep with observation noise; measure the transfer gap; then close part of it with DR retraining.",
    exercises: ["Distill a state-privileged PushCube teacher into a student without object-state access (proprio+image only): the privileged-information pattern hands-on"],
    masteryGate: "gold",
    masteryTest: "The sim2sim report: transfer gap measured before/after DR, the distillation result, and the checklist you'd run before a REAL deployment (transferable verbatim to hardware someday).",
    diagnostic: "Why does changing the integrator/timestep count as a transfer test? What does the teacher know that the student can't?",
  },
  {
    id: "l14-real-systems",
    level: 14,
    title: "Real-System Literacy: Latency, Calibration, Safety",
    track: "core",
    labs: ["robotics", "embodied"],
    why: "The phenomena simulation hides: control latency, actuator backlash, sensor timestamps, emergency stops. Learned as literacy now so the optional hardware track (or any future lab) doesn't start from zero.",
    objectives: [
      "The latency budget of a real control loop (sense→infer→act) and why async inference/RTC exists",
      "Calibration debt: camera-to-robot extrinsics, joint offsets, and what drifts and how you'd know",
      "Safety basics: workspace limits, force limits, e-stops, the 'never fight the robot' rules",
      "Actuator reality: backlash, friction, thermal limits, and why sim actuators are lies",
    ],
    prereqs: [{ id: "l14-reality-gap" }],
    hours: 4,
    primary: { resourceId: "reality-gap-survey", sections: "Real-world sections + Tang et al. survey (2408.03539) case studies" },
    exercises: [
      "Inject 50/100/200 ms action latency into your sim policy loop: plot the degradation curve, the number that explains real-robot pain",
      "Write the bring-up checklist for a hypothetical SO-101 session (calibrate, limits, e-stop test, data sanity), reviewed against LeRobot's actual tutorial",
    ],
    masteryGate: "silver",
    masteryTest: "The latency study + bring-up checklist, plus correct answers to 'name three ways a policy that's perfect in sim dies on a real arm'.",
    diagnostic: "Where does latency enter the loop (three places)? Why do robot-camera extrinsics rot over time?",
  },
  {
    id: "l14-hil-serl",
    level: 14,
    title: "HIL-SERL: Real-Robot RL, In Sim",
    track: "core",
    labs: ["embodied"],
    why: "The bridge between your SAC and real-world practice: sample-efficient RL with human interventions and a learned reward classifier. LeRobot ships a sim variant (gym_hil), so the workflow is learnable with zero hardware and drops onto a real SO-101 later.",
    objectives: [
      "The HIL-SERL loop: demos → reward classifier → SAC + human corrections",
      "Why interventions accelerate (and de-risk) real RL",
      "Reward classifiers: training success detectors from labeled frames",
    ],
    prereqs: [{ id: "l10-sac", tier: "gold" }, { id: "l11-diffusion-policy", tier: "gold" }],
    hours: 4,
    primary: { resourceId: "lerobot", sections: "HIL-SERL docs + the gym_hil sim variant run end-to-end" },
    exercises: ["Train the reward classifier on your own labeled success/failure frames; measure its false positives, then reason about what a wrong reward model does to RL"],
    masteryGate: "silver",
    masteryTest: "gym_hil session completed with interventions, plus the memo: 'how RECAP industrialized this exact recipe' (corrections → value function → advantage conditioning).",
    diagnostic: "Why does a learned reward beat hand-coded rewards on real robots? What do human interventions do to the exploration problem?",
  },
  {
    id: "l14-hardware-path",
    level: 14,
    title: "Optional: The SO-101 Hardware Track",
    track: "project",
    labs: ["robotics", "embodied"],
    why: "Hardware is an experimental instrument, not the curriculum (handover §16). IF budget and curiosity align: the SO-101 (~$230/pair, the verified 2026 starter arm with no successor) makes teleop, data collection, and real fine-tuning tangible.",
    objectives: [
      "Assemble/calibrate SO-101 leader+follower; LeRobot bring-up",
      "Teleop data collection (50-episode dataset) with your l11 quality standards",
      "Fine-tune ACT/SmolVLA on YOUR data; evaluate on the real arm honestly",
    ],
    prereqs: [{ id: "l14-real-systems" }, { id: "l11-data-quality" }],
    hours: 8,
    optional: true,
    primary: { resourceId: "lerobot", sections: "il_robots tutorial end-to-end on real hardware (SO-ARM101 docs)" },
    exercises: ["Reproduce your sim policy-comparison ON the real arm at small scale: does the sim ranking hold? (a genuine mini-research result either way)"],
    masteryGate: "silver",
    masteryTest: "A real-robot dataset on the Hub + a trained policy achieving ≥50% on your chosen task + the sim-vs-real ranking observation written up.",
    diagnostic: "Skip freely: the 210-day core is simulation-complete by design; take this branch only if the money and time are genuinely spare.",
    computeNote: "~$230–280 hardware; training fits any 8–16 GB GPU.",
  },
];
