import type { SkillNode } from "@/lib/types";

export const L15_NODES: SkillNode[] = [
  {
    id: "l15-paper-reading",
    level: 15,
    title: "How to Read a Paper",
    track: "research",
    labs: ["embodied"],
    why: "Deliberately unlocked early (Month 2): the three-pass method plus an honest note system turns papers from intimidating PDFs into decomposable objects. Every ladder paper from here on uses this protocol.",
    objectives: [
      "Keshav's three passes: 10-min triage → 1-hr comprehension → deep re-derivation",
      "The paper-note template: claims, evidence, assumptions, questions, 'what would break this'",
      "Reading equations actively: every symbol named before moving on",
    ],
    prereqs: [{ id: "l3-mlp-numpy", tier: "gold" }],
    hours: 3,
    primary: { resourceId: "keshav-reading", sections: "The whole (short) paper, then apply to ResNet immediately" },
    exercises: ["Three-pass ResNet and Attention Is All You Need; publish your notes to your repo, the first entries of your research log"],
    masteryGate: "gold",
    masteryTest: "Pick any unread ladder paper: produce a pass-2 note (claims/evidence/questions) in under 90 minutes that a peer could learn from.",
    diagnostic: "What do you extract in pass 1 (five things)? When do you abort a paper?",
  },
  {
    id: "l15-lit-search",
    level: 15,
    title: "Literature Search & Citation Graphs",
    track: "research",
    labs: ["embodied"],
    why: "Research begins by knowing what exists. Semantic Scholar/arXiv/citation-chasing turn 'is this novel?' from anxiety into procedure, and the awesome-lists of 2026 (VLA, WM) are your curated entry points.",
    objectives: [
      "Backward/forward citation chasing; survey-first strategy",
      "Query craft on arXiv/Semantic Scholar; alerts for your directions",
      "Maintaining a personal bib with one-line 'why it matters' per entry",
    ],
    prereqs: [{ id: "l15-paper-reading" }],
    hours: 3,
    primary: { resourceId: "awesome-vla-2026", sections: "As the worked example of a curated map; build YOUR map from it" },
    exercises: ["Map one topic (e.g. action tokenization): 15 papers, organized as a tree from 2 roots, each with a one-liner, timeboxed to 3 hours"],
    masteryGate: "silver",
    masteryTest: "Given a claimed-novel idea (I supply three), find the closest prior work within 45 minutes each and characterize the actual delta.",
    diagnostic: "Forward vs backward citation search: when each? Where do 2026 robot-learning papers appear first?",
  },
  {
    id: "l15-repro-methodology",
    level: 15,
    title: "Reproduction Methodology",
    track: "research",
    labs: ["embodied"],
    why: "Running a repo is not research; reproducing a CLAIM is. The discipline (environment pinning, seed protocols, tolerance definitions, deviation logging) is what makes your results citable and your failures informative.",
    objectives: [
      "Reproduction tiers: run-the-demo → reproduce-the-number → reproduce-from-scratch",
      "Environment capture (versions, hardware, configs); tolerance: what counts as 'reproduced'",
      "The deviation log: every difference from the paper, recorded at decision time",
    ],
    prereqs: [{ id: "l15-paper-reading", tier: "gold" }, { id: "l4-experiment-craft" }],
    hours: 5,
    primary: { resourceId: "lerobot", sections: "Practice target: reproduce LeRobot's documented DP-on-PushT reference number with full protocol" },
    exercises: ["Write the reproduction plan for one Robot Learning Boss result BEFORE running it: exact claim, tolerance, budget, abort criteria"],
    masteryGate: "gold",
    masteryTest: "One completed reproduction-with-protocol: claim stated, tolerance pre-registered, result honest (hit or miss), deviation log complete.",
    diagnostic: "Why pre-register the tolerance? Name four reasons a faithful reimplementation still misses the paper's number.",
  },
  {
    id: "l15-experiment-design",
    track: "research",
    level: 15,
    title: "Controlled Experiments & Ablations",
    labs: ["embodied"],
    why: "The research method itself: hypothesis → independent variable → controls → measurement. Ablation (remove one component, measure the damage) is how the field assigns credit, and how your Month-7 claims will be earned.",
    objectives: [
      "Falsifiable hypotheses; independent/dependent variables; controls that actually control",
      "Ablation design: one axis at a time; interaction effects acknowledged",
      "Seeds/variance/cost planning; negative results as results",
    ],
    prereqs: [{ id: "l3-metrics-experiments", tier: "gold" }],
    hours: 5,
    primary: { resourceId: "cs285", sections: "Experimental-methodology discussions + HANDOVER §19 templates (in-app)" },
    exercises: ["Re-audit your CIFAR ablation with the formal template: was anything confounded? Redesign it properly and note what changes"],
    masteryGate: "gold",
    masteryTest: "Design (on the template) the full experiment plan for a chunk-size ablation: hypothesis, variables, controls, seeds, analysis plan, cost, executable as written by someone else.",
    diagnostic: "What makes a hypothesis falsifiable? Why is 'we changed 3 things and it improved' uninterpretable?",
  },
  {
    id: "l15-ablation-stats",
    level: 15,
    title: "Analysis, Statistics & Failure Forensics",
    track: "research",
    labs: ["embodied"],
    why: "Numbers become claims through analysis: CIs, seed distributions, per-condition breakdowns. Failure analysis (WATCH the rollouts) is where robot-learning insight lives.",
    objectives: [
      "Your l11 statistics applied to experiment grids; when differences are real",
      "Failure taxonomies: categorize rollout failures, count them, let the counts drive the next experiment",
      "Cherry-picking and its subtle forms (metric selection, seed selection, eval-set drift), self-audited",
    ],
    prereqs: [{ id: "l15-experiment-design", tier: "gold" }, { id: "l11-eval-statistics", tier: "gold" }],
    hours: 4,
    primary: { resourceId: "libero", sections: "Build a failure taxonomy from YOUR boss-study rollout videos" },
    exercises: ["Tag 50 failed rollouts from your PushT study into a taxonomy (≤6 categories); produce the Pareto chart; pick the next experiment it implies"],
    masteryGate: "gold",
    masteryTest: "The failure-forensics report on one of your studies: taxonomy, counts, exemplar clips, and the evidence-ranked list of next experiments.",
    diagnostic: "Why watch rollouts instead of only reading success rates? Name two subtle cherry-picks you are personally most at risk of.",
  },
  {
    id: "l15-writing",
    level: 15,
    title: "Research Writing",
    track: "research",
    labs: ["embodied"],
    why: "Writing is where thinking gets debugged. Claims-match-evidence discipline, honest limitation sections, figures that carry the argument, practiced now so the Month-7 report isn't your first attempt.",
    objectives: [
      "The empirical-paper skeleton (intro/method/experiments/limitations) internalized",
      "Figure craft: one message per figure; captions that stand alone",
      "Claim calibration: 'suggests' vs 'shows' vs 'proves' used honestly",
    ],
    prereqs: [{ id: "l15-repro-methodology" }],
    hours: 4,
    primary: { resourceId: "keshav-reading", sections: "Reverse-engineer 3 papers you admired: outline their argument structure paragraph-by-paragraph" },
    exercises: ["Rewrite your boss-study report in paper skeleton (4 pages, 4 figures); get one adversarial read (AI-as-reviewer with the tutor prompts) and revise"],
    masteryGate: "gold",
    masteryTest: "The 4-page workshop-style writeup of your best study to date, with every claim traceable to a figure/table and a limitations section that names the real weaknesses first.",
    diagnostic: "What belongs in a caption? Where do most junior writeups overclaim (two patterns)?",
  },
  {
    id: "l15-reproduction-project",
    level: 15,
    title: "Project P21: The Rigorous Reproduction",
    track: "project",
    labs: ["embodied"],
    why: "The Month-6 centerpiece (scoped by the audit: ONE rigorous component-level reproduction + one lighter eval-level check, not 'multiple full reproductions', which single-GPU reality forbids).",
    objectives: ["A reproduction report the community could rely on: code, metrics, deviations, failure analysis"],
    prereqs: [{ id: "l15-repro-methodology", tier: "gold" }, { id: "l12-smolvla-finetune", tier: "gold" }],
    hours: 10,
    implementation: "Choose ONE from the vetted menu (feasibility-verified in research phase): (a) OpenVLA-OFT's continuous-head>tokens claim at SmolVLA scale; (b) Diffusion-vs-flow inference-step tradeoff (extend your l11 study to a second task); (c) DINO-WM planning-success reproduction; (d) LIBERO-Plus robustness-collapse reproduction on your fine-tuned model. Plus one eval-level check of a released checkpoint against its claimed number.",
    exercises: ["Pre-register the whole plan (claim, tolerance, budget) in the app's experiment tracker before any GPU-hour is spent"],
    masteryGate: "gold",
    masteryTest: "P21 accepted: reproduction report (protocol, results vs claim with CIs, deviation log, failure analysis, 'what I'd tell the authors') + reusable repo. This is the strongest pre-research portfolio artifact in the program.",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    projectIds: ["p21-reproduction"],
    computeNote: "Fits 16–24 GB local + ≤$30 optional cloud, by design of the menu.",
  },
];
