import type { SkillNode } from "@/lib/types";

export const L16_NODES: SkillNode[] = [
  {
    id: "l16-direction",
    level: 16,
    title: "Choosing the Question",
    track: "research",
    labs: ["embodied"],
    why: "Month 7 rises or falls on scoping. One narrow, falsifiable, single-GPU-tractable question beats every grand vision. The app's idea inbox + scoring rubric (novelty, tractability, data, sim-feasibility, time-to-first-experiment) turns taste into procedure.",
    objectives: [
      "Score your accumulated research ideas on the §16 rubric; kill most of them cheerfully",
      "Verify tractability against the frontier map's ranked directions (evaluation, data-composition, action-representation, WM-as-evaluator, small-scale RL-finetuning...)",
      "A literature mini-map for the chosen direction (10 closest works, deltas named)",
    ],
    prereqs: [{ id: "l15-lit-search", tier: "gold" }, { id: "l15-ablation-stats", tier: "gold" }],
    hours: 5,
    primary: { resourceId: "awesome-vla-2026", sections: "Your direction's neighborhood, exhaustively; the app's Frontier Tracker open-problems list" },
    exercises: ["Write three candidate one-sentence questions; for each: the experiment that would answer it, its compute cost, and its closest prior work, then pick with the rubric"],
    masteryGate: "gold",
    masteryTest: "The direction memo: chosen question, why now, why you, why one GPU suffices, the falsifier, and the three papers you must not accidentally reinvent.",
    diagnostic: "What makes a question 'narrow enough'? (test: can the first experiment run this week?)",
  },
  {
    id: "l16-proposal",
    level: 16,
    title: "Hypothesis & Experiment Plan",
    track: "research",
    labs: ["embodied"],
    why: "The proposal is the contract with yourself: hypothesis, baseline, metrics, ablations, timeline, written before the first run so Month 7 executes instead of wanders.",
    objectives: [
      "One falsifiable hypothesis with a pre-registered success criterion",
      "Baseline selection (what existing method, at what scale, from whose code)",
      "The experiment ladder: E1 (this week, cheap) → E2 → E3 (stretch), each with abort criteria",
    ],
    prereqs: [{ id: "l16-direction", tier: "gold" }],
    hours: 6,
    primary: { resourceId: "cs285", sections: "HANDOVER §19 templates in-app: experiment plan, filled completely" },
    exercises: ["Adversarial self-review: the three most likely ways your E1 produces an uninterpretable result. Redesign against each"],
    masteryGate: "gold",
    masteryTest: "The full proposal on the template, including the pre-registered analysis plan and a timeline that survives contact with your actual GPU-hours budget.",
    diagnostic: "What is YOUR baseline and why is beating it meaningful? What result would make you abandon the direction by Day 190?",
  },
  {
    id: "l16-baseline",
    level: 16,
    title: "Baseline Reproduction & Infrastructure",
    track: "research",
    labs: ["embodied"],
    why: "Research debugging must isolate YOUR change, so the baseline must run clean first. Infrastructure built here (configs, eval harness, logging) is what makes the sprint's iterations cheap.",
    objectives: [
      "Baseline running at documented performance on your task (the P21 skills, applied)",
      "The experiment harness: one-command runs, seeded, tracked, evaluated identically every time",
      "Compute budget dashboarded: GPU-hours planned vs spent",
    ],
    prereqs: [{ id: "l16-proposal", tier: "gold" }],
    hours: 20,
    primary: { resourceId: "lerobot", sections: "Whatever your direction needs; the workbench earns its keep" },
    exercises: ["Freeze the eval: golden seeds + episodes committed before any treatment run exists"],
    masteryGate: "gold",
    masteryTest: "Baseline reproduced within pre-registered tolerance + the harness demonstrated: config-diff-only between baseline and treatment runs.",
    diagnostic: "Why must eval be frozen before treatments? What belongs in the run config vs the code?",
  },
  {
    id: "l16-experiment-sprint",
    level: 16,
    title: "The Experiment Sprint",
    track: "research",
    labs: ["embodied"],
    why: "The daily research loop, for real: hypothesize → run → measure → fail → learn → modify. Most days produce negative or murky results. The log discipline is what converts them into knowledge.",
    objectives: [
      "E1→E3 executed with the daily experiment-log ritual (the app enforces it in research mode)",
      "Ablations isolating YOUR contribution; seeds and CIs throughout",
      "Failure forensics driving iteration; scope adjusted by evidence, not hope",
    ],
    prereqs: [{ id: "l16-baseline", tier: "gold" }],
    hours: 50,
    primary: { resourceId: "wandb", sections: "Every run tracked; weekly research memos to yourself (template in-app)" },
    exercises: ["The mid-sprint review (Day ~195): evidence table so far, kill/pivot/push decision made explicitly on the record"],
    masteryGate: "gold",
    masteryTest: "≥15 logged experiments with the decision trail visible; at least one ablation isolating the contribution; the honest evidence table, whatever the verdict.",
    diagnostic: "What did you learn from your best FAILED experiment this week? (If nothing: the log discipline is broken; fix that first.)",
  },
  {
    id: "l16-writing-release",
    level: 16,
    title: "Report, Repository & Release",
    track: "research",
    labs: ["embodied"],
    why: "Research that isn't communicated reproducibly didn't happen. The final artifacts: a workshop-grade technical report and a repo a stranger can run, your first citable objects.",
    objectives: [
      "The technical report (6–8 pages): claims calibrated to evidence, limitations first-class, negative results presented properly",
      "The reproducible repo: pinned env, one-command experiments, seeds, README with exact result-regeneration steps",
      "A 5-minute recorded talk (the defense rehearsal)",
    ],
    prereqs: [{ id: "l16-experiment-sprint", tier: "gold" }, { id: "l15-writing", tier: "gold" }],
    hours: 25,
    primary: { resourceId: "keshav-reading", sections: "Your three admired papers as structural models; the in-app writing templates" },
    exercises: ["The reproducibility test: a clean machine (or container) regenerates your headline table from the README alone"],
    masteryGate: "gold",
    masteryTest: "Report + repo + talk shipped; the repo passes the clean-machine test; the report survives your own adversarial read with the claim-evidence audit table attached.",
    diagnostic: "Can a stranger regenerate Table 1 in under an hour? If not, it isn't done.",
  },
  {
    id: "boss-final",
    level: 16,
    title: "FINAL BOSS: The Research Defense",
    track: "research",
    labs: ["embodied"],
    why: "The program's end-state made concrete (handover §30–31): defend an original, rigorously-tested hypothesis like a researcher, because that is now what you are becoming.",
    objectives: ["The defense: present, withstand cross-examination, propose what's next"],
    prereqs: [{ id: "l16-writing-release", tier: "gold" }],
    hours: 14,
    masteryGate: "research",
    masteryTest: "The defense session (recorded, AI-as-committee using the tutor prompts, plus any human you can recruit): 15-minute presentation + 45 minutes of adversarial Q&A covering method, statistics, alternatives, and 'why should anyone care'; then the written next-experiments memo (what you'd do with 10× compute, and with 0× more). Pass = every claim defended or honestly conceded, and a credible research agenda coming out the other side.",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    exercises: [],
    projectIds: ["p22-original-research"],
  },
];
