import type { SkillNode } from "@/lib/types";

export const L2_NODES: SkillNode[] = [
  {
    id: "l2-algebra",
    level: 2,
    title: "Algebra Repair (Test-Out Loop)",
    track: "math",
    labs: ["math"],
    why: "Algebraic fluency is the #1 predictor of survival in calculus and probability. Repair it with diagnostics, not lectures, and patch only what's broken.",
    objectives: [
      "Fluent equation manipulation, factoring, fractions with variables",
      "Exponent and logarithm rules automatic (log rules = how loss functions are read)",
      "Systems of linear equations by hand",
    ],
    prereqs: [],
    hours: 14,
    primary: { resourceId: "khan-math", sections: "Algebra 1 Course Challenge (diagnose) → Algebra 2: rational exponents/radicals, logarithms, equations units" },
    backup: { resourceId: "pauls-notes", sections: "Algebra: Preliminaries + Solving Equations (if you hate video)" },
    equations: ["\\log(ab)=\\log a+\\log b", "a^{m/n}=\\sqrt[n]{a^m}", "\\log_b x = \\tfrac{\\ln x}{\\ln b}"],
    exercises: [
      "Take the Course Challenge cold; screenshot the diagnosis; drill ONLY failed skills",
      "Solve 20 mixed log/exponent equations under time pressure",
    ],
    masteryGate: "gold",
    masteryTest: "OpenStax Algebra & Trig chapter practice tests (equations, exponentials/logs) at ≥90% without notes.",
    diagnostic: "Khan Algebra 2 Course Challenge ≥85% → mark mastered, move on immediately.",
    misconceptions: ["'I was bad at math in school' usually means 'I have 12 specific gaps'. The diagnostic finds them; you are not re-taking school."],
  },
  {
    id: "l2-functions-graphs",
    level: 2,
    title: "Functions & Graphs",
    track: "math",
    labs: ["math"],
    why: "Machine learning IS function fitting. Composition, inverses and transformations are used on day one of calculus and every day after.",
    objectives: [
      "Function notation, domain/range, composition f∘g, inverses",
      "Graph transformations (shift/scale/reflect) read at sight",
      "Exponential/log/polynomial family shapes recognized instantly",
    ],
    prereqs: [{ id: "l2-algebra" }],
    hours: 10,
    primary: { resourceId: "khan-math", sections: "Algebra 2 'Transformations of functions' + Precalc 'Composite functions'" },
    equations: ["(f\\circ g)(x)=f(g(x))", "f^{-1}(f(x))=x"],
    exercises: [
      "Sketch (by hand, then verify in matplotlib): e^x, ln x, x², 1/x, sigmoid, and shifted/scaled variants",
      "Given graphs, recover the formula (10 reps)",
    ],
    masteryGate: "gold",
    masteryTest: "Decompose σ(Wx+b) into primitive transformations and sketch the effect of changing W and b, the exact skill of reading a neuron.",
    diagnostic: "Sketch y = 2e^{-(x-1)} + 3 without plotting; state domain/range of ln(x-2).",
  },
  {
    id: "l2-trig",
    level: 2,
    title: "Trigonometry for Rotation",
    track: "math",
    labs: ["math", "robotics"],
    why: "Every robot joint angle, every rotation matrix, every wave is sin/cos. You need the unit-circle view, not the triangle-torture view.",
    objectives: [
      "Unit circle definition; radians as the only unit",
      "sin/cos/tan graphs, amplitude/frequency/phase",
      "sin²+cos²=1; angle-sum formulas exist as lookups; atan2 understood",
    ],
    prereqs: [{ id: "l2-functions-graphs" }],
    hours: 6,
    primary: { resourceId: "khan-math", sections: "Algebra 2 Trigonometry unit + Precalc trig functions unit tests" },
    equations: ["\\sin^2\\theta+\\cos^2\\theta=1", "x = r\\cos\\theta,\\; y = r\\sin\\theta", "\\theta = \\operatorname{atan2}(y, x)"],
    exercises: [
      "Program a point orbiting a circle; then a 2-link arm's fingertip position from two angles (your first FK, in 15 lines)",
      "Why atan2 and not arctan(y/x)? Break arctan in all four quadrants",
    ],
    masteryGate: "gold",
    masteryTest: "Derive the 2D rotation of a point by angle θ from the unit circle (no memorization) and implement rotate(p, θ) with tests.",
    diagnostic: "Convert 150° to radians instantly; sketch sin(2x - π/2); compute atan2(-1, -1).",
  },
  {
    id: "l2-vectors",
    level: 2,
    title: "Vectors & Dot Products",
    track: "math",
    labs: ["math", "robotics"],
    why: "States, actions, observations, gradients, embeddings: everything in this field is a vector. The dot product (similarity, projection) is the single most-used operation in ML.",
    objectives: [
      "Vectors as arrows AND as data; addition/scaling geometrically",
      "Dot product: algebraic, geometric (|a||b|cosθ), and as similarity",
      "Norms and distances; unit vectors; projection of a onto b",
    ],
    prereqs: [{ id: "l2-functions-graphs" }],
    hours: 6,
    primary: { resourceId: "3b1b-linalg", sections: "Ch 1–2 (vectors, span), before anything computational" },
    backup: { resourceId: "vmls", sections: "Ch 1, 3 (+ Python companion notebooks)" },
    equations: ["a\\cdot b = \\sum_i a_i b_i = \\|a\\|\\|b\\|\\cos\\theta", "\\operatorname{proj}_b a = \\frac{a\\cdot b}{b\\cdot b}\\, b"],
    exercises: [
      "Implement dot, norm, cosine similarity, projection in NumPy; verify the cosθ identity numerically on random vectors",
      "Word-vector toy: rank 10 vectors by cosine similarity to a query",
    ],
    masteryGate: "gold",
    masteryTest: "Derive the projection formula from 'error ⟂ b' and implement it; explain why attention scores are dot products.",
    diagnostic: "When is a·b zero, negative, maximal? Prove ‖a‖ = √(a·a).",
  },
  {
    id: "l2-matrices",
    level: 2,
    title: "Matrices & Linear Systems",
    track: "math",
    labs: ["math"],
    why: "A matrix is a function that moves space. Every neural-network layer, every camera, every robot pose is one. This node builds the transformation view from the start.",
    objectives: [
      "Matrix × vector = transformed vector = mix of columns (both views)",
      "Matrix multiply = composition; why order matters; identity/inverse",
      "Solve small linear systems; singular vs invertible intuition",
    ],
    prereqs: [{ id: "l2-vectors" }],
    hours: 8,
    primary: { resourceId: "3b1b-linalg", sections: "Ch 3–8 (transformations, composition, determinant, inverse/column space)" },
    backup: { resourceId: "vmls", sections: "Ch 6–8, 10–11 in NumPy" },
    equations: ["(AB)_{ij}=\\sum_k A_{ik}B_{kj}", "A^{-1}A = I", "\\det(AB)=\\det A\\,\\det B"],
    exercises: [
      "Animate a square under 6 different 2×2 matrices (rotation, shear, scale, reflection, singular, composition); label each",
      "Solve a 3×3 system by hand once; then np.linalg.solve forever; explain what singular means when solve fails",
    ],
    masteryGate: "gold",
    masteryTest: "Given a picture of a transformed grid, write down the matrix. Given R(θ)S(2,1), predict the picture. Both directions, no tools.",
    diagnostic: "What does a determinant of 0 mean geometrically? Compute a 2×2 inverse by hand.",
    misconceptions: ["A matrix is not a 'table of numbers'. It is a linear map; the numbers are just its effect on basis vectors."],
  },
  {
    id: "l2-linear-maps",
    level: 2,
    title: "Basis, Rank, Projections & Least Squares",
    track: "math",
    labs: ["math", "ml"],
    why: "Least squares is your first real ML model and the ancestor of all training. Basis/rank explain what networks can and cannot represent.",
    objectives: [
      "Linear independence, span, basis, rank, column space/null space intuition",
      "Orthonormal bases; Gram–Schmidt once by hand",
      "Least squares as projection onto the column space; normal equations; pseudo-inverse",
    ],
    prereqs: [{ id: "l2-matrices" }],
    hours: 8,
    primary: { resourceId: "vmls", sections: "Ch 5 (independence/basis/Gram–Schmidt) + Ch 12–13 (least squares, data fitting), implemented in NumPy" },
    backup: { resourceId: "3b1b-linalg", sections: "Ch 9, 13 (dot products, change of basis)" },
    equations: ["\\hat{x} = (A^{\\top}A)^{-1}A^{\\top} b", "b - A\\hat{x} \\perp \\operatorname{col}(A)"],
    exercises: [
      "Fit a line, then a cubic, to noisy data via the normal equations, no libraries; compare to np.linalg.lstsq",
      "Show rank-deficiency breaking the normal equations; fix with pseudo-inverse",
    ],
    masteryGate: "gold",
    masteryTest: "Derive the normal equations from the orthogonality condition and use them to fit a polynomial, with derivation and code both from a blank page.",
    diagnostic: "Why is A^T A invertible iff A has independent columns? What does the residual being orthogonal to col(A) mean?",
  },
  {
    id: "l2-eigen-svd",
    level: 2,
    title: "Eigenvalues, Eigenvectors & SVD",
    track: "math",
    labs: ["math", "ml"],
    why: "Eigen-thinking explains stability (control), covariance (statistics), PCA, and why deep-network training explodes or dies. SVD is the master decomposition behind low-rank everything, including LoRA.",
    objectives: [
      "Av = λv geometrically; eigendecomposition of symmetric matrices",
      "Powers of A through eigenvalues (stability preview for control)",
      "SVD: rotate–stretch–rotate; singular values as importance; low-rank approximation",
    ],
    prereqs: [{ id: "l2-linear-maps" }],
    hours: 8,
    primary: { resourceId: "mml-book", sections: "Ch 4 §4.1–4.2, 4.4–4.5 (eigendecomposition → SVD → low-rank)" },
    backup: { resourceId: "mit-1806", sections: "Eigen lectures L21–22 + SVD L29 (or RES.18-010)" },
    equations: ["Av=\\lambda v", "A = U\\Sigma V^{\\top}", "A_k=\\sum_{i=1}^{k}\\sigma_i u_i v_i^{\\top}"],
    exercises: [
      "Image compression via truncated SVD: plot quality vs k; find the elbow",
      "Iterate x ← Ax for eigenvalues inside/outside the unit circle; connect to 'will this system blow up?'",
      "PCA on a 2D point cloud from scratch (covariance → eigenvectors → projection)",
    ],
    masteryGate: "gold",
    masteryTest: "Implement power iteration to find the top eigenvector; explain LoRA's ΔW = BA (rank-r) using the SVD picture of low-rank structure.",
    diagnostic: "Eigenvalues of a rotation matrix? Of a diagonal matrix? What does σ₁/σₙ (condition number) tell you?",
  },
  {
    id: "l2-derivatives",
    level: 2,
    title: "Derivatives & the Chain Rule",
    track: "math",
    labs: ["math", "ml"],
    why: "The chain rule is backpropagation, literally. Automatic differentiation is this node applied recursively. Master it here and Level 3's backprop derivation becomes bookkeeping.",
    objectives: [
      "Derivative as local slope AND as sensitivity multiplier",
      "Rules: power/product/quotient; CHAIN RULE until automatic",
      "e^x and ln x derivatives; implicit differentiation lightly",
      "Numerical derivatives (finite differences) as the universal checker",
    ],
    prereqs: [{ id: "l2-functions-graphs" }],
    hours: 10,
    primary: { resourceId: "3b1b-calculus", sections: "Ch 1–5 first (visual chain rule)" },
    backup: { resourceId: "pauls-notes", sections: "Calc I Derivatives: all rules + practice sets" },
    equations: ["\\frac{d}{dx}f(g(x)) = f'(g(x))\\,g'(x)", "f'(x)\\approx\\frac{f(x+h)-f(x-h)}{2h}"],
    exercises: [
      "30 chain-rule reps ending with σ(w·x+b) differentiated w.r.t. w, x, and b",
      "Write check_grad(f, df, x): finite-difference verification; you will reuse this for years",
    ],
    masteryGate: "gold",
    masteryTest: "Differentiate L = (y - σ(wx+b))² w.r.t. w and b by hand, then verify with your finite-difference checker. This IS a neuron's backward pass.",
    diagnostic: "d/dx of e^{3x²}, of ln(sin x), of 1/(1+e^{-x}), under 90 seconds total.",
  },
  {
    id: "l2-multivariable",
    level: 2,
    title: "Gradients, Jacobians & Hessians",
    track: "math",
    labs: ["math", "ml", "robotics"],
    why: "∇L points uphill; training walks downhill. The Jacobian is both backprop's bookkeeping and the robot-arm velocity map.",
    objectives: [
      "Partial derivatives; gradient as steepest-ascent vector; level sets",
      "Jacobian of vector-valued functions; multivariable chain rule as matrix product",
      "Hessian as curvature; directional derivatives",
    ],
    prereqs: [{ id: "l2-derivatives" }, { id: "l2-matrices" }],
    hours: 10,
    primary: { resourceId: "khan-multivariable", sections: "'Derivatives of multivariable functions' (gradient + Jacobian)" },
    backup: { resourceId: "mml-book", sections: "§5.1–5.7 (the ML-dialect consolidation, incl. Hessian)" },
    equations: [
      "\\nabla f = \\left[\\tfrac{\\partial f}{\\partial x_1},\\dots,\\tfrac{\\partial f}{\\partial x_n}\\right]^{\\top}",
      "J_{ij} = \\frac{\\partial f_i}{\\partial x_j}",
      "\\frac{\\partial}{\\partial x}f(g(x)) = J_f(g(x))\\,J_g(x)",
    ],
    exercises: [
      "Plot a 2D loss surface + its gradient field; walk downhill by hand for 5 steps",
      "Compute the Jacobian of polar→cartesian by hand; verify with finite differences",
      "Hessian eigenvalues at a saddle vs a bowl; visualize both",
    ],
    masteryGate: "gold",
    masteryTest: "For f(x) = ‖Ax - b‖², derive ∇f = 2Aᵀ(Ax-b) by components once, then by matrix calculus, and verify numerically. (Gradient descent on this = training linear regression.)",
    diagnostic: "Gradient of x·y at (2,3)? Jacobian shape of f: ℝ⁵→ℝ³? What does a negative Hessian eigenvalue mean?",
  },
  {
    id: "l2-integrals",
    level: 2,
    title: "Integration Essentials",
    track: "math",
    labs: ["math"],
    why: "Just enough integration to read continuous probability (∫p(x)dx = 1, expectations) and value functions. Technique-grinding is explicitly banned.",
    objectives: [
      "Integral as accumulated area / anti-derivative; FTC",
      "u-substitution; definite integrals",
      "Numerical integration (trapezoid) as the practical fallback",
    ],
    prereqs: [{ id: "l2-derivatives" }],
    hours: 5,
    primary: { resourceId: "pauls-notes", sections: "Calc I: antiderivatives, u-substitution, FTC" },
    backup: { resourceId: "3b1b-calculus", sections: "Ch 8–9" },
    skip: ["Trig substitution, partial fractions, volumes/arc length, all convergence-test machinery: weeks of effort ML never uses"],
    equations: ["\\int_a^b f(x)\\,dx = F(b)-F(a)", "\\int_{-\\infty}^{\\infty} p(x)\\,dx = 1"],
    exercises: ["Implement trapezoid integration; verify against exact answers; integrate a Gaussian numerically and discover ≈0.68 within ±1σ"],
    masteryGate: "silver",
    masteryTest: "Evaluate ∫x e^{x²} dx by substitution AND explain why 𝔼[X] = ∫x p(x) dx is 'weighted average, continuum edition'.",
    diagnostic: "∫₀¹ 3x² dx in your head; what is d/dx ∫₀ˣ f(t) dt?",
  },
  {
    id: "l2-probability",
    level: 2,
    title: "Probability & Bayes",
    track: "math",
    labs: ["math", "ml"],
    why: "Robotics IS applied probability: sensors lie, actions slip. Bayes' rule is the Kalman filter, the localization algorithm, and the learning rule, all in embryo.",
    objectives: [
      "Sample spaces, events, axioms; conditional probability",
      "Bayes' theorem used forwards and backwards; base-rate traps",
      "Independence; law of total probability",
    ],
    prereqs: [{ id: "l2-algebra" }],
    hours: 10,
    primary: { resourceId: "mit-1805", sections: "Probability reading: counting → conditional probability & Bayes → independence (psets in NumPy)" },
    backup: { resourceId: "seeing-theory", sections: "Chapters 1–2 as a visual warm-up" },
    equations: ["P(A\\mid B) = \\frac{P(B\\mid A)P(A)}{P(B)}", "P(B)=\\sum_i P(B\\mid A_i)P(A_i)"],
    exercises: [
      "Simulate the disease-test base-rate paradox; make the wrong intuition and the right answer both visible",
      "Monte-Carlo verify three conditional-probability puzzles you first solve by hand",
    ],
    masteryGate: "gold",
    masteryTest: "Solve a two-stage Bayes problem (noisy sensor, prior belief) by hand AND by simulation, matching to 2 decimals. This is a robot localization update in miniature.",
    diagnostic: "A test is 99% accurate, disease hits 1/1000. P(sick | positive)? Estimate, then compute.",
    misconceptions: ["P(A|B) ≠ P(B|A). Confusing them is the single most common quantitative error in science."],
  },
  {
    id: "l2-random-variables",
    level: 2,
    title: "Random Variables, Expectation & Gaussians",
    track: "math",
    labs: ["math", "ml"],
    why: "Losses are expectations. Policies are distributions. Sensor noise is Gaussian. This is the vocabulary in which every ML/robotics paper is written.",
    objectives: [
      "Discrete/continuous RVs, PMF/PDF/CDF",
      "Expectation, variance, covariance; linearity of expectation as a superpower",
      "Distribution zoo: Bernoulli, binomial, uniform, exponential, Gaussian",
      "LLN + CLT: why Gaussians are everywhere; why means of many rollouts stabilize",
    ],
    prereqs: [{ id: "l2-probability" }, { id: "l2-integrals" }],
    hours: 10,
    primary: { resourceId: "mit-1805", sections: "RVs → expectation/variance → distributions → joints/covariance → LLN/CLT" },
    equations: [
      "\\mathbb{E}[X]=\\sum_x x\\,p(x)\\;\\text{or}\\;\\int x\\,p(x)dx",
      "\\operatorname{Var}(X)=\\mathbb{E}[X^2]-\\mathbb{E}[X]^2",
      "p(x)=\\tfrac{1}{\\sigma\\sqrt{2\\pi}}e^{-(x-\\mu)^2/2\\sigma^2}",
    ],
    exercises: [
      "Empirically verify linearity of expectation on dependent variables (surprise!)",
      "Sum n uniforms for n=1,2,5,30 → watch the CLT emerge in histograms",
      "Fit a Gaussian to noisy sensor data by computing μ̂, σ̂",
    ],
    masteryGate: "gold",
    masteryTest: "Derive 𝔼 and Var of a Bernoulli and a uniform from definitions; simulate a 50-rollout policy evaluation twice and explain (with CLT) why success rates differ run-to-run, the eval-statistics insight this whole field just relearned.",
    diagnostic: "Var(aX+b)? 𝔼[X+Y] with X,Y dependent? Sketch a Gaussian and mark μ±σ mass.",
  },
  {
    id: "l2-stats-mle",
    level: 2,
    title: "Estimation & Maximum Likelihood",
    track: "math",
    labs: ["math", "ml"],
    why: "'Training a model' formally means maximum likelihood. Cross-entropy loss IS negative log-likelihood. See it here once and loss functions stop being arbitrary.",
    objectives: [
      "Likelihood vs probability; log-likelihood; MLE recipe (differentiate, set to zero)",
      "MLE for Bernoulli and Gaussian by hand",
      "Sampling variability; standard error; why more data narrows estimates",
    ],
    prereqs: [{ id: "l2-random-variables" }],
    hours: 8,
    primary: { resourceId: "mit-1805", sections: "Statistics reading: MLE + Bayesian updating classes" },
    equations: [
      "\\hat{\\theta}_{\\text{MLE}} = \\arg\\max_\\theta \\sum_i \\log p(x_i\\mid\\theta)",
      "\\text{minimizing cross-entropy} \\equiv \\text{maximizing likelihood}",
    ],
    exercises: [
      "Derive p̂ = k/n for coin flips from the likelihood; then μ̂, σ̂² for a Gaussian",
      "Plot the likelihood surface for 10 coin flips; watch it sharpen with 1000",
    ],
    masteryGate: "gold",
    masteryTest: "Show, on paper, that least-squares regression = MLE under Gaussian noise, and that logistic-regression cross-entropy = Bernoulli MLE. (You'll reuse this argument in every ML conversation for years.)",
    diagnostic: "Why maximize LOG likelihood? MLE of λ for exponential data?",
  },
  {
    id: "l2-optimization",
    level: 2,
    title: "Optimization & Gradient Descent",
    track: "math",
    labs: ["math", "ml"],
    why: "All of deep learning is 'follow the negative gradient with taste'. Build that taste on 2D problems where you can SEE the loss landscape.",
    objectives: [
      "Minima/maxima/saddles; convex vs non-convex intuition",
      "Gradient descent: step size effects (crawl/converge/oscillate/diverge)",
      "Momentum intuition; constrained optimization + Lagrange multipliers (conceptually)",
    ],
    prereqs: [{ id: "l2-multivariable" }],
    hours: 9,
    primary: { resourceId: "d2l", sections: "Ch 12.1–12.6 (convexity, GD, SGD, minibatch, momentum), run every code cell" },
    backup: { resourceId: "khan-multivariable", sections: "Lagrange-multiplier articles" },
    equations: ["\\theta_{t+1} = \\theta_t - \\eta\\,\\nabla L(\\theta_t)", "\\mathcal{L}(x,\\lambda)=f(x)+\\lambda g(x)"],
    exercises: [
      "Implement GD on ‖Ax-b‖² (uses your l2-multivariable gradient); plot trajectories for 5 learning rates on the loss surface",
      "Add momentum; show it escaping a ravine that plain GD zigzags through",
      "Solve one constrained problem via Lagrange and verify graphically",
    ],
    masteryGate: "gold",
    masteryTest: "From scratch: minimize the Rosenbrock function with GD+momentum, visualize the path, and explain every hyperparameter's effect from your own plots.",
    diagnostic: "What happens with η too large (show the inequality intuition)? Why does momentum help in ravines?",
  },
  {
    id: "boss-math",
    level: 2,
    title: "BOSS: Mathematics",
    track: "math",
    labs: ["math"],
    why: "Gate out of the bootloader: derive and implement, closed-book, the mathematical core everything else builds on.",
    objectives: ["Prove the math is load-bearing, not recognized"],
    prereqs: [
      { id: "l2-eigen-svd", tier: "gold" },
      { id: "l2-multivariable", tier: "gold" },
      { id: "l2-random-variables", tier: "gold" },
      { id: "l2-stats-mle", tier: "gold" },
      { id: "l2-optimization", tier: "gold" },
    ],
    hours: 8,
    masteryGate: "gold",
    masteryTest: "One sitting, closed book: (1) derive ∇‖Ax-b‖² and implement GD to solve it; (2) chain-rule a two-layer scalar network by hand and verify with finite differences; (3) MLE for a Gaussian from scratch; (4) power-iterate the top eigenvector and explain what it means; (5) Bayes update a sensor belief. All five in code + derivation pages.",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    exercises: [],
  },
];
