import type { SkillNode } from "@/lib/types";

export const L3_NODES: SkillNode[] = [
  {
    id: "l3-ml-framing",
    level: 3,
    title: "The Learning Problem",
    track: "core",
    labs: ["ml"],
    why: "Before any algorithm: what does it mean for a machine to learn from data, and how do we know it worked? Getting train/val/test right is the difference between science and self-deception.",
    objectives: [
      "Supervised learning as function fitting; features/labels/hypothesis class",
      "Train/validation/test splits: what each is FOR; leakage",
      "Loss as 'how wrong'; empirical risk; the generalization question",
    ],
    prereqs: [{ id: "l1-numpy" }, { id: "l2-functions-graphs" }],
    hours: 4,
    primary: { resourceId: "cs229-notes", sections: "Part I intro framing" },
    backup: { resourceId: "statquest", sections: "ML fundamentals + cross-validation videos" },
    exercises: [
      "Split a dataset three ways; deliberately leak the test set into normalization; measure the lie it produces",
      "Hand-fit a line to 10 points by eyeball; define and compute its MSE",
    ],
    masteryGate: "silver",
    masteryTest: "Explain to a rubber duck: why can a model score 99% on training data and be worthless, and name the three distinct ways your pipeline could be lying to you.",
    diagnostic: "What is the validation set for, precisely, and why does tuning on test data invalidate it?",
  },
  {
    id: "l3-linear-regression",
    level: 3,
    title: "Linear Regression From Scratch",
    track: "core",
    labs: ["ml"],
    why: "The E. coli of machine learning: every concept (loss, gradient, fit, generalization) appears here in its simplest living form, and you already derived its math in L2.",
    objectives: [
      "Model ŷ = Xw + b; MSE loss; closed-form vs gradient descent solutions",
      "Feature scaling and why GD needs it",
      "The MLE view (Gaussian noise ⇒ least squares)",
    ],
    prereqs: [{ id: "l3-ml-framing" }, { id: "l2-linear-maps" }, { id: "l2-optimization" }, { id: "l2-stats-mle" }],
    hours: 6,
    primary: { resourceId: "cs229-notes", sections: "Part I: linear regression, LMS" },
    equations: ["L(w)=\\tfrac{1}{n}\\|Xw-y\\|^2", "\\nabla_w L = \\tfrac{2}{n}X^{\\top}(Xw-y)"],
    implementation: "NumPy only: fit synthetic + one real dataset by (a) normal equations, (b) your own GD; overlay both fits; loss-curve plot.",
    exercises: [
      "Show GD diverging without feature scaling, converging with it",
      "Polynomial features: sweep degree 1→15, plot train vs val error, your first overfitting curve",
    ],
    masteryGate: "gold",
    masteryTest: "Blank file → working linear regression (both solutions) on unseen data, with the ∇L derivation on paper. No sklearn, no AI.",
    diagnostic: "Write ∇w MSE from memory; when do normal equations fail and what do you do?",
    projectIds: ["p2-linreg"],
  },
  {
    id: "l3-classification",
    level: 3,
    title: "Logistic Regression & Cross-Entropy",
    track: "core",
    labs: ["ml"],
    why: "Classification introduces probabilities-as-outputs and cross-entropy, the exact loss VLAs use for action tokens. Sigmoid/softmax intuition built here is used daily forever.",
    objectives: [
      "Sigmoid → probability; decision boundaries",
      "Cross-entropy from the Bernoulli MLE you already did",
      "Softmax for multi-class; logits vocabulary",
    ],
    prereqs: [{ id: "l3-linear-regression" }, { id: "l2-random-variables" }],
    hours: 6,
    primary: { resourceId: "cs229-notes", sections: "Part II: classification, logistic regression, GLM/MLE view" },
    backup: { resourceId: "statquest", sections: "Logistic regression + MLE videos" },
    equations: [
      "\\sigma(z)=\\tfrac{1}{1+e^{-z}}",
      "L=-\\tfrac{1}{n}\\sum_i [y_i\\log \\hat p_i + (1-y_i)\\log(1-\\hat p_i)]",
      "\\operatorname{softmax}(z)_i = e^{z_i}/\\textstyle\\sum_j e^{z_j}",
    ],
    implementation: "NumPy logistic regression with GD on a 2D dataset; plot the decision boundary evolving during training.",
    exercises: [
      "Derive ∂L/∂w for logistic regression. Discover it is the same (ŷ-y)x form as linear regression, and explain why",
      "Implement stable softmax (subtract max); break the naive version with large logits",
    ],
    masteryGate: "gold",
    masteryTest: "Derive the cross-entropy gradient by hand and implement multi-class softmax regression on a 3-class toy set, from scratch, boundary plotted.",
    diagnostic: "Why cross-entropy instead of MSE for classification (two reasons: statistical + gradient)?",
  },
  {
    id: "l3-sgd-optimizers",
    level: 3,
    title: "SGD, Momentum & Adam",
    track: "core",
    labs: ["ml"],
    why: "Nobody trains on full batches. Stochasticity, momentum, and adaptive step sizes are the practical physics of training. Learn their behavior on problems small enough to see.",
    objectives: [
      "Minibatch SGD: noise vs speed tradeoff; batch-size effects",
      "Momentum and RMS scaling; Adam assembled from both",
      "Learning-rate schedules (concept)",
    ],
    prereqs: [{ id: "l3-linear-regression" }],
    hours: 5,
    primary: { resourceId: "d2l", sections: "Ch 12.4–12.6 + Adam section" },
    equations: ["m_t=\\beta_1 m_{t-1}+(1-\\beta_1)g_t", "v_t=\\beta_2 v_{t-1}+(1-\\beta_2)g_t^2", "\\theta_t = \\theta_{t-1}-\\eta\\, \\hat m_t/(\\sqrt{\\hat v_t}+\\epsilon)"],
    implementation: "Implement SGD, SGD+momentum, Adam as interchangeable optimizer classes; race them on the same logistic-regression problem across batch sizes.",
    exercises: ["Plot loss curves for batch ∈ {1, 16, full}; explain the noise floor you observe"],
    masteryGate: "gold",
    masteryTest: "Write Adam from its update equations from memory and show it matching a reference implementation's trajectory on a fixed seed.",
    diagnostic: "What problem does each Adam term solve? Why bias correction?",
  },
  {
    id: "l3-generalization",
    level: 3,
    title: "Overfitting, Regularization & Bias/Variance",
    track: "core",
    labs: ["ml"],
    why: "The central drama of ML: memorizing vs generalizing. Every robot policy that aces LIBERO and collapses under a moved camera is this node at scale.",
    objectives: [
      "Bias/variance decomposition intuition; capacity vs data",
      "L2 regularization (weight decay) derived and applied; early stopping",
      "Reading learning curves like a clinician",
    ],
    prereqs: [{ id: "l3-classification" }],
    hours: 4,
    primary: { resourceId: "cs229-notes", sections: "Bias–variance + regularization chapters" },
    backup: { resourceId: "statquest", sections: "Bias/variance, ridge/lasso videos" },
    equations: ["L_{\\text{reg}} = L + \\lambda\\|w\\|^2"],
    exercises: [
      "Polynomial-degree sweep with and without L2: full train/val curve family, annotated",
      "Early stopping: find the val-loss minimum and show test error there vs at the end",
    ],
    masteryGate: "gold",
    masteryTest: "Given four unlabeled learning-curve plots, diagnose each (underfit/overfit/leak/fine) and prescribe the fix, then produce one example of each yourself.",
    diagnostic: "λ→∞ does what to the model? Why does more data reduce variance but not bias?",
  },
  {
    id: "l3-metrics-experiments",
    level: 3,
    title: "Metrics & Honest Experiments",
    track: "core",
    labs: ["ml"],
    why: "Accuracy lies under class imbalance; single runs lie under seed variance. This node installs the experimental hygiene the whole research arc depends on.",
    objectives: [
      "Precision/recall/F1/confusion matrix; when accuracy misleads",
      "Seed variance: mean±std over runs as the default report",
      "Baselines: always know what 'dumb' scores",
    ],
    prereqs: [{ id: "l3-classification" }],
    hours: 4,
    primary: { resourceId: "statquest", sections: "Confusion matrix, ROC/AUC, precision-recall videos" },
    exercises: [
      "Build a 95%-accurate classifier that is useless (1:20 imbalance); show precision/recall exposing it",
      "Train the same model with 5 seeds; report mean±std; watch a 'improvement' vanish inside the error bars",
    ],
    masteryGate: "gold",
    masteryTest: "Write the evaluation section for one of your toy models the way a careful paper would: metrics chosen with justification, baseline, seeds, and one explicit limitation.",
    diagnostic: "Design the metric for a grasp-success detector where failures are 1-in-50. Why not accuracy?",
  },
  {
    id: "l3-backprop-theory",
    level: 3,
    title: "Backpropagation, Derived",
    track: "core",
    labs: ["ml", "math"],
    why: "The one derivation you must own before frameworks are allowed to hide it. Backprop is the chain rule organized as bookkeeping over a graph, nothing more, and you prove that here.",
    objectives: [
      "Computational graphs; forward values, backward gradients",
      "The local-gradient × upstream-gradient rule; fan-out summation",
      "Vectorized backprop through Wx+b, activations, and MSE/CE losses",
    ],
    prereqs: [{ id: "l2-multivariable", tier: "gold" }, { id: "l3-sgd-optimizers" }],
    hours: 5,
    primary: { resourceId: "karpathy-z2h", sections: "v1 micrograd (build scalar autograd along with him)" },
    backup: { resourceId: "3b1b-nn", sections: "Classic ch 3–4 (backprop visually)" },
    equations: [
      "\\frac{\\partial L}{\\partial x} = \\frac{\\partial L}{\\partial y}\\cdot\\frac{\\partial y}{\\partial x}",
      "\\delta^{(l)} = (W^{(l+1)\\top}\\delta^{(l+1)})\\odot f'(z^{(l)})",
    ],
    implementation: "Micrograd-style scalar autograd: Value class with +, ×, tanh, backward(); train a 2-neuron net with it.",
    exercises: ["Draw the graph for L=(σ(wx+b)-y)² and annotate every edge's local gradient; verify against your finite-difference checker"],
    masteryGate: "gold",
    masteryTest: "On paper, backprop a 2-layer network (matrix form) from loss to all parameters; then make your scalar autograd reproduce the numbers on a tiny example.",
    diagnostic: "Why does a node used twice SUM its gradients? What is ∂L/∂W's shape for W (m×n)?",
    misconceptions: ["Backprop is not an approximation and not 'biologically mystical'. It is exact chain-rule bookkeeping."],
  },
  {
    id: "l3-mlp-numpy",
    level: 3,
    title: "MLP From Raw NumPy",
    track: "core",
    labs: ["ml"],
    why: "The rite of passage: a neural network where you wrote every line. After this, PyTorch is a convenience, not a mystery, and the Gold gate on autograd is honestly earned.",
    objectives: [
      "Forward pass: affine → nonlinearity → affine → softmax",
      "Backward pass: vectorized gradients for every parameter",
      "Training loop: minibatches, your Adam, accuracy tracking",
    ],
    prereqs: [{ id: "l3-backprop-theory", tier: "gold" }],
    hours: 8,
    primary: { resourceId: "karpathy-z2h", sections: "v3 makemore-MLP as companion (his tensor habits, your NumPy)" },
    implementation: "2-layer MLP on MNIST-class data (or make_moons→digits): forward, backward, train to >95%, all NumPy. Gradient-check every layer before training.",
    exercises: [
      "Break it five ways on purpose (lr too high, no scaling, dead ReLU init, wrong CE, transposed W) and recognize each failure signature",
      "Add L2 and early stopping; show the generalization gap closing",
    ],
    masteryGate: "gold",
    masteryTest: "Blank file → trained 2-layer MLP with gradient-checked backward pass, in one sitting. This node Gold-gates all of PyTorch.",
    diagnostic: "There is no skip here: everyone builds this once. (Prior deep-learning veterans: rebuild it in <90 min to certify.)",
    projectIds: ["p3-numpy-net"],
  },
];
