import type { SkillNode } from "@/lib/types";

export const L4_NODES: SkillNode[] = [
  {
    id: "l4-pytorch-tensors",
    level: 4,
    title: "PyTorch: Tensors & Autograd",
    track: "code",
    labs: ["ml", "code"],
    why: "You earned this: having built backprop by hand, autograd is now a familiar machine with a gas pedal. Tensors are NumPy arrays that remember their history and live on GPUs.",
    objectives: [
      "Tensor creation/dtype/device; NumPy bridge; GPU round-trips",
      "requires_grad, backward(), .grad, connected explicitly to your micrograd",
      "no_grad/detach; when graphs are freed",
    ],
    prereqs: [{ id: "l3-mlp-numpy", tier: "gold" }],
    hours: 6,
    primary: { resourceId: "pytorch-tutorials", sections: "Learn the Basics: Quickstart → Tensors → Autograd (typing everything)" },
    exercises: [
      "Recreate your finite-difference gradient check against autograd on 5 functions",
      "Time matmul CPU vs GPU across sizes; find the crossover point",
      "Recompute your L2 favorite: ∇‖Ax-b‖² via autograd and match it to your hand derivation",
    ],
    masteryGate: "gold",
    masteryTest: "Implement linear regression three ways in PyTorch (manual grads, autograd, nn.Linear+optim) producing identical losses on a fixed seed, and explain what each abstraction hid.",
    diagnostic: "What does loss.backward() do to leaf tensors? Why zero_grad()? What breaks if you forget detach in a logging line?",
  },
  {
    id: "l4-training-loop",
    level: 4,
    title: "The Training Loop, Owned",
    track: "code",
    labs: ["ml", "code"],
    why: "The five-line loop (forward, loss, zero, backward, step) is the beating heart of everything from MNIST to π0.5 fine-tuning. You will write it, instrument it, and never use a Trainer you couldn't rebuild.",
    objectives: [
      "nn.Module composition; parameters(); Dataset/DataLoader",
      "Full train/val loop with checkpointing and metric logging",
      "GPU training hygiene: .to(device), memory watching, seed control",
    ],
    prereqs: [{ id: "l4-pytorch-tensors" }],
    hours: 8,
    primary: { resourceId: "pytorch-tutorials", sections: "Data → Transforms → Build NN → Optimization → Save/Load" },
    implementation: "Reusable train.py skeleton: config dict, loop, val evaluation, best-checkpoint saving, CSV + W&B logging, the skeleton you will reuse all program.",
    exercises: [
      "Train your L3 MLP architecture in PyTorch; match NumPy accuracy; compare wall-clock",
      "Kill and resume training from a checkpoint mid-run; prove the curves continue without a break",
    ],
    masteryGate: "gold",
    masteryTest: "From a blank file, write a full training loop for a given model+dataset with validation, checkpointing and logging, no Lightning, no Trainer, no copying.",
    diagnostic: "Order these correctly and explain each: zero_grad, backward, step, forward, loss. What goes subtly wrong if step precedes backward?",
  },
  {
    id: "l4-training-dynamics",
    level: 4,
    title: "Why Training Breaks: Init, Norms, Activations",
    track: "core",
    labs: ["ml"],
    why: "The single best 'debugging deep learning' education in existence is watching activations and gradients flow, or die. Karpathy v4 is the definitive lecture; you reproduce its diagnostics.",
    objectives: [
      "Activation/gradient statistics as health monitors; dead ReLUs, saturation",
      "Initialization logic (fan-in scaling): why it matters, roughly derived",
      "BatchNorm/LayerNorm: what they fix, their train/eval duality, why transformers use LN",
    ],
    prereqs: [{ id: "l4-training-loop" }],
    hours: 6,
    primary: { resourceId: "karpathy-z2h", sections: "v4 'Activations & Gradients, BatchNorm'; reproduce every histogram" },
    equations: ["\\operatorname{Var}(w) = 2/n_{\\text{in}}\\;\\text{(He init, ReLU)}", "\\hat{x} = \\frac{x-\\mu}{\\sqrt{\\sigma^2+\\epsilon}}\\gamma + \\beta"],
    exercises: [
      "Instrument your MLP: per-layer activation/grad histograms across depth; show a bad init killing layer 5+",
      "Swap BatchNorm↔LayerNorm; explain the batch-dependence difference you observe",
    ],
    masteryGate: "gold",
    masteryTest: "I hand you a 6-layer net that trains to 40% then plateaus. Using only statistics plots, diagnose the (planted) init/norm bug and fix it, with the diagnostic writeup.",
    diagnostic: "Why does tanh saturate deep nets at bad init? What breaks BatchNorm at batch size 1 (and which robot-learning setting hits exactly that)?",
  },
  {
    id: "l4-cnn",
    level: 4,
    title: "Convolutions & CNNs",
    track: "core",
    labs: ["ml"],
    why: "Convolution = weight sharing over space, the inductive bias that made deep vision work. CNNs still encode half the robot policies in production, and ResNet's skip connection is load-bearing everywhere.",
    objectives: [
      "Convolution mechanics: kernels, stride, padding, channels; shape arithmetic fluent",
      "Pooling; receptive fields; feature hierarchies",
      "ResNet residual blocks: why identity shortcuts fix depth",
    ],
    prereqs: [{ id: "l4-training-loop" }],
    hours: 8,
    primary: { resourceId: "cs231n", sections: "CNN lectures (L5–6) + assignment CNN parts" },
    backup: { resourceId: "d2l", sections: "CNN chapters as alternate explanation" },
    equations: ["\\text{out} = \\lfloor (n + 2p - k)/s \\rfloor + 1", "y = F(x) + x \\;\\text{(residual)}"],
    exercises: [
      "Implement conv2d with loops on a 6×6 input by hand-check; then verify nn.Conv2d matches",
      "Compute output shapes for 10 conv stacks on paper before running (shape-arithmetic drill)",
      "Visualize first-layer filters and feature maps of a small trained CNN",
    ],
    masteryGate: "gold",
    masteryTest: "Design a CNN for 64×64 input under a parameter budget (<500k), predict every layer's shape and parameter count on paper, then verify, and train it to a sane accuracy.",
    diagnostic: "Params in Conv2d(16→32, k=3)? Why do 3×3 stacks beat 7×7? What exactly does stride 2 trade?",
    paperIds: ["paper-resnet"],
  },
  {
    id: "l4-classifier-project",
    level: 4,
    title: "Project P4: CIFAR-10 Classifier, Properly Run",
    track: "project",
    labs: ["ml"],
    why: "Your first full deep-learning experiment executed like a researcher: baselines, ablation, seed-aware reporting, W&B instrumented. The scientific habits matter more than the accuracy.",
    objectives: ["End-to-end: data pipeline, augmentation, ResNet-ish model, LR schedule, honest evaluation"],
    prereqs: [{ id: "l4-cnn" }, { id: "l4-training-dynamics" }, { id: "l4-experiment-craft" }],
    hours: 6,
    implementation: "CIFAR-10 to ≥90%: linear-probe baseline → small CNN → +augmentation → +schedule; every step one W&B run; final table mean±std over 3 seeds.",
    exercises: ["One deliberate ablation (remove augmentation OR normalization): quantify the damage properly"],
    masteryGate: "gold",
    masteryTest: "P4 accepted: repo + 1-page experiment report (table, curves, ablation, 3 seeds, one limitation).",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    projectIds: ["p4-classifier"],
    computeNote: "Any 8 GB GPU: ~10–30 min/run. CPU possible but slow.",
  },
  {
    id: "l4-embeddings-lm",
    level: 4,
    title: "Embeddings & Autoregressive Modeling",
    track: "core",
    labs: ["ml"],
    why: "Two ideas that power VLAs: symbols→vectors (embeddings) and predict-the-next-token (autoregression). Karpathy's makemore teaches both on a dataset small enough to fully understand.",
    objectives: [
      "Embedding tables as learned lookup; visualizing embedding space",
      "Autoregressive factorization P(x) = ∏ P(xᵢ|x<ᵢ); sampling from the model",
      "Context windows; train/val perplexity",
    ],
    prereqs: [{ id: "l4-training-loop" }],
    hours: 6,
    primary: { resourceId: "karpathy-z2h", sections: "v2 (bigram) + v3 (MLP language model); code along fully" },
    equations: ["P(x_{1:T}) = \\prod_t P(x_t \\mid x_{<t})"],
    exercises: [
      "Train makemore on a name corpus; sample names at temperatures 0.5/1.0/1.5 and explain the difference",
      "Plot the learned 2D character embeddings; find the vowel cluster",
    ],
    masteryGate: "gold",
    masteryTest: "Build a context-3 MLP language model from scratch on your own corpus, report perplexity, and explain precisely why 'action tokens' in RT-2 are this same machinery pointed at motors.",
    diagnostic: "Why does an embedding beat one-hot into a dense layer (two reasons)? What does temperature do to the softmax?",
  },
  {
    id: "l4-attention",
    level: 4,
    title: "Attention From a Blank File",
    track: "core",
    labs: ["ml"],
    why: "The mechanism of the decade. Queries, keys, values: content-based routing of information powers every VLA, world model, and LLM you will touch. You build it before you import it.",
    objectives: [
      "Q/K/V projections; scaled dot-product attention; why /√d",
      "Causal masking; multi-head as parallel subspace attention",
      "Attention-map reading; shapes traced at every step",
    ],
    prereqs: [{ id: "l4-embeddings-lm" }],
    hours: 8,
    primary: { resourceId: "3b1b-nn", sections: "Ch 6 Attention (BEFORE building)" },
    backup: { resourceId: "uva-notebooks", sections: "Tutorial 6 (after building; fills in encoder view, masking variants)" },
    equations: ["\\operatorname{Attn}(Q,K,V)=\\operatorname{softmax}\\!\\left(\\tfrac{QK^{\\top}}{\\sqrt{d_k}}\\right)V"],
    implementation: "Single-head attention from raw tensors with hand-verified shapes on a 4-token example; then batched multi-head causal attention as a clean nn.Module.",
    exercises: [
      "Hand-compute attention weights for a 3-token example on paper; match your code exactly",
      "Ablate the /√d scaling at d=256: show the softmax saturating and gradients dying",
      "Visualize causal-mask attention maps evolving over training",
    ],
    masteryGate: "gold",
    masteryTest: "Blank file → batched multi-head causal self-attention with correct masking, verified against nn.MultiheadAttention outputs. Shapes narrated aloud at every line.",
    diagnostic: "Shapes of Q,K,V for batch 8, 64 tokens, d=512, 8 heads, at every intermediate step? Why mask BEFORE softmax?",
    paperIds: ["paper-attention"],
  },
  {
    id: "l4-transformer",
    level: 4,
    title: "The Transformer, Built & Trained",
    track: "core",
    labs: ["ml"],
    why: "Assembly of everything so far: embeddings + attention + MLPs + LayerNorm + residuals = GPT. The architecture of π0, GR00T and Gemini Robotics, built, trained and debugged by you.",
    objectives: [
      "Pre-LN transformer block; residual stream mental model",
      "Positional information; the full decoder-only architecture",
      "Training on real text; loss curves, sampling, overfitting a tiny set as a sanity ritual",
    ],
    prereqs: [{ id: "l4-attention", tier: "gold" }],
    hours: 10,
    primary: { resourceId: "karpathy-z2h", sections: "v7 'Let's build GPT', twice: follow, then rebuild alone" },
    backup: { resourceId: "annotated-transformer", sections: "Once, for the encoder–decoder completion" },
    equations: ["x \\mathrel{+}= \\operatorname{MHA}(\\operatorname{LN}(x));\\quad x \\mathrel{+}= \\operatorname{MLP}(\\operatorname{LN}(x))"],
    implementation: "nanoGPT-style decoder-only transformer trained on Shakespeare; overfit 1 batch first (the debugging ritual), then full training with sampling checkpoints.",
    exercises: [
      "Parameter-count your model by hand from the config; verify against numel()",
      "Ablate residual connections at depth 6, watch training collapse; explain via gradient flow",
    ],
    masteryGate: "gold",
    masteryTest: "Rebuild the full GPT from memory in one sitting (aided only by shapes on paper), train to coherent Shakespeare, and answer the microgpt cold-read line-by-line.",
    diagnostic: "The microgpt exit exam: read Karpathy's ~200-line microgpt cold and explain every line's purpose. Pass = mastered.",
    paperIds: ["paper-attention", "paper-gpt2"],
    projectIds: ["p5-tiny-transformer"],
  },
  {
    id: "l4-rope-tokenization",
    level: 4,
    title: "Tokenizers & RoPE (2026 Defaults)",
    track: "core",
    labs: ["ml"],
    why: "BPE intuition transfers directly to ACTION tokenization (FAST compresses action sequences exactly like BPE compresses text). RoPE is the positional scheme every 2026 model uses.",
    objectives: [
      "BPE mechanics: merges, vocabulary, why subwords",
      "RoPE: rotating query/key pairs; relative-position property (working understanding)",
    ],
    prereqs: [{ id: "l4-transformer" }],
    hours: 4,
    primary: { resourceId: "karpathy-z2h", sections: "v8 tokenizer video (once, don't over-invest)" },
    backup: { resourceId: "labml", sections: "Annotated RoPE implementation; port into your GPT" },
    equations: ["\\text{RoPE: } q_m^{\\top} k_n = f(q, k, m-n)"],
    exercises: [
      "Run 200 BPE merges on a tiny corpus by hand-traceable code; inspect the vocabulary",
      "Swap your GPT's learned positional embeddings for RoPE; verify loss parity",
    ],
    masteryGate: "silver",
    masteryTest: "Explain to the camera: why discretizing robot actions into tokens (RT-2/FAST style) is 'just' tokenization, and what RoPE gives that absolute positions don't.",
    diagnostic: "Why does BPE handle unseen words? What does RoPE encode that sinusoidal doesn't (relative offsets in the dot product)?",
  },
  {
    id: "l4-vit",
    level: 4,
    title: "Vision Transformers",
    track: "core",
    labs: ["ml"],
    why: "Patches-as-tokens unified vision with language, the precondition for VLAs. Every robot-policy vision backbone you'll meet (SigLIP, DINO) is a ViT.",
    objectives: [
      "Patchify → linear embed → [CLS]/pooling → transformer encoder",
      "ViT vs CNN inductive bias; why small-data ViTs struggle",
      "Fine-tuning vs frozen-feature usage",
    ],
    prereqs: [{ id: "l4-transformer" }, { id: "l4-cnn" }],
    hours: 6,
    primary: { resourceId: "vit-pytorch", sections: "Read vit.py line-by-line, then train on CIFAR-10" },
    backup: { resourceId: "uva-notebooks", sections: "Tutorial 15 (honest about small-data ViT tricks)" },
    equations: ["N = HW/P^2\\;\\text{patches};\\; z_0=[x_{cls}; x_1E; \\dots; x_NE]+E_{pos}"],
    exercises: [
      "Patchify by hand with einops/reshape; verify patch count and dims for 224×224, P=16",
      "CIFAR bake-off: your CNN vs small ViT at matched params; explain the gap you find",
    ],
    masteryGate: "gold",
    masteryTest: "Implement patch embedding + ViT forward from scratch (reusing your transformer blocks) and train it; trace shapes 224×224→logits from memory.",
    diagnostic: "How many tokens does a 336×336 image at P=14 produce (and why does that number matter for VLA latency)?",
    paperIds: ["paper-vit"],
  },
  {
    id: "l4-clip-contrastive",
    level: 4,
    title: "CLIP, SigLIP & Contrastive Multimodality",
    track: "core",
    labs: ["ml", "embodied"],
    why: "How vision and language land in one space, the semantic substrate VLAs are built on. 'Frozen backbone + probe' practiced here is exactly how robot policies consume these models.",
    objectives: [
      "Contrastive objective: batch similarity matrix, temperature, symmetric CE",
      "Zero-shot classification via text prompts; SigLIP's sigmoid variant (why it scales)",
      "Linear probing frozen features; DINO-family self-supervised features (context)",
    ],
    prereqs: [{ id: "l4-vit" }],
    hours: 6,
    primary: { resourceId: "open-clip", sections: "Zero-shot inference + linear probe on frozen features" },
    equations: ["L = \\tfrac{1}{2}[\\operatorname{CE}(\\text{sim}/\\tau, I) + \\operatorname{CE}(\\text{sim}^{\\top}/\\tau, I)]"],
    exercises: [
      "Implement the CLIP loss on toy embeddings; verify the diagonal-target structure",
      "Zero-shot classify your own 20 images with prompt engineering; then beat it with a linear probe on 50 labels",
    ],
    masteryGate: "gold",
    masteryTest: "Build a tiny two-tower contrastive model on a synthetic paired dataset (shapes↔captions), train it, and demonstrate zero-shot transfer to unseen pairs.",
    diagnostic: "Why does contrastive need large batches (and how does SigLIP relax that)? What does temperature control?",
    paperIds: ["paper-clip", "paper-siglip", "paper-dinov3"],
  },
  {
    id: "l4-experiment-craft",
    level: 4,
    title: "Experiment Tracking & Ablation Craft",
    track: "research",
    labs: ["ml"],
    why: "From now on, every run is an experiment with a record. W&B + a config discipline turns 'I think it helped' into evidence. The research spine starts here, not in Month 6.",
    objectives: [
      "W&B (or CSV-hedged) run tracking: configs, metrics, artifacts",
      "One-variable-at-a-time ablations; naming and organizing runs",
      "Seeds: fixing them, and reporting across them",
    ],
    prereqs: [{ id: "l4-training-loop" }],
    hours: 3,
    primary: { resourceId: "wandb", sections: "Instrument your train.py: config, losses, histograms, system metrics" },
    exercises: ["Re-run your CIFAR pipeline as a 2×2 ablation grid (aug × schedule), tracked, with a comparison dashboard"],
    masteryGate: "silver",
    masteryTest: "Show me any experiment from last week and reproduce its exact numbers from the logged config in one command.",
    diagnostic: "What must be logged for a run to be reproducible six months later? (config, seed, code version, data version, env)",
  },
  {
    id: "boss-dl",
    level: 4,
    title: "BOSS: Deep Learning",
    track: "project",
    labs: ["ml"],
    why: "Gate out of Level 4: implement, train, and debug a transformer under adversarial conditions, the handover's DL Boss.",
    objectives: ["Certified: transformers are yours, including when they break"],
    prereqs: [
      { id: "l4-transformer", tier: "gold" },
      { id: "l4-vit", tier: "gold" },
      { id: "l4-training-dynamics", tier: "gold" },
    ],
    hours: 8,
    masteryGate: "gold",
    masteryTest: "Three-part sitting: (1) implement a specified small transformer variant from a written spec (blank file); (2) fix a sabotaged training run (three planted bugs: mask, LR, norm placement) using diagnostics only; (3) oral defense: trace shapes and gradients through your model from memory, then explain one design tradeoff (heads vs width) with evidence from a 30-minute experiment.",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    exercises: [],
  },
];
