import type { SkillNode } from "@/lib/types";

export const L5_NODES: SkillNode[] = [
  {
    id: "l5-frames-rotations",
    level: 5,
    title: "Frames & Rotation Matrices (SO(3))",
    track: "core",
    labs: ["robotics", "math"],
    why: "Robotics is the discipline of keeping track of where things are relative to other things. Wrong-frame bugs are the #1 practical error source in all of robotics. This node is the vaccine.",
    objectives: [
      "Coordinate frames; expressing a point in different frames",
      "Rotation matrices: orthonormal columns = axes of one frame in another; R∈SO(3)",
      "Composition order (world vs body); inverse = transpose",
    ],
    prereqs: [{ id: "l2-matrices" }, { id: "l2-trig" }],
    hours: 7,
    primary: { resourceId: "modern-robotics", sections: "Ch 3.1–3.2 (+ MR lightboard videos for these sections)" },
    equations: ["R^{\\top}R=I,\\; \\det R = 1", "{}^{a}p = {}^{a}R_{b}\\,{}^{b}p", "{}^{a}R_{c}={}^{a}R_{b}{}^{b}R_{c}"],
    implementation: "Start your library: se3.py with rot_x/y/z, compose, is_rotation checks; visualize a triad rotating in matplotlib 3D.",
    exercises: [
      "Compose Rz(90°)Rx(90°) vs Rx(90°)Rz(90°); predict both orientations with your hands before running",
      "Prove R⁻¹=Rᵀ from orthonormal columns (3 lines)",
      "Frame-chase drill: given {}^wR_a and {}^aR_b, express a point known in frame b in world frame",
    ],
    masteryGate: "gold",
    masteryTest: "Superscript-notation frame-chase test: 5 multi-frame problems solved with explicit notation and verified in your library, with zero frame errors.",
    diagnostic: "Why must det=+1 (not −1)? What breaks if you average two rotation matrices entrywise?",
    misconceptions: ["Rotation matrices don't 'rotate points' only. The SAME matrix re-expresses vectors between frames; keep the two readings straight with notation."],
  },
  {
    id: "l5-quaternions",
    level: 5,
    title: "Euler Angles, Axis-Angle & Quaternions",
    track: "core",
    labs: ["robotics", "math"],
    why: "Every robot format (URDF, MJCF, ROS TF) speaks quaternions. Euler angles gimbal-lock and quaternions double-cover. Misunderstanding either costs real debugging days.",
    objectives: [
      "Euler conventions and why 3 numbers must fail somewhere (gimbal lock demonstrated)",
      "Axis-angle; Rodrigues' formula",
      "Unit quaternions: composition, inverse, q and −q; slerp intuition",
    ],
    prereqs: [{ id: "l5-frames-rotations" }],
    hours: 5,
    primary: { resourceId: "eater-quaternions", sections: "All interactive parts; drag the rotations yourself" },
    backup: { resourceId: "modern-robotics", sections: "Ch 3.2.3 + Appendix B" },
    equations: [
      "R = I + \\sin\\theta\\,[\\hat\\omega] + (1-\\cos\\theta)[\\hat\\omega]^2",
      "q = (\\cos\\tfrac{\\theta}{2},\\, \\hat\\omega\\sin\\tfrac{\\theta}{2})",
    ],
    implementation: "Add to se3.py: quat↔matrix↔axis-angle conversions with round-trip property tests (1000 random rotations).",
    exercises: [
      "Produce gimbal lock concretely in a ZYX Euler visualizer; identify the lost axis",
      "Show q and −q give the same rotation; explain why naive quaternion 'distance' is wrong",
    ],
    masteryGate: "gold",
    masteryTest: "Round-trip conversion suite passes to 1e-9 on 1000 random rotations, plus a written half-page: 'which representation for storage, composition, interpolation, optimization, and why'.",
    diagnostic: "Why 4 numbers for 3 DOF? What is the rotation of quaternion (0.707, 0, 0.707, 0)?",
  },
  {
    id: "l5-lie-se3",
    level: 5,
    title: "SE(3), Twists & the Micro-Lie Toolkit",
    track: "core",
    labs: ["robotics", "math"],
    why: "Homogeneous transforms carry rotation+translation as one object; exp/log maps let you differentiate and interpolate poses correctly. This is the exact formalism modern estimation and robot-learning papers assume.",
    objectives: [
      "Homogeneous transforms T∈SE(3); composition and inverse",
      "so(3)/se(3): exp and log maps; twists as velocity of pose",
      "⊞/⊟ (perturbations on the manifold), Solà conventions",
    ],
    prereqs: [{ id: "l5-quaternions" }, { id: "l2-eigen-svd" }],
    hours: 8,
    primary: { resourceId: "sola-lie", sections: "Author's 1h video FIRST, then §I–IV + SO(3)/SE(3) boxes + appendix Jacobian tables" },
    backup: { resourceId: "modern-robotics", sections: "Ch 3.3 (transforms + twists, screw view)" },
    equations: [
      "T = \\begin{bmatrix} R & p \\\\ 0 & 1 \\end{bmatrix}",
      "R = \\exp([\\omega]_\\times\\theta)",
      "T_2 = T_1 \\exp([\\xi]^{\\wedge})\\;\\text{(local perturbation)}",
    ],
    implementation: "Complete se3.py: SE(3) exp/log, adjoint, ⊞/⊟; property tests: exp(log(T))=T, log(exp(ξ))=ξ near identity.",
    exercises: [
      "Interpolate two poses via log/exp geodesic vs naive lerp of matrices; visualize the difference",
      "Verify the SO(3) Jacobian tables numerically on random perturbations",
    ],
    masteryGate: "gold",
    masteryTest: "Your SO(3)/SE(3) module passes a 30-case property suite including exp/log round trips and adjoint identities, and you can state, in one paragraph, why optimization on rotations uses local coordinates.",
    diagnostic: "What is log of a rotation matrix (geometrically)? Why can't you add rotation matrices to optimize them?",
  },
  {
    id: "l5-mujoco-basics",
    level: 5,
    title: "MuJoCo: Your Primary Laboratory",
    track: "code",
    labs: ["robotics", "code"],
    why: "MuJoCo is the curriculum's physics home, and (via Warp/Newton) now the convergent substrate of both Google's and NVIDIA's stacks. Learn to read MJCF, load Menagerie robots, actuate, sense, and render.",
    objectives: [
      "Install; viewer; load Menagerie models (UR5e, Panda)",
      "MJCF anatomy: bodies/joints/geoms/actuators/sensors",
      "Step the sim from Python; read qpos/qvel; apply controls; render offscreen",
    ],
    prereqs: [{ id: "l1-numpy" }, { id: "l1-classes" }],
    hours: 5,
    primary: { resourceId: "mujoco", sections: "Overview + Python bindings; skim MJCF reference as needed" },
    backup: { resourceId: "menagerie", sections: "UR5e model; read its MJCF top to bottom" },
    exercises: [
      "Author a 2-link pendulum MJCF from scratch; verify its DOFs and limits in the viewer",
      "Sinusoidal joint commands to a Menagerie UR5e; plot commanded vs actual positions (discover actuator dynamics exist)",
    ],
    masteryGate: "silver",
    masteryTest: "Build a tabletop scene (arm + cube + camera) in MJCF, drive the arm through a scripted motion, and record a rendered video + joint-state CSV from Python.",
    diagnostic: "What's the difference between a joint and an actuator in MJCF? Where do sensor readings live in mjData?",
  },
  {
    id: "l5-fk",
    level: 5,
    title: "Forward Kinematics (Product of Exponentials)",
    track: "core",
    labs: ["robotics"],
    why: "FK answers 'where is the hand, given the joints', the first question of manipulation. PoE (not DH tables) is the modern formulation used by Drake/Pinocchio and everything you'll read.",
    objectives: [
      "Screws/joint axes; home configuration M",
      "PoE formula assembled from your exp map",
      "DH parameters: read-a-table literacy only",
    ],
    prereqs: [{ id: "l5-lie-se3" }],
    hours: 6,
    primary: { resourceId: "modern-robotics", sections: "Ch 4 (PoE FK) + videos; App C read once" },
    equations: ["T(\\theta) = e^{[S_1]\\theta_1} e^{[S_2]\\theta_2} \\cdots e^{[S_n]\\theta_n} M"],
    implementation: "kin.py: FK for the Menagerie UR5e from its screw axes; validate against MuJoCo's own body poses across 500 random configurations (<1e-6).",
    exercises: [
      "Derive the 2-link planar arm FK by hand from PoE; match your L2-trig version",
      "Extract screw axes for the UR5e from its MJCF frames and document the process",
    ],
    masteryGate: "gold",
    masteryTest: "Your FK matches MuJoCo ground truth to 1e-6 on 500 random configs for a 6-DOF arm YOU parameterized from the model file, plus the 2-link hand derivation on paper.",
    diagnostic: "What is a screw axis? Why does PoE avoid DH's frame-assignment ceremony?",
  },
  {
    id: "l5-jacobians",
    level: 5,
    title: "The Manipulator Jacobian",
    track: "core",
    labs: ["robotics", "math"],
    why: "The Jacobian maps joint velocities to hand velocities. Control, IK, force transmission, and singularity analysis all live here. It is your L2 Jacobian wearing a hard hat.",
    objectives: [
      "Geometric Jacobian columns as joint-axis contributions",
      "Velocity mapping V = J(θ)θ̇; force duality τ = Jᵀf",
      "Singularities: rank collapse; manipulability ellipsoid",
    ],
    prereqs: [{ id: "l5-fk" }, { id: "l2-multivariable", tier: "gold" }],
    hours: 6,
    primary: { resourceId: "modern-robotics", sections: "Ch 5 (velocity kinematics & statics) + videos" },
    equations: ["\\mathcal{V} = J(\\theta)\\dot\\theta", "\\tau = J^{\\top}\\mathcal{F}", "w = \\sqrt{\\det(JJ^{\\top})}"],
    implementation: "kin.py: geometric Jacobian; verify against finite differences of your FK; manipulability ellipsoid plotted along a trajectory.",
    exercises: [
      "Drive the UR5e to a singularity; show σ_min→0 and the ellipsoid collapsing; identify the lost direction",
      "Verify τ=Jᵀf numerically with MuJoCo applied forces",
    ],
    masteryGate: "gold",
    masteryTest: "Finite-difference-verified Jacobian + a written explanation of one singularity of your arm (which motions become impossible and why the math says so).",
    diagnostic: "Columns of J correspond to what? What does σ_min of J tell a controller?",
  },
  {
    id: "l5-ik",
    level: 5,
    title: "Inverse Kinematics (Numerical)",
    track: "core",
    labs: ["robotics"],
    why: "IK answers 'what joints put the hand THERE': Newton's method on the manifold, damped near singularities. Differential IK from this node is the control law inside modern manipulation stacks.",
    objectives: [
      "Newton–Raphson IK with the SE(3) error via log map",
      "Damped least squares (why raw pseudo-inverse explodes near singularities)",
      "Joint limits; null-space motion for redundant arms (concept + demo)",
    ],
    prereqs: [{ id: "l5-jacobians" }],
    hours: 6,
    primary: { resourceId: "modern-robotics", sections: "Ch 6 (numerical IK; skim 6.1 analytic)" },
    backup: { resourceId: "mjctrl", sections: "diffik.py, the oracle for your implementation" },
    equations: ["\\Delta\\theta = J^{\\top}(JJ^{\\top}+\\lambda^2 I)^{-1}\\, e", "e = \\log(T_{\\text{target}} T(\\theta)^{-1})^{\\vee}"],
    implementation: "kin.py: damped-least-squares IK with limits; success-rate benchmark on 500 random reachable poses (target ≥95%, <1mm, <0.5°).",
    exercises: [
      "Show undamped IK exploding near the singularity you found; fix with λ; plot both trajectories",
      "Differential IK teleop: drag a target in the viewer, arm follows at 100 Hz",
    ],
    masteryGate: "gold",
    masteryTest: "IK benchmark passes (≥95% / <1mm / <0.5°) with your own convergence plot, and a paragraph on how λ trades accuracy for robustness.",
    diagnostic: "Why iterate instead of solving in closed form? What does the damping term do to the smallest singular values?",
  },
  {
    id: "l5-dynamics-lite",
    level: 5,
    title: "Rigid-Body Dynamics (The Load-Bearing Subset)",
    track: "core",
    labs: ["robotics", "math"],
    why: "You need the STRUCTURE M(q)q̈ + C(q,q̇)q̇ + g(q) = τ, for computed-torque control and for reading papers, not Featherstone derivations. Simulators do the rest; you learn what they're doing.",
    objectives: [
      "Lagrangian mechanics on a 2-link arm, once, by hand",
      "The manipulator equation's terms: inertia, Coriolis, gravity and what each feels like",
      "Forward vs inverse dynamics; where MuJoCo fits in",
    ],
    prereqs: [{ id: "l5-jacobians" }],
    hours: 5,
    primary: { resourceId: "modern-robotics", sections: "Ch 8.1–8.3 + 8.5 (skim 8.9); MuJoCo docs 'Computation' chapter for how a simulator actually does contacts" },
    equations: ["M(q)\\ddot q + C(q,\\dot q)\\dot q + g(q) = \\tau", "L = T - U"],
    skip: ["Featherstone spatial algebra, O(n) ABA derivations: reference-only unless you someday build a simulator"],
    exercises: [
      "Derive the 2-link arm's M(q) and g(q) via Lagrange; verify against MuJoCo's mass matrix at 10 configurations",
      "Feel gravity compensation: apply τ=g(q) and watch the arm float",
    ],
    masteryGate: "silver",
    masteryTest: "The 2-link derivation on paper + numerical match to MuJoCo, and a correct one-paragraph answer to 'why is Coriolis usually ignorable at low speed but fatal at high speed?'",
    diagnostic: "What does M(q) depend on and why? Units and meaning of each manipulator-equation term?",
  },
  {
    id: "l5-trajectories",
    level: 5,
    title: "Trajectory Generation",
    track: "core",
    labs: ["robotics"],
    why: "Robots don't teleport between configurations. They follow time-parameterized paths with bounded velocity/acceleration. Also your first taste of the 'action sequence' objects policies output.",
    objectives: [
      "Cubic/quintic time scaling; trapezoidal profiles",
      "Joint-space vs task-space (screw) trajectories",
      "Via points; smoothness/jerk intuition",
    ],
    prereqs: [{ id: "l5-ik" }],
    hours: 4,
    primary: { resourceId: "modern-robotics", sections: "Ch 9.1–9.4" },
    equations: ["s(t) = 10(t/T)^3 - 15(t/T)^4 + 6(t/T)^5"],
    implementation: "traj.py: quintic scaling + joint and Cartesian-screw trajectory generators; execute on the UR5e with position control; plot pos/vel/acc profiles.",
    exercises: ["Compare linear vs quintic scaling at the same duration: plot acceleration spikes; explain which a real motor prefers"],
    masteryGate: "silver",
    masteryTest: "Smooth pick-motion trajectory through 3 via points executing on the sim arm with continuous velocity, with profiles plotted and within declared limits.",
    diagnostic: "Why is jerk continuity nice? What's wrong with linear interpolation in SE(3) done naively?",
  },
  {
    id: "boss-robotics",
    level: 5,
    title: "BOSS: Robotics Geometry",
    track: "project",
    labs: ["robotics"],
    why: "Gate: the kinematics stack, from math to moving robot, built by you and verified against oracles, the core of Project PandaKin.",
    objectives: ["Certified kinematics library owner"],
    prereqs: [
      { id: "l5-ik", tier: "gold" },
      { id: "l5-trajectories" },
      { id: "l5-dynamics-lite" },
      { id: "l5-mujoco-basics" },
    ],
    hours: 6,
    masteryGate: "gold",
    masteryTest: "One sitting, your library only (no frameworks): given a NEW Menagerie arm you haven't used (e.g. a Kinova or IIWA), parameterize its screw axes from the model, get FK matching MuJoCo to 1e-6, run your IK benchmark, and execute a smooth square-tracing trajectory with the end-effector, recorded on video with the test suite green.",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    exercises: [],
    projectIds: ["p7-arm-kinematics"],
  },
];
