import type { SkillNode } from "@/lib/types";

export const L6_NODES: SkillNode[] = [
  {
    id: "l6-feedback-pid",
    level: 6,
    title: "Feedback & PID",
    track: "core",
    labs: ["robotics"],
    why: "Feedback is the founding idea of control: measure the error, push against it. PID still runs most of the world's actuators, including the joint controllers under every learned policy.",
    objectives: [
      "Open vs closed loop; why feedback fixes model error and disturbances",
      "P, I, D terms: what each contributes and each one's failure mode",
      "Manual tuning on real(istic) systems; saturation and integrator windup",
    ],
    prereqs: [{ id: "l5-mujoco-basics" }, { id: "l2-derivatives" }],
    hours: 6,
    primary: { resourceId: "brian-douglas", sections: "Intro + PID videos (~5 at 1.25×)" },
    equations: ["u(t) = K_p e(t) + K_i \\int e\\,dt + K_d \\dot e(t)"],
    implementation: "PID class with anti-windup; tune it to (1) hold a MuJoCo pendulum at 45°, (2) make a point-mass follow a step then a sine reference.",
    exercises: [
      "Show each pathology deliberately: P-only steady-state error, excess I windup overshoot, D amplifying sensor noise",
      "Tune Kp/Ki/Kd by hand and document your tuning procedure as an algorithm",
    ],
    masteryGate: "gold",
    masteryTest: "Given an unseen second-order MuJoCo system, tune a PID to spec (rise time, overshoot bounds) and explain every gain change you made and why.",
    diagnostic: "What does the D term do to overshoot and to noise? Why does pure P leave steady-state error under gravity?",
  },
  {
    id: "l6-state-space",
    level: 6,
    title: "State-Space Models & Stability",
    track: "core",
    labs: ["robotics", "math"],
    why: "ẋ = Ax + Bu is the lingua franca of modern control AND the shape of every latent world model. Eigenvalues you learned in L2 now literally decide if systems blow up.",
    objectives: [
      "States/inputs/outputs; linearization of nonlinear dynamics about equilibria",
      "Stability from eigenvalues (continuous vs discrete)",
      "Controllability intuition (can inputs reach the whole state space?)",
    ],
    prereqs: [{ id: "l2-eigen-svd", tier: "gold" }, { id: "l6-feedback-pid" }],
    hours: 6,
    primary: { resourceId: "brunton-bootcamp", sections: "State-space, stability, controllability, pole-placement videos, implementing along" },
    equations: ["\\dot x = Ax + Bu", "x_{t+1} = Ax_t + Bu_t", "\\text{stable} \\iff \\operatorname{Re}(\\lambda_i)<0\\;(\\text{or } |\\lambda_i|<1)"],
    exercises: [
      "Linearize the pendulum about both equilibria; check eigenvalues; simulate to confirm the up-position is unstable",
      "Pole placement by hand on a double integrator: choose K, verify closed-loop eigenvalues move",
    ],
    masteryGate: "gold",
    masteryTest: "Derive the cart-pole linearization about upright (from the nonlinear equations), assemble (A,B), and demonstrate a stabilizing state-feedback gain you computed in simulation.",
    diagnostic: "Where do A's eigenvalues live for a stable discrete system? What makes (A,B) uncontrollable, intuitively?",
  },
  {
    id: "l6-lqr",
    level: 6,
    title: "LQR: Optimal Feedback",
    track: "core",
    labs: ["robotics", "math"],
    why: "'Penalize state error and effort, get the optimal gain'. LQR is control's crown jewel and secretly RL's ancestor: a value function solved exactly. The Riccati equation is a Bellman equation.",
    objectives: [
      "Quadratic cost design (Q, R) and the tradeoffs it encodes",
      "The Riccati recursion (discrete) implemented, not just called",
      "LQR as the local controller inside bigger systems",
    ],
    prereqs: [{ id: "l6-state-space" }, { id: "l2-optimization" }],
    hours: 6,
    primary: { resourceId: "brunton-bootcamp", sections: "LQR segment" },
    backup: { resourceId: "underactuated", sections: "Ch 8 (LQR; the value-function view)" },
    equations: [
      "J = \\sum_t x_t^{\\top}Q x_t + u_t^{\\top}R u_t",
      "u = -Kx",
      "P = Q + A^{\\top}P A - A^{\\top}PB(R+B^{\\top}PB)^{-1}B^{\\top}PA",
    ],
    implementation: "Discrete Riccati iteration from scratch → K for cart-pole; compare against scipy's solver; balance the MuJoCo cart-pole from perturbed starts.",
    exercises: [
      "Sweep R by 100×: show the aggressive-vs-lazy control tradeoff in trajectories and effort plots",
      "Explain in writing why P defines a value function x^T P x, your first Bellman equation",
    ],
    masteryGate: "gold",
    masteryTest: "Cart-pole balanced by YOUR Riccati-derived K, with a Q/R ablation table and the PID-vs-LQR comparison (disturbance rejection, effort) quantified.",
    diagnostic: "What does increasing R do? Why is LQR only locally valid on the real pendulum?",
  },
  {
    id: "l6-mpc",
    level: 6,
    title: "Model Predictive Control",
    track: "core",
    labs: ["robotics"],
    why: "Plan a short future, act, replan. MPC is how constraints enter control, and the conceptual bridge to world-model planning (TD-MPC2 is literally this with a learned model).",
    objectives: [
      "Receding-horizon idea; why replanning forgives model error",
      "Constraints (input/state) as MPC's superpower over LQR",
      "Horizon-length tradeoffs; sampling-based MPC (CEM) preview",
    ],
    prereqs: [{ id: "l6-lqr" }],
    hours: 5,
    primary: { resourceId: "underactuated", sections: "Ch 10 trajectory-optimization intro (direct methods) + your own QP-MPC build" },
    equations: ["\\min_{u_{0:H}} \\sum_{t=0}^{H} \\|x_t\\|_Q^2 + \\|u_t\\|_R^2 \\;\\; \\text{s.t. } x_{t+1}=Ax_t+Bu_t,\\; |u_t|\\le u_{max}"],
    implementation: "QP-based MPC (cvxpy/OSQP) on the double integrator with input limits, then cart-pole; also a 50-sample CEM-MPC on the same task to preview sampling-based planning.",
    exercises: ["Show MPC respecting an input limit that makes LQR fail; sweep horizon 5→50 and plot performance vs compute"],
    masteryGate: "silver",
    masteryTest: "Working constrained MPC on cart-pole with a horizon study, plus one paragraph connecting CEM-MPC to how TD-MPC2/V-JEPA-AC plan in latent spaces.",
    diagnostic: "Why does MPC re-solve every step instead of executing the whole plan? What do constraints buy over LQR?",
  },
  {
    id: "l6-bayes-filter",
    level: 6,
    title: "The Bayes Filter",
    track: "core",
    labs: ["robotics", "math"],
    why: "The master equation of state estimation: predict with the motion model, correct with the measurement. Kalman, EKF, particle filters: all are this one loop with different representations.",
    objectives: [
      "Belief as a distribution over state; predict/update cycle derived from Bayes",
      "Discrete Bayes filter implemented on a 1D corridor robot",
      "Motion and measurement models as the two things you must specify",
    ],
    prereqs: [{ id: "l2-random-variables", tier: "gold" }],
    hours: 4,
    primary: { resourceId: "labbe-kalman", sections: "Ch 1–2 (g-h filter, discrete Bayes); run and modify the notebooks" },
    equations: [
      "\\overline{bel}(x_t) = \\int p(x_t\\mid u_t, x_{t-1})\\,bel(x_{t-1})\\,dx",
      "bel(x_t) = \\eta\\, p(z_t\\mid x_t)\\,\\overline{bel}(x_t)",
    ],
    implementation: "Discrete Bayes filter for a robot in a 20-cell corridor with door sensors; animate the belief sharpening and getting kidnapped.",
    exercises: ["Kidnap the robot mid-run: watch belief recover; break the sensor model and watch confident wrongness. Narrate both"],
    masteryGate: "gold",
    masteryTest: "Derive the predict/update equations from Bayes + total probability on paper, and your corridor filter localizes from uniform prior within 10 steps.",
    diagnostic: "Which step increases uncertainty and which decreases it? Where exactly does Bayes' rule enter?",
  },
  {
    id: "l6-kalman",
    level: 6,
    title: "Kalman Filter, From Scratch",
    track: "core",
    labs: ["robotics", "math"],
    why: "The optimal Bayes filter when everything is Gaussian and linear, and the most deployed algorithm in robotics history. Built from equations you now fully own.",
    objectives: [
      "KF as Bayes filter with Gaussians: predict/update in matrix form",
      "Kalman gain as precision-weighted trust; innovation",
      "Tuning Q/R; NEES/NIS consistency checking (the honest-filter test)",
    ],
    prereqs: [{ id: "l6-bayes-filter" }, { id: "l6-state-space" }],
    hours: 8,
    primary: { resourceId: "labbe-kalman", sections: "Ch 4–8 (1D → multivariate KF, design); every filter written from scratch, FilterPy as oracle only" },
    equations: [
      "\\bar x = Fx,\\;\\; \\bar P = FPF^{\\top}+Q",
      "K = \\bar P H^{\\top}(H\\bar P H^{\\top}+R)^{-1}",
      "x = \\bar x + K(z - H\\bar x)",
    ],
    implementation: "est.py: KF tracking a 2D constant-velocity target from noisy position measurements; NEES/NIS consistency plots against chi-square bounds.",
    exercises: [
      "Derive the 1D Kalman update as a product of two Gaussians (precision-weighted mean)",
      "Mis-tune R by 100× both ways: show overconfident vs sluggish filters in the NIS plot",
    ],
    masteryGate: "gold",
    masteryTest: "Blank file → consistent 2D tracker (NEES within bounds over 100 Monte-Carlo runs) + the 1D Gaussian-product derivation on paper.",
    diagnostic: "What does K→0 vs K→1 mean about sensor trust? Write the innovation and its covariance.",
    projectIds: ["p10-kf-localization"],
  },
  {
    id: "l6-ekf-pf",
    level: 6,
    title: "EKF & Particle Filters",
    track: "core",
    labs: ["robotics"],
    why: "Real robots are nonlinear (bearings, ranges, poses on SE(3)). EKF linearizes with YOUR Jacobians; particle filters drop assumptions entirely. Together they cover 95% of practical estimation.",
    objectives: [
      "EKF: Jacobian linearization of motion/measurement models; where it breaks",
      "Particle filter: sample-weight-resample; degeneracy and effective sample size",
      "Choosing between KF/EKF/PF for a given problem",
    ],
    prereqs: [{ id: "l6-kalman" }, { id: "l5-lie-se3" }],
    hours: 5,
    primary: { resourceId: "labbe-kalman", sections: "Ch 11 (EKF) + Ch 12 (particle filters)" },
    backup: { resourceId: "stachniss", sections: "EKF/PF lectures if Labbe's treatment feels too applied" },
    equations: ["F = \\left.\\tfrac{\\partial f}{\\partial x}\\right|_{\\hat x}", "w_i \\propto p(z\\mid x_i);\\;\\; N_{\\text{eff}} = 1/\\textstyle\\sum_i w_i^2"],
    implementation: "EKF for a unicycle robot with range-bearing landmarks; PF for the same problem; head-to-head RMSE + a kidnapping test (PF wins; explain why).",
    exercises: ["Push the EKF to failure with a sharp nonlinearity and coarse timestep; document the divergence signature"],
    masteryGate: "gold",
    masteryTest: "Both filters localizing the same simulated robot, quantitative comparison table, and correct answers to 'when must you NOT use an EKF?'",
    diagnostic: "What exactly gets linearized in an EKF? Why does resampling cause particle depletion?",
  },
  {
    id: "l6-pendulum-project",
    level: 6,
    title: "Project P9: Inverted Pendulum, Three Ways",
    track: "project",
    labs: ["robotics"],
    why: "The level's synthesis: one system, three controllers (PID, LQR, MPC), quantitative comparison, estimator in the loop, a complete miniature of real control engineering.",
    objectives: ["Swing-up + balance with layered control; estimator-driven control; honest comparison"],
    prereqs: [{ id: "l6-lqr", tier: "gold" }, { id: "l6-mpc" }, { id: "l6-kalman", tier: "gold" }],
    hours: 8,
    implementation: "MuJoCo cart-pole: energy-based swing-up → LQR catch; PID vs LQR vs MPC comparison table (settling time, effort, disturbance rejection, constraint handling); then close the loop on KF-estimated state with noisy sensors and quantify degradation.",
    exercises: ["Inject sensor noise ×10: which controller degrades most gracefully, and why?"],
    masteryGate: "gold",
    masteryTest: "P9 accepted: video + comparison table + estimator-in-loop result + half-page 'what surprised me', the level's exit gate.",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    projectIds: ["p9-inverted-pendulum"],
  },
];
