import type { SkillNode } from "@/lib/types";

export const L7_NODES: SkillNode[] = [
  {
    id: "l7-ros2-core",
    level: 7,
    title: "ROS 2 Core: Nodes, Topics, Services",
    track: "code",
    labs: ["robotics", "code"],
    why: "ROS 2 is how robot software components talk, the plumbing of nearly every real robot lab. You learn Jazzy on Ubuntu 24.04 (deliberately NOT the 3-month-old Lyrical: the CUDA/Isaac ecosystem lives on 24.04).",
    objectives: [
      "Install Jazzy; workspaces, colcon, sourcing",
      "CLI fluency: node/topic/service/param/action introspection",
      "The pub/sub mental model and message interfaces",
    ],
    prereqs: [{ id: "l0-workflow-capstone", tier: "gold" }, { id: "l1-testing-modules" }],
    hours: 8,
    primary: { resourceId: "ros2-docs", sections: "Beginner: CLI tools (all 9 lessons) + first client-library lessons" },
    exercises: [
      "Run turtlesim; discover everything about it with introspection commands only (no docs): nodes, topics, types, rates",
      "ros2 topic pub a Twist by hand; echo the pose; graph it with rqt",
    ],
    masteryGate: "silver",
    masteryTest: "Given an unfamiliar running ROS 2 system, map its computation graph (nodes/topics/types/rates) in 15 minutes using CLI only and diagram it.",
    diagnostic: "Topic vs service vs action: one sentence and one example each. What does sourcing a workspace actually do?",
  },
  {
    id: "l7-ros2-interfaces",
    level: 7,
    title: "rclpy: Writing Nodes",
    track: "code",
    labs: ["robotics", "code"],
    why: "Now you write the components: publishers, subscribers, services, actions, parameters, the vocabulary of every perception→planning→control pipeline you'll build or read.",
    objectives: [
      "Publisher/subscriber nodes with timers and QoS defaults",
      "Service + client; action client (concept + one use)",
      "Custom interfaces; parameters with callbacks",
    ],
    prereqs: [{ id: "l7-ros2-core" }],
    hours: 6,
    primary: { resourceId: "ros2-docs", sections: "Beginner client libraries: pub/sub, service, custom interfaces, parameters (Python; read-port one C++ pub/sub)" },
    implementation: "A sensor-fusion toy: fake_gps node + fake_imu node → fusion node (your L6 KF!) → /pose_estimate; a service to reset the filter.",
    exercises: ["Break QoS compatibility on purpose (transient vs volatile) and diagnose the silent non-connection"],
    masteryGate: "gold",
    masteryTest: "Build the three-node KF-fusion pipeline from scratch in one session: clean package, launch-able, introspectable.",
    diagnostic: "Where does a subscriber callback run? Why do timers beat sleep loops in nodes?",
  },
  {
    id: "l7-launch-tf-urdf",
    level: 7,
    title: "Launch, TF2 & URDF",
    track: "code",
    labs: ["robotics"],
    why: "TF2 is your L5 frame mathematics as a distributed system; URDF is how robots are described to the whole ROS ecosystem. Launch files compose it all into a system.",
    objectives: [
      "Python launch files: multiple nodes, params from YAML, namespaces",
      "TF2: static/dynamic broadcasters, lookups, time travel basics",
      "URDF/Xacro: links/joints/inertials; robot_state_publisher; RViz visualization",
    ],
    prereqs: [{ id: "l7-ros2-interfaces" }, { id: "l5-frames-rotations", tier: "gold" }],
    hours: 8,
    primary: { resourceId: "ros2-docs", sections: "Intermediate: Launch, TF2, URDF tutorials" },
    backup: { resourceId: "articulated-robotics", sections: "URDF/Xacro episodes of the mobile-robot series" },
    implementation: "Author a differential-drive robot URDF (base + 2 wheels + caster + lidar + camera mounts) in Xacro; visualize in RViz with joint-state GUI; broadcast a moving TF and query transforms between arbitrary frames.",
    exercises: ["Write a node that answers 'where is the camera relative to the left wheel NOW' via TF lookup. Connect this to your se3.py compose operation"],
    masteryGate: "gold",
    masteryTest: "Your URDF robot fully visualized and TF-correct: I pick two frames and a time, you produce the transform and defend it against your own se3 math.",
    diagnostic: "Who publishes TF for robot links (and from what inputs)? Xacro vs URDF: why bother?",
  },
  {
    id: "l7-gazebo-control",
    level: 7,
    title: "Gazebo Harmonic + ros2_control",
    track: "code",
    labs: ["robotics"],
    why: "The ROS-native simulator (Harmonic pairs with Jazzy from apt) plus the standard control stack: this is how ROS robots actually move. Scoped tightly: Gazebo serves the project and never becomes the curriculum.",
    objectives: [
      "Spawn your URDF in Gazebo via ros_gz; bridge topics",
      "ros2_control architecture: controller_manager, diff_drive_controller, joint_trajectory_controller",
      "Simulated sensors: lidar + camera + IMU publishing into ROS",
    ],
    prereqs: [{ id: "l7-launch-tf-urdf" }],
    hours: 9,
    primary: { resourceId: "articulated-robotics", sections: "Gazebo + ros2_control + sensors episodes (build-along)" },
    backup: { resourceId: "ros2-docs", sections: "Simulators section as reference" },
    implementation: "Your diff-drive robot driving in a Gazebo world by teleop: gz_ros2_control wired, sensors bridged and visualized in RViz simultaneously.",
    exercises: ["Drive into a wall watching lidar; verify camera + IMU rates; record the whole session as a bag"],
    masteryGate: "gold",
    masteryTest: "From your URDF to a driving, sensing robot in Gazebo with ros2_control, reproducible with one launch file on a clean checkout.",
    diagnostic: "What does controller_manager manage? Which piece converts /cmd_vel into wheel torques?",
  },
  {
    id: "l7-bags-debugging",
    level: 7,
    title: "Bags, Introspection & System Debugging",
    track: "code",
    labs: ["robotics"],
    why: "Data recording is how robotics experiments become analyzable and reproducible, and how real teams debug field failures. Bags are your lab notebook's raw data.",
    objectives: [
      "ros2 bag record/play/info; selective topics; analysis in Python",
      "rqt_graph, tf tree views, logging levels",
      "A debugging protocol for 'the robot does nothing'",
    ],
    prereqs: [{ id: "l7-ros2-interfaces" }],
    hours: 3,
    primary: { resourceId: "ros2-docs", sections: "ros2 bag tutorial + rqt tooling" },
    exercises: ["Record a teleop run; replay it into RViz; load the bag in Python and plot lidar-min-distance vs commanded speed"],
    masteryGate: "silver",
    masteryTest: "Given a bag of a failing run (planted fault: TF gap), find the failure from the bag alone and write the incident note.",
    diagnostic: "How do you check if a message is actually flowing, its rate, and who publishes it (three commands)?",
  },
  {
    id: "l7-cpp-literacy",
    level: 7,
    title: "C++ Reading Literacy",
    track: "code",
    labs: ["code", "robotics"],
    why: "90% of your work is Python, but the robotics substrate (rclcpp, Nav2 plugins, drivers, MuJoCo internals) is C++. Twenty focused hours of READING fluency, not a semester, is the researched budget.",
    objectives: [
      "Types/references/const; headers vs source; how a build works (CMake mental model)",
      "Classes/templates at reading level; STL containers recognized",
      "Trace a real ROS 2 C++ node and a Nav2 plugin end-to-end",
    ],
    prereqs: [{ id: "l1-functions", tier: "gold" }],
    hours: 8,
    primary: { resourceId: "learncpp", sections: "Ch ~1–11 fast + skim classes/templates chapters" },
    exercises: [
      "Port the official rclcpp pub/sub + service tutorials: type them, build them, break them, fix the compiler errors",
      "Annotate a printed page of Nav2 costmap plugin code: every syntax element named",
    ],
    masteryGate: "silver",
    masteryTest: "Read an unseen 150-line robotics C++ file aloud, explaining semantics (ownership, references, virtual calls) with ≤3 misses; diagnose one planted compile error stack.",
    diagnostic: "What does `const std::string&` in a signature mean and why is it idiomatic? What does a linker error look like vs a compile error?",
    skip: ["Writing significant C++: expand only when a project forces it (per handover §17)"],
  },
  {
    id: "l7-sim-landscape",
    level: 7,
    title: "The 2026 Simulator Landscape",
    track: "core",
    labs: ["robotics", "embodied"],
    why: "Strategic literacy: MuJoCo (your home) vs Gazebo (ROS-native) vs Isaac Lab (industry GPU stack, 16 GB floor, in Newton transition) vs Genesis (watchlist). Knowing WHEN each earns its complexity is a researcher's judgment call.",
    objectives: [
      "The MuJoCo-Warp/Newton convergence story (DeepMind+NVIDIA) and why MJCF skills transfer everywhere",
      "Isaac Sim/Lab: what it uniquely offers (photoreal sensors, task libraries) and its adoption triggers",
      "MJX batched-simulation preview: 4096 pendulums stepping in parallel on your GPU",
    ],
    prereqs: [{ id: "l5-mujoco-basics" }],
    hours: 4,
    primary: { resourceId: "mujoco", sections: "MJX docs section + one batched-stepping demo" },
    exercises: ["Run an MJX batched rollout (1000 envs) and time steps/sec vs single-env MuJoCo. Feel the 3-orders-of-magnitude gap that makes modern robot RL possible"],
    masteryGate: "bronze",
    masteryTest: "Write the one-page 'simulator decision memo' for your own rig (GPU tier from Settings): which sim for which phase, with the triggers that would change the answer.",
    diagnostic: "Name the phase where Gazebo beats MuJoCo, and the trigger that justifies installing Isaac Lab.",
  },
  {
    id: "l7-ros-robot-project",
    level: 7,
    title: "Project P11: The Integrated ROS Robot",
    track: "project",
    labs: ["robotics"],
    why: "The level's exit: your simulated robot, your nodes, your launch files, a complete sense→compute→act system you can demo, record, and extend into Level 8/9 work.",
    objectives: ["Integrate everything: URDF, Gazebo, ros2_control, sensors, custom logic node, bags"],
    prereqs: [{ id: "l7-gazebo-control", tier: "gold" }, { id: "l7-bags-debugging" }],
    hours: 6,
    implementation: "'Wanderer': your diff-drive robot autonomously roams a Gazebo world using lidar-based obstacle avoidance (a simple reactive controller node you write), with a service to start/stop, parameters for speed/threshold, full launch, and a recorded bag + plot of its trajectory.",
    exercises: ["Add a 'panic stop' when an object approaches faster than X. Test it with a moving obstacle"],
    masteryGate: "gold",
    masteryTest: "P11 accepted: one-command launch on clean checkout, roaming demo video, bag-derived trajectory plot, README explaining the node graph.",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    projectIds: ["p11-ros-robot"],
  },
];
