import type { SkillNode } from "@/lib/types";

export const L8_NODES: SkillNode[] = [
  {
    id: "l8-camera-models",
    level: 8,
    title: "Image Formation & Camera Geometry",
    track: "core",
    labs: ["robotics", "ml"],
    why: "The pinhole model is the bridge between pixels and the 3D world, the math that lets a robot turn 'I see it at pixel (412, 208)' into 'it is 40 cm ahead'. Deeply learned here; everything after is tools.",
    objectives: [
      "Pinhole model; intrinsics K (focal, principal point); extrinsics [R|t]",
      "Projection π: 3D→pixel and its information loss; homogeneous coordinates paying rent",
      "Distortion models at working level",
    ],
    prereqs: [{ id: "l5-frames-rotations", tier: "gold" }, { id: "l2-linear-maps" }],
    hours: 6,
    primary: { resourceId: "fpcv", sections: "Image formation + lenses + camera-model modules" },
    equations: ["s\\,\\begin{bmatrix}u\\\\v\\\\1\\end{bmatrix} = K\\,[R\\mid t]\\,\\begin{bmatrix}X\\\\Y\\\\Z\\\\1\\end{bmatrix}", "K = \\begin{bmatrix} f_x & 0 & c_x\\\\ 0 & f_y & c_y \\\\ 0&0&1\\end{bmatrix}"],
    implementation: "project.py: project 3D points through a K you define; render a wireframe cube from a virtual camera you move on an orbit, in pure NumPy, no OpenCV.",
    exercises: [
      "Halve fx: predict then verify what happens to the image; explain focal length as zoom",
      "Given a MuJoCo camera's fovy and resolution, derive its K and verify by projecting a known site position onto the rendered image",
    ],
    masteryGate: "gold",
    masteryTest: "From a rendered MuJoCo image and known camera pose, predict the pixel location of a scene object to <2px using your own projection code, the full 3D→2D chain owned.",
    diagnostic: "What information does projection destroy? What are the units and meaning of fx? Why homogeneous coordinates?",
  },
  {
    id: "l8-calibration-opencv",
    level: 8,
    title: "Calibration & OpenCV Fundamentals",
    track: "code",
    labs: ["robotics"],
    why: "Calibration recovers K from images, the ritual every real-robot session begins with. OpenCV is the lingua-franca toolbox; you learn the 20% that does 90% (incl. solvePnP, the pose workhorse).",
    objectives: [
      "Checkerboard/ArUco calibration pipeline; reprojection error as the quality metric",
      "OpenCV basics: imread/color/resize/undistort, drawing, ArUco detection",
      "solvePnP: 2D-3D correspondences → camera (or object) pose",
    ],
    prereqs: [{ id: "l8-camera-models" }, { id: "l1-numpy", tier: "gold" }],
    hours: 5,
    primary: { resourceId: "opencv", sections: "Calibration tutorial + ArUco + solvePnP labs" },
    implementation: "Calibrate a simulated (MuJoCo-rendered checkerboard sequence) or webcam camera; undistort; then estimate an ArUco cube's 6-DoF pose live and draw its axes.",
    exercises: ["Compare your derived MuJoCo K vs the calibrated estimate; explain the residual"],
    masteryGate: "gold",
    masteryTest: "Full pipeline on fresh data: calibrate (<0.5px reprojection), then track a fiducial's pose and overlay a virtual object that 'sticks' to it.",
    diagnostic: "What does reprojection error measure exactly? Minimum correspondences for PnP and why?",
  },
  {
    id: "l8-depth-pointclouds",
    level: 8,
    title: "Depth, RGB-D & Point Clouds",
    track: "core",
    labs: ["robotics"],
    why: "Manipulation needs 3D. Depth images unproject into point clouds, the representation grasp planners and ICP consume. MuJoCo gives you perfect RGB-D to learn on before real sensors add their lies.",
    objectives: [
      "Stereo intuition (disparity→depth); RGB-D unprojection with K⁻¹",
      "Point-cloud ops: downsampling, normals, cropping (Open3D)",
      "Depth Anything 3 as the monocular-depth tool when no depth sensor exists",
    ],
    prereqs: [{ id: "l8-camera-models" }],
    hours: 6,
    primary: { resourceId: "open3d", sections: "RGB-D→cloud, normals, visualization" },
    backup: { resourceId: "depth-anything3", sections: "Run on your own images; compare to MuJoCo ground-truth depth" },
    equations: ["p = Z\\,K^{-1}\\,[u, v, 1]^{\\top}", "Z = \\tfrac{f b}{d}\\;\\text{(stereo)}"],
    implementation: "Render RGB-D of your MuJoCo tabletop; unproject to a colored cloud with YOUR K⁻¹ code (verify against Open3D's); estimate the table plane and segment points above it.",
    exercises: ["Corrupt depth with realistic noise + holes; watch your plane fit degrade; add robust (RANSAC) fitting"],
    masteryGate: "gold",
    masteryTest: "From one RGB-D frame: table plane removed, object clusters segmented, each cluster's centroid reported in ROBOT frame (chaining your TF math), verified against sim ground truth to <1 cm.",
    diagnostic: "Why does depth accuracy fall with distance (stereo)? What does K⁻¹ do in unprojection?",
  },
  {
    id: "l8-pose-estimation",
    level: 8,
    title: "6-DoF Object Pose: PnP & ICP",
    track: "core",
    labs: ["robotics"],
    why: "'Where is the cup, exactly' is THE manipulation question. PnP answers it from 2D-3D correspondences; ICP refines it from clouds. Tedrake's Ch 4 treatment makes both concrete.",
    objectives: [
      "Pose from correspondences (PnP recap in the object-pose direction)",
      "ICP: correspondence → alignment iteration; local minima and initialization",
      "Pose error metrics (ADD, angular) for honest evaluation",
    ],
    prereqs: [{ id: "l8-depth-pointclouds" }, { id: "l5-lie-se3", tier: "gold" }],
    hours: 5,
    primary: { resourceId: "tedrake-manipulation", sections: "Ch 4 Geometric Pose Estimation + its notebooks" },
    backup: { resourceId: "open3d", sections: "ICP registration tutorial" },
    equations: ["T^{*} = \\arg\\min_T \\sum_i \\|T p_i - q_{c(i)}\\|^2"],
    implementation: "Point-to-point ICP written from scratch (SVD-based alignment step, your L2 SVD earning rent); align a model cloud to your segmented scene cluster; compare vs Open3D's ICP.",
    exercises: ["Start ICP from 4 initializations incl. one adversarial: document the local-minimum failure and a mitigation (better init from centroid+PCA)"],
    masteryGate: "gold",
    masteryTest: "Your from-scratch ICP recovers a sim object's pose to <5 mm/<2° from a decent init, with the SVD alignment derivation on paper.",
    diagnostic: "Why is the optimal rotation an SVD problem (Procrustes)? When does ICP diverge?",
  },
  {
    id: "l8-modern-tools",
    level: 8,
    title: "Modern Perception Tools (SAM 3, DA3, YOLO)",
    track: "code",
    labs: ["robotics", "ml"],
    why: "In 2026 you do not train detectors from scratch; you WIELD foundation tools: SAM 3 for open-vocabulary segmentation, Depth Anything 3 for depth, YOLO26 when speed matters. Tools, not topics: wired into pipelines in an afternoon each.",
    objectives: [
      "SAM 3 concept-prompted segmentation on your scenes",
      "Choosing the tool: open-vocab vs fast supervised vs depth, as a decision table you own",
      "Mask → point-cloud pipeline: segmentation lifted to 3D",
    ],
    prereqs: [{ id: "l4-vit", tier: "gold" }, { id: "l8-depth-pointclouds" }],
    hours: 5,
    primary: { resourceId: "sam3", sections: "Text-prompted segmentation on rendered + real images" },
    backup: { resourceId: "depth-anything3", sections: "As the no-depth-sensor fallback" },
    exercises: [
      "Prompt SAM 3 with 'red cube' on your MuJoCo tabletop render; lift the mask through depth to a 3D cluster",
      "Failure hunt: find three prompts/scenes where SAM 3 fails; characterize the failure modes",
    ],
    masteryGate: "silver",
    masteryTest: "Language → 3D localization demo: type an object name, system returns its 3D position in robot frame by SAM3+depth+your unprojection, with a short failure-mode appendix.",
    diagnostic: "When would you pick YOLO over SAM 3 (two concrete reasons)? Why do foundation tools change what 'perception curriculum' means?",
  },
  {
    id: "l8-repr-learning",
    level: 8,
    title: "Visual Representations for Robots",
    track: "core",
    labs: ["ml", "embodied"],
    why: "Robot policies see through frozen DINO/SigLIP-class features. The 'frozen backbone + head' pattern from L4 is exactly how π0-class systems consume vision. This node connects your CLIP knowledge to the robotics use.",
    objectives: [
      "Why frozen features: sample efficiency, robustness, compute",
      "Dense (patch) features vs pooled features; what VLAs actually take",
      "Probe quality: linear probes as representation evaluation",
    ],
    prereqs: [{ id: "l4-clip-contrastive", tier: "gold" }],
    hours: 4,
    primary: { resourceId: "open-clip", sections: "Dense-feature extraction; DINOv3 frozen features via its repo" },
    exercises: [
      "Extract DINOv3/SigLIP patch features from tabletop images; PCA-visualize and watch objects segment themselves",
      "Linear-probe two backbones for a 5-class object task at 50 labels each; report which wins and hypothesize why",
    ],
    masteryGate: "silver",
    masteryTest: "One-page memo with plots: 'which frozen backbone should our robot stack use, based on my probe experiments', a real mini-study.",
    diagnostic: "Why do policies rarely fine-tune the vision encoder end-to-end from scratch? What do DINO patch features encode that CLIP pooled features don't?",
  },
  {
    id: "l8-slam-bridge",
    level: 8,
    title: "SLAM & Visual Odometry (The Bridge, Not the Ocean)",
    track: "core",
    labs: ["robotics"],
    why: "For a manipulation-focused researcher, deep SLAM is off the critical path (audited decision), but you must know what it is, run one, and know where the SLAM Handbook lives for the day you need it.",
    objectives: [
      "The SLAM problem: chicken-and-egg of mapping + localization; your Bayes filter generalized",
      "EKF-SLAM and FastSLAM run and read (PythonRobotics)",
      "VO concept; where learned features changed the field",
    ],
    prereqs: [{ id: "l6-ekf-pf", tier: "gold" }],
    hours: 3,
    primary: { resourceId: "stachniss", sections: "'Introduction to SLAM' lecture + graph-SLAM overview" },
    backup: { resourceId: "pythonrobotics", sections: "EKF-SLAM + FastSLAM demos; run, then read" },
    references: [{ resourceId: "slam-handbook", sections: "On-demand forever after" }],
    exercises: ["Run EKF-SLAM; kill loop closure; watch drift accumulate and narrate why"],
    masteryGate: "bronze",
    masteryTest: "Whiteboard the SLAM problem and its two classic solutions in 10 minutes, ending with 'and here is why my manipulation research doesn't need me to go deeper (yet)'.",
    diagnostic: "What makes SLAM harder than localization-with-a-map? What does loop closure fix?",
  },
  {
    id: "l8-perception-project",
    level: 8,
    title: "Project P13: Language → 3D Object Localization",
    track: "project",
    labs: ["robotics"],
    why: "The level's exit and a direct VLA precursor: speak an object's name, get its graspable 3D pose, the perception half of every 'pick up the X' demo you'll ever run.",
    objectives: ["Full pipeline: prompt → segment → depth → cloud → pose in robot frame → visualized"],
    prereqs: [{ id: "l8-pose-estimation", tier: "gold" }, { id: "l8-modern-tools" }],
    hours: 4,
    implementation: "On your MuJoCo tabletop (3+ objects): text prompt → SAM 3 mask → depth crop → cluster → ICP/PCA pose → pose published as TF & drawn in the viewer. Quantitative eval vs sim ground truth across 20 scenes (success rate + error stats).",
    exercises: ["Stress test: occlusion, duplicate objects, absent object. Define correct behavior for each and measure it"],
    masteryGate: "gold",
    masteryTest: "P13 accepted: ≥85% localization success across your 20-scene eval, error table, failure appendix, the pipeline Level 9 will pick objects with.",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    projectIds: ["p13-object-localization"],
  },
];
