import type { SkillNode } from "@/lib/types";

export const L9_NODES: SkillNode[] = [
  {
    id: "l9-graph-search",
    level: 9,
    title: "Graph Search & A*",
    track: "core",
    labs: ["robotics", "code"],
    why: "The cleanest planning algorithm in existence and the mental template for everything after: explore states, order by promise, guarantee the best path. Also your one concession to classical algorithms, earned, not ritual.",
    objectives: [
      "BFS/Dijkstra/A*; admissible heuristics and why they preserve optimality",
      "Grid worlds as configuration spaces",
      "Cost functions shaping behavior",
    ],
    prereqs: [{ id: "l1-data-structures", tier: "gold" }],
    hours: 4,
    primary: { resourceId: "pythonrobotics", sections: "A*/Dijkstra reference implementations; build yours first, compare after" },
    equations: ["f(n) = g(n) + h(n)"],
    implementation: "A* on occupancy grids with visualization of explored set; heuristics: zero (Dijkstra), euclidean, inflated (watch optimality break).",
    exercises: ["Animate explored-node counts across heuristics on the same maze; explain the admissibility tradeoff you observe"],
    masteryGate: "gold",
    masteryTest: "Blank-file A* solving unseen mazes with a correctness proof sketch (why the first goal expansion is optimal) in your own words.",
    diagnostic: "What breaks if h overestimates? Why does A* with h=0 equal Dijkstra?",
  },
  {
    id: "l9-sampling-planning",
    level: 9,
    title: "Sampling-Based Planning: RRT & RRT*",
    track: "core",
    labs: ["robotics"],
    why: "Arms live in 6-7D configuration spaces where grids explode. Sampling planners (throw random configurations, connect what's reachable) are the workhorses of motion planning, and you build them.",
    objectives: [
      "C-space vs workspace; collision checking as the primitive",
      "RRT growth; goal biasing; path extraction + shortcutting",
      "RRT* rewiring intuition (asymptotic optimality)",
    ],
    prereqs: [{ id: "l9-graph-search" }, { id: "l5-ik", tier: "gold" }],
    hours: 6,
    primary: { resourceId: "pythonrobotics", sections: "RRT/RRT* references, after your own build" },
    references: [{ resourceId: "lavalle", sections: "Ch 5 skim for the theory backbone" }, { resourceId: "ompl", sections: "Know it exists as the production library" }],
    implementation: "2D RRT first (visualized growing tree), then joint-space RRT for your UR5e around a shelf obstacle using MuJoCo collision checks; shortcut + time-parameterize with your traj.py.",
    exercises: ["50-seed benchmark: success rate, path length pre/post shortcutting, planning time, a proper planner eval table"],
    masteryGate: "gold",
    masteryTest: "Your arm plans collision-free through a cluttered scene across 50 random seeds at ≥90% success, with the eval table and one paragraph on where sampling planners struggle (narrow passages).",
    diagnostic: "Why do grids fail in 7D? What does goal biasing trade? What does RRT* add over RRT?",
  },
  {
    id: "l9-trajopt",
    level: 9,
    title: "Trajectory Optimization (Intuition + One Build)",
    track: "core",
    labs: ["robotics", "math"],
    why: "The other planning philosophy: write costs and constraints, let an optimizer shape the whole trajectory. Bridges your MPC to modern methods (and to GCS-style research directions you should recognize).",
    objectives: [
      "Direct transcription: trajectory as decision variables; dynamics as constraints",
      "Cost shaping (smoothness, effort, obstacle penalties); local-minimum honesty",
      "Where trajopt vs sampling wins (smoothness/constraints vs global search)",
    ],
    prereqs: [{ id: "l6-lqr", tier: "gold" }, { id: "l9-sampling-planning" }],
    hours: 5,
    primary: { resourceId: "underactuated", sections: "Ch 10 (direct methods) + one collocation exercise" },
    equations: ["\\min_{x_{0:T},u_{0:T}} \\sum_t c(x_t,u_t) \\;\\text{s.t.}\\; x_{t+1}=f(x_t,u_t),\\; g(x_t)\\le 0"],
    implementation: "Direct transcription for the double integrator with an obstacle (cvxpy where convex; scipy minimize where not); warm-start from your RRT path and watch it smooth.",
    exercises: ["Show a bad initialization landing in a local minimum; fix via RRT warm start, the classic hybrid pipeline"],
    masteryGate: "silver",
    masteryTest: "RRT-seeds-trajopt pipeline producing a smooth, constraint-satisfying arm motion, plus a half-page on why modern stacks hybridize sampling + optimization.",
    diagnostic: "Why does trajopt need a good initial guess where RRT doesn't? What's a dynamics 'defect' constraint?",
  },
  {
    id: "l9-manipulation-pipeline",
    level: 9,
    title: "Geometric Pick-and-Place (Tedrake Ch 3)",
    track: "core",
    labs: ["robotics"],
    why: "The single best implementation chapter in robotics education: spatial algebra → differential IK → a complete pick-and-place state machine. Everything you built (frames, IK, trajectories, perception) snaps together here.",
    objectives: [
      "Grasp/pregrasp frames designed with your SE(3) algebra",
      "Differential-IK trajectory following through keyframes",
      "The pick state machine: approach, close, lift, transport, place, retreat",
    ],
    prereqs: [{ id: "l8-pose-estimation", tier: "gold" }, { id: "l5-trajectories", tier: "gold" }],
    hours: 6,
    primary: { resourceId: "tedrake-manipulation", sections: "Ch 3 Basic Pick and Place (+ its exercises, ported into your MuJoCo stack)" },
    implementation: "In MuJoCo (your stack, not Drake): scripted pick-and-place of a known-pose cube with the full keyframe pipeline; gripper contact handled; 20-trial success eval.",
    exercises: ["Randomize the cube pose ±5cm/±30°: measure where the scripted pipeline starts failing, the motivating data for LEARNED policies"],
    masteryGate: "gold",
    masteryTest: "≥90% pick success over 20 randomized trials with your own pipeline, plus the failure-boundary study writeup (the punchline: this is why Level 11 exists).",
    diagnostic: "Why a pregrasp pose? What breaks if you interpolate gripper poses naively in SE(3)?",
  },
  {
    id: "l9-grasping",
    level: 9,
    title: "Grasping (Antipodal + Learned, Briefly)",
    track: "core",
    labs: ["robotics"],
    why: "Just enough grasp theory to be dangerous: antipodal intuition and force-closure vocabulary. The modern answer is mostly learned or heuristic (audited cut: wrench-space depth skipped).",
    objectives: [
      "Antipodal grasps; friction cones (concept)",
      "Grasp candidate generation from point clouds (normals-based)",
      "Force/form closure as vocabulary; where learned grasping took over",
    ],
    prereqs: [{ id: "l9-manipulation-pipeline" }],
    hours: 4,
    primary: { resourceId: "tedrake-manipulation", sections: "Ch 5 Bin Picking (antipodal grasping in clutter)" },
    exercises: ["Generate antipodal candidates on your segmented object clouds; execute the top-ranked grasp; log success by object shape"],
    masteryGate: "silver",
    masteryTest: "Cloud-in, grasp-out: your candidate generator + ranker picks 3 novel objects at ≥70% in sim, with honest per-object stats.",
    diagnostic: "What makes a grasp antipodal? Why do parallel-jaw grippers simplify the problem so much?",
  },
  {
    id: "l9-nav-moveit",
    level: 9,
    title: "Nav2 & MoveIt 2 Tasters",
    track: "code",
    labs: ["robotics"],
    why: "The production stacks, tasted not married: Nav2 navigating your P11 robot, MoveIt planning for an arm. You learn enough to use them, read their configs, and know what your from-scratch versions correspond to.",
    objectives: [
      "Nav2: slam_toolbox map → AMCL → goal sending from rclpy; BT concept, costmaps",
      "MoveIt 2: planning scene, one moveit_py motion request on a Panda/UR demo",
      "Mapping YOUR implementations to THEIR components (A*↔planner server, your IK↔IK plugins)",
    ],
    prereqs: [{ id: "l7-ros-robot-project", tier: "gold" }],
    hours: 4,
    primary: { resourceId: "nav2", sections: "Bringup on your sim robot: map, localize, navigate" },
    backup: { resourceId: "moveit2", sections: "Panda/UR pick-place tutorial + moveit_py request" },
    exercises: ["Send nav goals from a Python node while watching costmaps; then read the Nav2 params file and annotate 10 parameters with their meaning"],
    masteryGate: "silver",
    masteryTest: "Your P11 robot autonomously navigates a mapped world to clicked goals; a MoveIt demo arm executes one scripted plan, both with a written 'my-code ↔ their-component' correspondence table.",
    diagnostic: "Which Nav2 pieces are your A*, your localization filter, your controller? What is a planning scene?",
  },
  {
    id: "boss-autonomy",
    level: 9,
    title: "BOSS: Autonomy",
    track: "project",
    labs: ["robotics"],
    why: "The handover's Autonomy Boss: a simulated system that perceives, decides, moves, manipulates, and recovers, the classical-robotics capstone before learning takes over.",
    objectives: ["Integrate levels 5–9 into one demonstrable autonomous behavior"],
    prereqs: [
      { id: "l9-manipulation-pipeline", tier: "gold" },
      { id: "l9-grasping" },
      { id: "l9-sampling-planning", tier: "gold" },
      { id: "l8-perception-project", tier: "gold" },
    ],
    hours: 5,
    masteryGate: "gold",
    masteryTest: "The Tabletop Butler (fixed-base variant per the de-scope decision): on 'clean up', perceive 3 randomized objects by language prompt, plan collision-free motions, grasp and sort each into bins, and RECOVER from at least one induced failure (dropped object re-detected and re-grasped). ≥80% task completion over 10 randomized episodes, video + eval table + architecture diagram. (Mobile-base stretch only if ahead of schedule.)",
    diagnostic: "No separate diagnostic. Use this node's mastery test.",
    exercises: [],
    projectIds: ["p15-mobile-manipulator"],
  },
];
